### ISSUE TITLE
lxc-stop hangs

### ISSUE THREAD

**Issue by shijialee** [lxc/lxc#1147] opened 2016-08-22 12:58 UTC
Hi, 

```
% lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty

% dpkg -l |grep lxc
ii  liblxc1                             1.0.8-0ubuntu0.3                 amd64        Linux Containers userspace tools (library)
ii  lxc                                 1.0.8-0ubuntu0.3                 amd64        Linux Containers userspace tools
ii  lxc-templates                       1.0.8-0ubuntu0.3                 amd64        Linux Containers userspace tools (templates)
ii  python3-lxc                         1.0.8-0ubuntu0.3                 amd64        Linux Containers userspace tools (Python 3.x bindings)

% lxc-ls -f
NAME     STATE    IPV4  IPV6  AUTOSTART
---------------------------------------
app      STOPPED  -     -     YES
app1     RUNNING  -     -     YES
app2     STOPPED  -     -     YES
app3     STOPPED  -     -     YES
app4     STOPPED  -     -     YES
base_os  STOPPED  -     -     YES

% lxc-info -n app1
Name:           app1
State:          RUNNING
PID:            7831
CPU use:        0.03 seconds
BlkIO use:      0 bytes
Memory use:     1000.00 KiB
KMem use:       0 bytes
Link:           vethOI2RY0
 TX bytes:      648 bytes
 RX bytes:      552 bytes
 Total bytes:   1.17 KiB

% ps aux | grep lxc-start
qiang     7795  0.0  0.0  43160  1564 ?        Ss   20:04   0:00 lxc-start -n app1 -d
qiang     9305  0.0  0.0  11740   924 pts/1    S+   20:30   0:00 grep --color lxc-start

% lxc-stop -n app1 -k
% sudo strace -f -odebug_kill.out -p  7795
```

Also include dmesg, ps -faux, strace output

[debug.out.txt](https://github.com/lxc/lxc/files/430122/debug.out.txt)
[dmesg.txt](https://github.com/lxc/lxc/files/430131/dmesg.txt)
[ps_faux.txt](https://github.com/lxc/lxc/files/430121/ps_faux.txt)

**Comment by brauner** [comment] 2016-08-22 13:11
From the `dmesg.txt` log it looks like you experienced a kernel crash right after container start `kernel BUG at /build/linux-zODV55/linux-3.13.0/kernel/cred.c:423!`. For completeness can you attach the containers config and the output of `uname -a`?

**Comment by shijialee** [comment] 2016-08-22 13:19
Is app1 config enough? let me know if you need something else.

```
% uname -a
Linux staging1 3.13.0-86-generic #131-Ubuntu SMP Thu May 12 23:33:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

% cat .local/share/lxc/app1/config
lxc.mount.entry = proc proc proc nodev,noexec,nosuid 0 0
lxc.mount.entry = sysfs sys sysfs defaults 0 0
lxc.mount.entry = /sys/fs/fuse/connections sys/fs/fuse/connections none bind,optional 0 0
lxc.mount.entry = /sys/kernel/debug sys/kernel/debug none bind,optional 0 0
lxc.mount.entry = /sys/kernel/security sys/kernel/security none bind,optional 0 0
lxc.mount.entry = /sys/fs/pstore sys/fs/pstore none bind,optional 0 0
lxc.mount.entry = /dev/console dev/console none bind,create=file 0 0
lxc.mount.entry = /dev/full dev/full none bind,create=file 0 0
lxc.mount.entry = /dev/null dev/null none bind,create=file 0 0
lxc.mount.entry = /dev/random dev/random none bind,create=file 0 0
lxc.mount.entry = /dev/tty dev/tty none bind,create=file 0 0
lxc.mount.entry = /dev/urandom dev/urandom none bind,create=file 0 0
lxc.mount.entry = /dev/zero dev/zero none bind,create=file 0 0
lxc.mount.entry = /sys/firmware/efi/efivars sys/firmware/efi/efivars none bind,optional 0 0
lxc.mount.entry = /proc/sys/fs/binfmt_misc proc/sys/fs/binfmt_misc none bind,optional 0 0
lxc.tty = 4
lxc.pts = 1024
lxc.arch = x86_64
lxc.seccomp = /usr/share/lxc/config/common.seccomp
lxc.utsname = app1
lxc.network.type = veth
lxc.network.flags = up
lxc.network.link = lxcbr0
lxc.network.hwaddr = 00:16:3e:bf:9d:af
lxc.cap.drop = sys_module
lxc.cap.drop = mac_admin
lxc.cap.drop = mac_override
lxc.cap.drop = sys_time
lxc.id_map = u 0 100000 65536
lxc.id_map = g 0 100000 65536
lxc.rootfs = overlayfs:/home/qiang/.local/share/lxc/base_os/rootfs:/home/qiang/.local/share/lxc/app1/delta0
lxc.pivotdir = lxc_putold
lxc.start.auto = 1
lxc.start.delay = 5
```

**Comment by brauner** [comment] 2016-08-22 13:35
This looks like a bug either in the `overlayfs` module or in `apparmor` (/cc @stgraber).

**Comment by stgraber** [comment] 2016-08-23 02:44
PID1 in the container being stuck in D state with a bunch of zombies underneath it and that oops sure smells like a kernel bug.

Can you file a bug against the Ubuntu kernel with this backtrace?
Bonus point if it's something you can reasonably easily reproduce.

**Comment by brauner** [comment] 2016-08-25 15:26
Closing as this is likely not an `LXC` bug.

**Closed by brauner** 2016-08-25 15:26 UTC
