### ISSUE TITLE
ArchLinux template double tty problems

### ISSUE THREAD

**Issue by xor-gate** [lxc/lxc#484] opened 2015-04-04 16:52 UTC
With lxc v.1.1.1 on ArchLinux as host i try to create ArchLinux containers. This works only after running lxc-console I get the following double tty login:

```
Arch Linux 3.19.2-1-ARCH (lxc/tty1)

arch1234 login:
Arch Linux 3.19.2-1-ARCH (pts/0)

arch1234 login:
```

It seems that this piece of code which creates tty's for systemd seems get in the way:
https://github.com/lxc/lxc/blob/master/templates/lxc-archlinux.in#L110-L126

Also I needed to add pts/0 to /etc/securetty to enable login

Maybe somebody could try to reproduce this and see if we really need creation of the tty's for systemd.

I also asked the same question on ServerFault here: http://serverfault.com/questions/678502/linuxcontainers-arch-linux-double-login-tty

(Same issue on debian with systemd exists on issue #520)

**Comment by xor-gate** [comment] 2015-08-12 20:41
When lxc-tty1 is disabled using systemd systemctl command only one tty shows up.

lxc-attach -n arch1234 -- systemctl disable getty@lxc-tty1.service
lxc-attach -n arch1234 -- systemctl stop getty@lxc-tty1.service

The lxc-tty1 is created within the LXC template.

**Comment by xor-gate** [comment] 2016-01-04 18:17
Closed by https://github.com/lxc/lxc/commit/a3d42f4bd6313bf2a6e43d2cd64b379d1fce0f32

**Comment by sim590** [comment] 2016-01-05 15:48
#746 doesn't fix this issue just yet. You should reopen the issue.

**Comment by xor-gate** [comment] 2016-01-05 15:50
@sim590, you are right I looked with a half eye :+1: @ar45 or somebody could probably backport this to the archlinux template as wel..

**Comment by sim590** [comment] 2016-01-05 16:13
@ar45 If I can throw something here that could help: as mentionned in #520, issuing the following command works as expected *on arch too*:

```sh
lxc-console -n <container> -t 0
```

I found this was worth mentionning since the issue is platform dependant.

**Comment by brauner** [comment] 2018-02-06 10:02
This should be fixed in git master.

**Closed by brauner** 2018-02-06 10:02 UTC
