### ISSUE TITLE
Container with debian 8 doesn't restore use lxc-checkpoint

### ISSUE THREAD

**Issue by ofinto** [lxc/lxc#1853] opened 2017-10-11 12:23 UTC
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 16.04.3 LTS
```
# lxc-start --version 2.0.8
```
```
# lxc-checkconfig
Kernel configuration not found at /proc/config.gz; searching...
Kernel configuration found at /boot/config-4.4.0-96-generic
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Warning: newuidmap is not setuid-root
Warning: newgidmap is not setuid-root
Network namespace: enabled
Multiple /dev/pts instances: enabled

--- Control groups ---
Cgroup: enabled
Cgroup clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled
Macvlan: enabled
Vlan: enabled
Bridges: enabled
Advanced netfilter: enabled
CONFIG_NF_NAT_IPV4: enabled
CONFIG_NF_NAT_IPV6: enabled
CONFIG_IP_NF_TARGET_MASQUERADE: enabled
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled
FUSE (for use with lxcfs): enabled

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities: enabled

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig

```
```
# uname -a
Linux lxcmaster08-seosf-wz 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
```
# cat /proc/self/cgroup
11:freezer:/user/root/0
10:devices:/user.slice/user-0.slice/session-c7.scope
9:blkio:/user.slice/user-0.slice/session-c7.scope
8:pids:/user.slice/user-0.slice/session-c7.scope
7:memory:/user.slice/user-0.slice/session-c7.scope
6:cpuset:/
5:cpu,cpuacct:/user.slice/user-0.slice/session-c7.scope
4:perf_event:/
3:net_cls,net_prio:/
2:hugetlb:/
1:name=systemd:/user.slice/user-0.slice/session-c7.scope
```
```
# cat /proc/1/mounts
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
udev /dev devtmpfs rw,nosuid,relatime,size=65937752k,nr_inodes=16484438,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=13191584k,mode=755 0 0
/dev/sda1 / ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset,clone_children 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime 0 0
mqueue /dev/mqueue mqueue rw,relatime 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=39,pgrp=1,timeout=0,minproto=5,maxproto=5,direct 0 0
fusectl /sys/fs/fuse/connections fusectl rw,relatime 0 0
lxcfs /var/lib/lxcfs fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
data /data zfs rw,relatime,xattr,noacl 0 0
tmpfs /run/user/1004 tmpfs rw,nosuid,nodev,relatime,size=13191584k,mode=700,uid=1004,gid=1004 0 0
tmpfs /run/user/0 tmpfs rw,nosuid,nodev,relatime,size=13191584k,mode=700 0 0
data/d1 /var/lib/lxc/d1/rootfs zfs rw,relatime,xattr,noacl 0 0
binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc rw,relatime 0 0
```

# Issue description

The recovery from checkpoint of the container with debian8 does not work, but ubuntu 12.04 based on debian 7 and 14.04 based on debian 8 works.

# Steps to reproduce

1. Create container
```
lxc-create -t download -B zfs --zfsroot=data -n d1 -- -d debian -r jessie -a amd64
```
2. Add the following lines
```
cat | tee -a /var/lib/lxc/d1/config << EOF
# hax for criu
lxc.console = none
lxc.tty = 0
lxc.cgroup.devices.deny = c 5:1 rwm
EOF
```
3. Start container and checkpoint the container
```
lxc-start -n d1
sleep 5s
lxc-checkpoint -s -D /tmp/d1 -n d1
```
4. Restore the container
```
lxc-checkpoint -r -D /tmp/d1 -n d1 -l DEBUG -o debug.log
```

- [config.txt](https://github.com/lxc/lxc/files/1375510/config.txt)
- [debug.log](https://github.com/lxc/lxc/files/1375511/debug.log)
- [dmesg.txt](https://github.com/lxc/lxc/files/1375512/dmesg.txt)

**Comment by brauner** [comment] 2017-10-11 12:25
I need to see the `dump` and `restore` logs that can be found under `/tmp/d1`, please.

**Comment by ofinto** [comment] 2017-10-11 12:35
No problem
[dump.log](https://github.com/lxc/lxc/files/1375557/dump.log)
[restore.log](https://github.com/lxc/lxc/files/1375558/restore.log)

**Comment by brauner** [comment] 2017-10-11 13:11
@ofinto, this is a CRIU issue not liblxc one. It looks like the socket type is not supported. You should try to reproduce the failure with the latest CRIU release and if you can still reproduce open an issue at https://github.com/checkpoint-restore/criu . Closing this here. :)

**Closed by brauner** 2017-10-11 13:11 UTC
Labels: Incomplete
