### ISSUE TITLE
A socketcan problem in container——socket: Address family not supported by protocol

### ISSUE THREAD

**Issue by lovinghao** [lxc/lxc#3626] opened 2021-01-20 06:02 UTC
* Distribution: Debian
 * Distribution version: 9
 * Lxc version: 3.2.1

# Issue description

I have a problem in using can device. When I enter my container and do the test below, it turns out an error.
![image](https://user-images.githubusercontent.com/13519613/105132122-4eddac00-5b25-11eb-9be3-e4b3ddae2b4c.png)

I can see my device using ifconfig.
![image](https://user-images.githubusercontent.com/13519613/105132245-8a787600-5b25-11eb-856b-788043adc130.png)

I find the container have no route can and can-bcm in /proc/net/ camparing with the host os.
![image](https://user-images.githubusercontent.com/13519613/105132655-4174f180-5b26-11eb-82a8-214fbe86474a.png)
![image](https://user-images.githubusercontent.com/13519613/105132790-7b45f800-5b26-11eb-8495-a34dfef2d286.png)

I don't know why the can0 device can't work well. Maybe it's the reason I show up. Please show me the way to fix it. Thank you.

**Comment by mihalicyn** [comment] 2024-02-23 09:31
Duplicate of https://github.com/lxc/lxc/issues/3635

**Comment by lovinghao** [comment] 2024-02-23 09:32
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Closed by mihalicyn** 2024-02-23 09:31 UTC
