### ISSUE TITLE
'lxc-wait' command returns error code immediate if container is stopped

### ISSUE THREAD

**Issue by vinod-990** [lxc/lxc#2027] opened 2017-12-12 13:45 UTC
Hi,

$subj

[$]> lxc-start --version                                                                                                                     
2.1.1

STR:
-stop container
-run lxc-wait -n \<container name\> --state=RUNNING

Here is an example
```
[#]> lxc-info -sn container1
State:          STOPPED
[$]> lxc-wait -n container1 --state=RUNNING --timeout=600
[$]> echo $?
1
```

The issue is not reproducible on lxc-2.0.X. Also 'lxc-wait' command works for other statuses if the container is started. Please advice.

**Comment by brauner** [comment] 2017-12-12 14:01
Right, this is an issue caused by the deprecation of the `lxc-monitord` binary which would've simply caused this to block. I was waiting for someone to bring this up and whether we need to think about a solution to this. So one way to deal with this for now is essentially to use `lxc-monitor` which will block. But it will report the states for all containers under a given path.

**Comment by brauner** [comment] 2018-01-17 14:24
Should be closed by https://github.com/lxc/lxc/pull/2089 .

**Closed** 2018-01-17 23:44 UTC
