### ISSUE TITLE
LXC BROKEN - Container configs missing for most distributions

### ISSUE THREAD

**Issue by ich777** [lxc/lxc#4325] opened 2023-07-07 09:27 UTC
# Required information

 * Distribution: `Unraid (Slackware)`
 * Distribution version: `6.12.2 (Slackware 15.0)`
 * The output of
   * `lxc-start --version`: `5.0.2`
   * `lxc-checkconfig`:
```
LXC version 5.0.2

Kernel configuration not found at /proc/config.gz; searching...
Kernel configuration found at /lib/modules/6.1.36-Unraid/build/.config

--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: enabled

--- Control groups ---
Cgroups: enabled
Cgroup namespace: enabled
Cgroup v1 mount points: 
Cgroup v2 mount points: 
 - /sys/fs/cgroup
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, loaded
Macvlan: enabled, not loaded
Vlan: enabled, not loaded
Bridges: enabled, loaded
Advanced netfilter: enabled, loaded
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
FUSE (for use with lxcfs): enabled, not loaded

--- Checkpoint/Restore ---
checkpoint restore: missing
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities: enabled

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig
```
   * `uname -a`: `Linux TestServer 6.1.36-Unraid #1 SMP PREEMPT_DYNAMIC Wed Jun 28 07:51:54 PDT 2023 x86_64 Intel(R) Core(TM) i5-10600 CPU @ 3.30GHz GenuineIntel GNU/Linux`
   * `cat /proc/self/cgroup`: `0::/`
   * `cat /proc/1/mounts` : I really don't want to included that here because I have a lot of Docker containers and those also show up here and would mess up the report

# Issue description

It seems like the container config files are missing for most distributions, I've tested it with Ubuntu Bionic (not working), Debian Bullseye/Bookworm (not working) and Alpine Edge (working).
I've even tried to delete the download cache to force a container pull but that didn't fix it either.

Steps to reproduce at the bottom.

# Steps to reproduce

 1. Issue: `lxc-create --name debian --template download -- --dist debian --release bookworm --arch amd64`
 2. Wait for it to finish and see these messages:
```
Downloading the image index
Downloading the rootfs
Downloading the metadata
The image cache is now ready
Unpacking the rootfs
ERROR: meta tarball is missing the configuration file
lxc-create: debian: ../src/lxc/lxccontainer.c: create_run_template: 1628 Failed to create container from template
lxc-create: debian: ../src/lxc/tools/lxc_create.c: main: 317 Failed to create container debian
```

**Comment by kaleb-utilityapi** [comment] 2023-07-07 13:25
I noticed this with Ubuntu Focal, and it looks like the `meta.tar.xz` file is missing a good bit of files between today's and yesterday's builds: https://images.linuxcontainers.org/images/debian/bookworm/amd64/default/

**Comment by alekslyse** [comment] 2023-07-07 13:37
I can confirm I get the same error

**Comment by ich777** [comment] 2023-07-07 15:34
Sorry I don't mention people directly @stgraber & @brauner but I think this is urgent.

**Comment by tyami94** [comment] 2023-07-07 16:19
Can confirm, reproduced on multiple systems.

**Comment by soonic6** [comment] 2023-07-07 16:24
same for me

**Comment by quinndiggity** [comment] 2023-07-08 03:40
Experiencing the same -

`lxc-create -t download -n mariadb.domain.tld -- -d debian -r bookworm -a amd64`:
```
Downloading the image index
Downloading the rootfs
Downloading the metadata
The image cache is now ready
Unpacking the rootfs
ERROR: meta tarball is missing the configuration file
lxc-create: mariadb.domain.tld: ../src/lxc/lxccontainer.c: create_run_template: 1628 Failed to create container from template
lxc-create: mariadb.domain.tld: ../src/lxc/tools/lxc_create.c: main: 317 Failed to create container mariadb.domain.tld
```

Same with `lxc-create -t download -n mariadb.domain.tld -- -d ubuntu-r jammy -a amd64`

This is on a debian 12 host; working without issue until the last several hours.

**Comment by quinndiggity** [comment] 2023-07-08 03:40
Experiencing the same -

`lxc-create -t download -n mariadb.domain.tld -- -d debian -r bookworm -a amd64`:
```
Downloading the image index
Downloading the rootfs
Downloading the metadata
The image cache is now ready
Unpacking the rootfs
ERROR: meta tarball is missing the configuration file
lxc-create: mariadb.domain.tld: ../src/lxc/lxccontainer.c: create_run_template: 1628 Failed to create container from template
lxc-create: mariadb.domain.tld: ../src/lxc/tools/lxc_create.c: main: 317 Failed to create container mariadb.domain.tld
```

Same with `lxc-create -t download -n mariadb.domain.tld -- -d ubuntu jammy -a amd64`

This is on a debian 12 host; working without issue until the last several hours.

**Comment by quinndiggity** [comment] 2023-07-08 04:00
> I noticed this with Ubuntu Focal, and it looks like the `meta.tar.xz` file is missing a good bit of files between today's and yesterday's builds: Here's Debian Bookworm's, for example: https://images.linuxcontainers.org/images/debian/bookworm/amd64/default/

Just to summarize the differences:

```
curl 'https://images.linuxcontainers.org/images/debian/bookworm/amd64/default/20230706_05%3A24/meta.tar.xz' > meta.1.tar.xz
curl 'https://images.linuxcontainers.org/images/debian/bookworm/amd64/default/20230707_05%3A24/meta.tar.xz' > meta.2.tar.xz
tar -tf meta.1.tar.xz > meta.1.list
tar -tf meta.2.tar.xz > meta.2.list
tar -xf meta.1.tar.xz
```

`diff meta.1.list meta.2.list`:

```
< config
< config-user
< config-user.1
< config-user.2
< config-user.3
< config-user.4
< config.1
< config.2
< config.3
< config.4
< templates
```

```
diff meta.1.list meta.2.list | tail -n +2 | sed 's/^..\(.\+\)$/\1/' | xargs -I{} sh -c "echo '{}:\n'; cat '{}' | sed 's/^/    /'; echo"
```

```
config:

    lxc.include = LXC_TEMPLATE_CONFIG/common.conf
    lxc.arch = linux64

config-user:

    lxc.include = LXC_TEMPLATE_CONFIG/common.conf
    lxc.include = LXC_TEMPLATE_CONFIG/userns.conf
    lxc.arch = linux64

config-user.1:

    lxc.include = LXC_TEMPLATE_CONFIG/debian.common.conf
    lxc.include = LXC_TEMPLATE_CONFIG/debian.userns.conf
    lxc.arch = linux64

config-user.2:

    lxc.include = LXC_TEMPLATE_CONFIG/debian.common.conf
    lxc.include = LXC_TEMPLATE_CONFIG/debian.userns.conf
    lxc.arch = linux64

config-user.3:

    lxc.include = LXC_TEMPLATE_CONFIG/debian.common.conf
    lxc.include = LXC_TEMPLATE_CONFIG/debian.userns.conf
    lxc.arch = linux64

config-user.4:

    lxc.include = LXC_TEMPLATE_CONFIG/debian.common.conf
    lxc.include = LXC_TEMPLATE_CONFIG/debian.userns.conf
    lxc.arch = linux64

config.1:

    lxc.include = LXC_TEMPLATE_CONFIG/debian.common.conf
    lxc.arch = linux64

config.2:

    lxc.include = LXC_TEMPLATE_CONFIG/debian.common.conf
    lxc.arch = linux64

config.3:

    lxc.include = LXC_TEMPLATE_CONFIG/debian.common.conf
    lxc.arch = linux64

config.4:

    lxc.include = LXC_TEMPLATE_CONFIG/debian.common.conf
    lxc.arch = linux64

templates:

    /etc/hostname
    /etc/hosts
```

**Comment by quinndiggity** [comment] 2023-07-08 04:13
As an interim workaround for debian/bookworm; the cached image can be sorted with:

```
cd ~/.cache/lxc/download/debian/bookworm/amd64/default/

printf 'lxc.include = LXC_TEMPLATE_CONFIG/common.conf
lxc.arch = linux64
' > config

printf 'lxc.include = LXC_TEMPLATE_CONFIG/common.conf
lxc.include = LXC_TEMPLATE_CONFIG/userns.conf
lxc.arch = linux64
' > config-user

printf 'lxc.include = LXC_TEMPLATE_CONFIG/debian.common.conf
lxc.include = LXC_TEMPLATE_CONFIG/debian.userns.conf
lxc.arch = linux64
' > config-user.1

printf 'lxc.include = LXC_TEMPLATE_CONFIG/debian.common.conf
lxc.include = LXC_TEMPLATE_CONFIG/debian.userns.conf
lxc.arch = linux64
' > config-user.2

printf 'lxc.include = LXC_TEMPLATE_CONFIG/debian.common.conf
lxc.include = LXC_TEMPLATE_CONFIG/debian.userns.conf
lxc.arch = linux64
' > config-user.3

printf 'lxc.include = LXC_TEMPLATE_CONFIG/debian.common.conf
lxc.include = LXC_TEMPLATE_CONFIG/debian.userns.conf
lxc.arch = linux64
' > config-user.4

printf 'lxc.include = LXC_TEMPLATE_CONFIG/debian.common.conf
lxc.arch = linux64
' > config.1

printf 'lxc.include = LXC_TEMPLATE_CONFIG/debian.common.conf
lxc.arch = linux64
' > config.2

printf 'lxc.include = LXC_TEMPLATE_CONFIG/debian.common.conf
lxc.arch = linux64
' > config.3

printf 'lxc.include = LXC_TEMPLATE_CONFIG/debian.common.conf
lxc.arch = linux64
' > config.4

printf '/etc/hostname
/etc/hosts
' > templates
```

`lxc-create -t download -n mariadb.domain.tld -- -d debian -r bookworm -a amd64`:
```
Using image from local cache
Unpacking the rootfs

---
You just created a Debian bookworm amd64 (20230707_05:24) container.

To enable SSH, run: apt install openssh-server
No default root or user password are set by LXC.
```

**Comment by quinndiggity** [comment] 2023-07-08 04:21
Otherwise, if you have another host/user with a working cached image, you can source it from there instead -


If using rootless, copy from another user which has the image cached:

```
rsync -av /home/lxc-user-1/.cache/lxc/download/debian/bookworm/amd64/default/ /home/lxc-user-2/.cache/lxc/download/debian/bookworm/amd64/default/
chown -R lxc-user-2: /home/lxc-user-2/.cache/lxc/download/debian/bookworm/amd64/default/
```

Or just from another functional host:

```
rsync -av lxc-host-1:/home/lxc-user-1/.cache/lxc/download/debian/bookworm/amd64/default/ /home/lxc-user-2/.cache/lxc/download/debian/bookworm/amd64/default/
chown -R lxc-user-2: /home/lxc-user-2/.cache/lxc/download/debian/bookworm/amd64/default/
```

**Comment by ich777** [comment] 2023-07-08 05:17
@quinndiggity please don't get me wrong here.
I don't have a second machine where I can copy over the cached images nor is the cache valid forever and I can indeed fix this issue for myself but it would be of course better this is fixed by the LXC team itself. :)

**Comment by quinndiggity** [comment] 2023-07-08 07:24
@ich777 , `As an interim workaround` 😉  I'm not involved with the team behind LXC; just hoping this isn't a side effect of something like [this recent change](https://linuxcontainers.org/lxd/) 😬

**Comment by quinndiggity** [comment] 2023-07-08 07:28
Also, when running `lxc-create -t download ...`, a fresh image is cached - the image is just missing [these](https://github.com/lxc/lxc/issues/4325#issuecomment-1626770530)

None of the missing files include timestamps, etc, in their contents, so technically a functional image can be patched together by recreating said files; at least until the upstream images' build process is fixed

**Comment by Abdull** [comment] 2023-07-08 11:08
Maybe relevant:

IMHO The missing metadata files `config` and `config-user` are conditionally added in https://github.com/lxc/distrobuilder/blob/f0eb5b4bbfe1bb43a2b319cce8347451b8469bb6/image/lxc.go#L107

That *lxc/distrobuilder* `lxc.go` source file was updated just before the problems appeared: https://github.com/lxc/distrobuilder/commit/6e5be6ab0bd080db22348da2275281aeef9a4e10#diff-6b48a5a286363a4f7fd7c7650f1116cbdc53901efd5b209c1fe6cce4eba54097 (Canonical LXD transition-related ...).

**Comment by hallyn** [comment] 2023-07-08 17:00
I can confirm that re-setting HEAD to 5ef217d51cc3b31ff2a57362cbbcf10deee7a37f fixes it here.

**Comment by hallyn** [comment] 2023-07-08 17:17
https://github.com/lxc/distrobuilder/pull/747

AIUI fixed images should start rolling out in a bit.

**Comment by 4nc414g0n** [comment] 2023-07-09 08:11
same thing happened to centos8
![image](https://github.com/lxc/lxc/assets/31583536/abd07492-226a-4905-9287-3998e13d856c)

**Comment by ich777** [comment] 2023-07-09 13:35
I can confirm that with the builds from today everything is working again as it should, I will close this issue tomorrow.
Thank you @hallyn !


@4nc414g0n please try to empty your download cache from LXC.

**Comment by stgraber** [comment] 2023-07-09 14:07
All our images should have rebuilt by now or will have in a few minutes as everything is rebuilt once a day and the fix was merged yesterday.

**Closed** 2023-07-09 14:07 UTC

**Comment by Abdull** [comment] 2023-07-10 08:06
I too can confirm that [image *debian amd64,bullseye,default* works again at least since its Jenkins build *#2703*](https://jenkins.linuxcontainers.org/job/image-debian/2703/architecture=amd64,release=bullseye,variant=default/) ([its image files](https://images.linuxcontainers.org/images/debian/bullseye/arm64/default/20230710_05:24/); that image version considered as downloaded/used/tested against via https://images.linuxcontainers.org/meta/1.0/ ).

Using my usual
```
/usr/bin/lxc-create -t download -n "my-container" -- --dist debian --release bullseye --arch amd64
```
I initially still encountered the broken image problem, as *lxc-create*/*lxc-download* kept on using the broken image version from my host's image cache. Adding the [`--flush-cache` option](https://github.com/lxc/lxc/blob/lxc-5.0.2/templates/lxc-download.in#L136) forced a fresh image download, resolving the issue:

```
/usr/bin/lxc-create -t download -n "my-container" -- --dist debian --release bullseye --arch amd64 --flush-cache
```
