### ISSUE TITLE
can not run screen command from not root user

### ISSUE THREAD

**Issue by aston-r** [lxc/lxc#2257] opened 2018-04-04 17:09 UTC
Dear Developers,

The issue is appeared after updating to lxc-3.0

STR:
-run container
-connect to the container via SSH
-run screen command from not root user

Actual Result:
```
> screen
[screen is terminating]
```

I downgraded the RPMs to lxc-2.1 and the issue is not observed. I tried to include the file /usr/share/lxc/config/common.conf to check where the issue is caused by some missing parameter in template, but it did not help.
 Also I performed the strace and here are the results:

* lxc-3.0
```
[#]> grep /dev/pts/6 /tmp/screentrace.30915
stat("/dev/pts/6", {st_dev=makedev(0, 52), st_ino=9, st_mode=S_IFCHR|0620, st_nlink=1, st_uid=1000, st_gid=84, st_blksize=1024, st_blocks=0, st_rdev=makedev(136, 6), st_atime=2018/04/04-16:35:02.182073490, st_mtime=2018/04/04-16:35:02.182073490, st_ctime=2018/04/04-16:35:02.182073490}) = 0
stat("/dev/pts/6", {st_dev=makedev(0, 52), st_ino=9, st_mode=S_IFCHR|0620, st_nlink=1, st_uid=1000, st_gid=84, st_blksize=1024, st_blocks=0, st_rdev=makedev(136, 6), st_atime=2018/04/04-16:35:02.182073490, st_mtime=2018/04/04-16:35:02.182073490, st_ctime=2018/04/04-16:35:02.182073490}) = 0
chown("/dev/pts/6", 1000, 5)            = -1 EPERM (Operation not permitted) <-----!!!!!
```

* lxc-2.1
```
> grep /dev/pts/7 /tmp/screentrace.15390 
stat("/dev/pts/7", {st_dev=makedev(0, 63), st_ino=10, st_mode=S_IFCHR|0620, st_nlink=1, st_uid=1000, st_gid=5, st_blksize=1024, st_blocks=0, st_rdev=makedev(136, 7), st_atime=2018/04/04-16:43:41.734788790, st_mtime=2018/04/04-16:43:41.734788790, st_ctime=2018/04/04-16:43:41.734788790}) = 0
stat("/dev/pts/7", {st_dev=makedev(0, 63), st_ino=10, st_mode=S_IFCHR|0620, st_nlink=1, st_uid=1000, st_gid=5, st_blksize=1024, st_blocks=0, st_rdev=makedev(136, 7), st_atime=2018/04/04-16:43:41.734788790, st_mtime=2018/04/04-16:43:41.734788790, st_ctime=2018/04/04-16:43:41.734788790}) = 0
chown("/dev/pts/7", 1000, 5)            = 0
chmod("/dev/pts/7", 0620)               = 0
```

Could you please help me to identify the issue?

**Comment by brauner** [comment] 2018-04-04 18:05
I need at least:

- what distro
- what screen version
- what glibc version
- what kernel version

**Comment by vinod-990** [comment] 2018-04-04 18:52
@brauner 

Host:
```
[#]> cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core) 

[#]> uname -a
Linux XXXX 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

[#]> rpm -qi glibc
Name        : glibc
Version     : 2.17
Release     : 196.el7_4.2
Architecture: x86_64
Install Date: Mon Mar 26 15:49:05 2018
Group       : System Environment/Libraries
Size        : 14107624
License     : LGPLv2+ and LGPLv2+ with exceptions and GPLv2+
Signature   : RSA/SHA256, Sat Dec  2 14:35:03 2017, Key ID 24c6a8a7f4a80eb5
Source RPM  : glibc-2.17-196.el7_4.2.src.rpm
Build Date  : Thu Nov 30 18:53:33 2017
Build Host  : c1bm.rdu2.centos.org
```
Container:
```
> cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.4 (Maipo)

> screen -v
Screen version 4.01.00devel (GNU) 2-May-06

> rpm -qi glibc
Name        : glibc
Version     : 2.17
Release     : 196.el7
Architecture: x86_64
Install Date: Mon Nov 20 08:45:27 2017
Group       : System Environment/Libraries
Size        : 14107784
License     : LGPLv2+ and LGPLv2+ with exceptions and GPLv2+
Signature   : RSA/SHA1, Mon Aug 14 13:55:41 2017, Key ID 2c943c8a40d49220
Source RPM  : glibc-2.17-196.el7.src.rpm
Build Date  : Wed Aug  2 08:53:56 2017
Build Host  : x86-ol7-builder-02.us.oracle.com
```

**Comment by brauner** [comment] 2018-04-07 11:53
How exactly do run the screen command from a non-root user?

**Comment by aston-r** [comment] 2018-04-10 10:15
@brauner 

Yes. sure. I also checked the permissions of these devices before creating the TT, and they were the same for affected and not affected version of lxc:(

LXC-3.0
```
> ls -al /dev/ptmx
crw-rw-rw- 1 root root 5, 2 Apr 10 09:49 /dev/ptmx
> ls -al /dev/pts/ptmx
crw-rw-rw- 1 root root 5, 2 Apr 10 09:49 /dev/pts/ptmx

> screen 
[screen is terminating]
```

LXC-2.1(just downgraded rpms and restarted container)
```
> ls -al /dev/ptmx
crw-rw-rw- 1 root root 5, 2 Apr 10 10:10 /dev/ptmx
>  ls -al /dev/pts/ptmx
crw-rw-rw- 1 root root 5, 2 Apr 10 10:10 /dev/pts/ptmx

> screen
> screen -ls
There is a screen on:
        3649.pts-5.configurator (Attached)
1 Socket in /var/run/screen/S-aston.

> ps aux | grep screen
aston  6061  0.0  0.0 131812  1292 pts/5    S+   10:06   0:00 screen
```

**Comment by aston-r** [comment] 2018-04-10 10:36
@brauner 

lxc-2.1
```
189 180 0:11 /0 /dev/lxc/console rw,nosuid,noexec,relatime master:4 - devpts devpts rw,gid=5,mode=620,ptmxmode=000
146 180 0:42 / /dev/pts rw,relatime - devpts devpts rw,gid=5,mode=620,ptmxmode=666,max=1024
147 180 0:42 /ptmx /dev/ptmx rw,relatime - devpts devpts rw,gid=5,mode=620,ptmxmode=666,max=1024
148 180 0:42 /0 /dev/lxc/tty1 rw,relatime - devpts devpts rw,gid=5,mode=620,ptmxmode=666,max=1024
150 180 0:42 /1 /dev/lxc/tty2 rw,relatime - devpts devpts rw,gid=5,mode=620,ptmxmode=666,max=1024
151 180 0:42 /2 /dev/lxc/tty3 rw,relatime - devpts devpts rw,gid=5,mode=620,ptmxmode=666,max=1024
152 180 0:42 /3 /dev/lxc/tty4 rw,relatime - devpts devpts rw,gid=5,mode=620,ptmxmode=666,max=1024
```

lxc-3.0
```
190 180 0:11 /0 /dev/console rw,nosuid,noexec,relatime master:4 - devpts devpts rw,gid=5,mode=620,ptmxmode=000
146 180 0:42 / /dev/pts rw,nosuid,noexec,relatime - devpts devpts rw,mode=620,ptmx
mode=666,max=1024
147 180 0:42 /ptmx /dev/ptmx rw,nosuid,noexec,relatime - devpts devpts rw,mode=620,ptmxmode=666,max=1024
148 180 0:42 /0 /dev/lxc/tty1 rw,nosuid,noexec,relatime - devpts devpts rw,mode=620,ptmxmode=666,max=1024
150 180 0:42 /1 /dev/lxc/tty2 rw,nosuid,noexec,relatime - devpts devpts rw,mode=620,ptmxmode=666,max=1024
151 180 0:42 /2 /dev/lxc/tty3 rw,nosuid,noexec,relatime - devpts devpts rw,mode=620,ptmxmode=666,max=1024
152 180 0:42 /3 /dev/lxc/tty4 rw,nosuid,noexec,relatime - devpts devpts rw,mode=620,ptmxmode=666,max=1024
```

![selection_796](https://user-images.githubusercontent.com/22587476/38552187-0a8f98a6-3cc4-11e8-801b-71c66378fac9.png)
[lxc-2.1.txt](https://github.com/lxc/lxc/files/1894208/lxc-2.1.txt)
[lxc-3.0.txt](https://github.com/lxc/lxc/files/1894209/lxc-3.0.txt)

**Comment by brauner** [comment] 2018-04-10 11:37
Hm, why is there no `gid=5` option on 3.0.

**Comment by aston-r** [comment] 2018-04-10 12:29
@brauner 
> Hm, why is there no gid=5 option on 3.0.

maybe the behavior changed after this commit https://github.com/lxc/lxc/commit/f49007111ea2f1cffa6de43259ccf74e93a295c9

**Comment by brauner** [comment] 2018-04-11 15:25
Hm, can you show me the container's config, please?

**Comment by brauner** [comment] 2018-04-11 15:29
Right, so the problem is definitely that in `3.0` the `devpts` is mounted without `gid=5` but the detection logic looks sane to me.

**Comment by brauner** [comment] 2018-04-12 09:01
I think I have a fix for this soon.

**Comment by brauner** [comment] 2018-04-12 09:14
@aston-r, that should fix you.

**Comment by aston-r** [comment] 2018-04-12 13:39
@brauner 

Yep, screen works now. Thank you.
```
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666,max=1024 0 0
devpts /dev/ptmx devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666,max=1024 0 0
```

**Comment by brauner** [comment] 2018-04-12 13:40
Cool, glad to hear. :)

**Closed** 2018-04-12 16:31 UTC
