### ISSUE TITLE
Cannot start a gogs Docker container inside an LXD container

### ISSUE THREAD

**Issue by jokogr** [lxc/lxc#1001] opened 2016-05-04 14:37 UTC
Hello,

I am testing LXD over a freshly-installed and up-to-date Ubuntu 16.04 LTS installation with ZFS and I have trouble running a Gogs Docker container inside an LXC container.

These are the steps I am following:
```
lxc launch ubuntu:16.04 docker -p default -p docker
lxc exec docker -- apt update
lxc exec docker -- apt dist-upgrade -y
lxc exec docker -- apt install docker.io -y
lxc exec docker -- docker pull gogs/gogs
lxc exec docker -- mkdir -p /var/gogs
lxc exec docker -- docker run --name=gogs -p 10022:22 -p 10080:3000 -v /var/gogs:/data gogs/gogs
```

At this point, Docker container starts running and produces the following output:
```
May  4 14:29:42 syslogd started: BusyBox v1.24.1
error: exec: "/app/gogs/gogs": stat /app/gogs/gogs: permission denied
May  4 14:29:42 sshd[33]: Server listening on :: port 22.
May  4 14:29:42 sshd[33]: Server listening on 0.0.0.0 port 22.
error: exec: "/app/gogs/gogs": stat /app/gogs/gogs: permission denied
```

I have also tried enabling `security.privileged` for the LXC container, but it really messed up Docker:

```
lxc config set docker security.privileged true
lxc restart docker
lxc exec docker -- docker run --name=gogs -p 10022:22 -p 10080:3000 -v /var/gogs:/data gogs/gogs
```
and the output was:

```
Unable to find image 'gogs/gogs:latest' locally
latest: Pulling from gogs/gogs
420890c9e918: Pull complete
3b43b9904207: Pull complete
737b0ea9ffa6: Pull complete
849bbce27bce: Pull complete
0e3879fc8087: Pull complete
28043fe46587: Pull complete
Digest: sha256:291e8c2ddea5af0e4d07995b444a27def8eeb4f70b3c0779ea2f070dbfbcec43
Status: Downloaded newer image for gogs/gogs:latest
docker: Error response from daemon: Cannot start container b8223a8ddc4aef5cdc1d8d1d5d2a9d38c27a5d2998e13223473661251a371a3e: [10] System error: write /sys/fs/cgroup/devices/docker/b8223a8ddc4aef5cdc1d8d1d5d2a9d38c27a5d2998e13223473661251a371a3e/devices.allow: operation not permitted.
```

So, the Docker image got lost and now Docker cannot start the container.

Is there anything more I could do?

**Comment by stgraber** [comment] 2016-05-05 04:12
@hallyn any idea?

**Comment by hallyn** [comment] 2016-05-05 05:36
Hm.  Works for me:

root@x1:~# docker run --name=gogs -p 10022:22 -p 10080:3000 -v /var/gogs:/data gogs/gogs
May  5 05:35:57 syslogd started: BusyBox v1.24.1
May  5 05:35:58 sshd[29]: Server listening on :: port 22.
May  5 05:35:58 sshd[29]: Server listening on 0.0.0.0 port 22.
2016/05/05 05:35:58 [W] Custom config '/data/gogs/conf/app.ini' not found, ignore this if you're running first time
2016/05/05 05:35:58 [T] Custom path: /data/gogs
2016/05/05 05:35:58 [T] Log path: /app/gogs/log
2016/05/05 05:35:58 [I] Gogs: Go Git Service 0.9.22.0425
2016/05/05 05:35:58 [I] Log Mode: Console(Trace)
2016/05/05 05:35:58 [I] Cache Service Enabled
2016/05/05 05:35:58 [I] Session Service Enabled
2016/05/05 05:35:58 [I] SQLite3 Supported
2016/05/05 05:35:58 [I] Run Mode: Development
2016/05/05 05:35:58 [I] Listen: http://0.0.0.0:3000

That is not on zfs though.

**Comment by hallyn** [comment] 2016-05-05 06:35
On my laptop using zfs it indeed fails.  So it could either be a zfs issue, or a kernel issue (since zfs is on 4.4.0-21-generic kernel and non-zfs was on 4.2.0-34-generic)

**Comment by hallyn** [comment] 2016-05-05 06:36
Ah no, definately a zfs issue - the non-zfs was actually on 4.4.0-21-generic as well.

**Comment by jokogr** [comment] 2016-05-05 12:19
Thanks for your replies, I believe it has to do with the way I have created /var. I have followed [this guide](https://github.com/rlaager/zfs/wiki/Ubuntu-16.04-Root-on-ZFS) to install Ubuntu 16.04 with root on ZFS, which proposes the following way of creating it:

```
# zfs create -o canmount=off -o setuid=off  -o exec=off rpool/var
```

Should I enable exec and/or setuid?

**Comment by hallyn** [comment] 2016-05-05 20:36
Quoting jokogr (notifications@github.com):
> Thanks for your replies, I believe it has to do with the way I have created /var. I have followed [this guide](https://github.com/rlaager/zfs/wiki/Ubuntu-16.04-Root-on-ZFS) to install Ubuntu 16.04 with root on ZFS, which proposes the following way of creating it:
> 
> ```
> # zfs create -o canmount=off -o setuid=off  -o exec=off rpool/var
> ```
> 
> Should I enable exec and/or setuid?

Hm.  Certainly that would be a problem.  Yes I would think you'd need to change
both of those to be able to run containers.  As I said though, I do see the
same problem when I use zfs so I think it's a bug in zfs itself.  I've not had
a chance to dig further yet, unfortunately.

**Comment by jokogr** [comment] 2016-05-08 11:21
Is there anything more I could do to help you find a fix/solution?

Thanks in advance.

**Comment by hallyn** [comment] 2016-05-09 17:36
The piece which is failing is:

26661 setuid(1000)                      = 0
26661 stat("/app/gogs/gogs",  <unfinished ...>
26667 <... select resumed> )            = 0 (Timeout)
26667 select(0, NULL, NULL, NULL, {0, 20} <unfinished ...>
26661 <... stat resumed> 0xc82006a000)  = -1 EACCES (Permission denied)

This is odd as /app, /app/gogs, and /app/gogs/gogs are all
owned by 'ubuntu'.

This appears to always fail on zfs.  Simply using docker
with overlay driver on the host (on ext4) does not reproduce this.
Disabling apparmor for the container does not help.  Using the
directory backend does not reproduce this.

**Comment by hallyn** [comment] 2016-05-09 18:49
When I run docker on a host with the overlay driver with /var/lib/docker
on a zfs drive, I get an error saying that overlay on zfs is not
supported.

So this may suggest, unfortunately, that we should consider docker
in lxd with zfs backingstore unsupported for now.

**Comment by cpoole** [comment] 2016-07-15 04:28
I experience near identical issues with the mysql image on ZFS. also ZFS storage pools are mysteriously growing in size until they are empty (an 82 meg lxc container running a 200 meg container is consuming 10 gigs of space).

**Comment by brauner** [comment] 2016-07-15 07:35
Fwiw, Docker does currently not support running the `overlay` graphdriver on most `cow` systems, effectively they just suggest you use `overlay` with `ext4`. However, with kernel `4.7` it will be possible to use it at least on `btrfs`. I'm not super familiar with `zfs` but e.g. the incompatibility between `overlay` and `btrfs` stemmed from the fact that `btrfs` until this [commit](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=cdd1fedf8261cd7a73c0596298902ff4f0f04492) did not implement `RENAME_{EXCHANGE,WHITEOUT}` which `overlay` requires. A similar problem might apply to `zfs`.

**Comment by brauner** [comment] 2016-07-15 08:11
Also note, that similiar issues with `zfs` hit Docker not necessarily being related to `overlay` on `zfs`: (e.g. https://github.com/docker/docker/issues/24403#issuecomment-232641827).

**Comment by eviweb** [comment] 2016-08-26 12:21
Hi all,
I don't know if it could help, but the issue comes from the docker container run into a LXD container.
I've successfully run the gogs and mysql (my problem) containers with docker installed directly on ZFS using the zfs and overlay drivers. And this, on the same environment I've tried to run both containers in a LXD container.

**Comment by eviweb** [comment] 2016-08-29 07:21
Hi,
here are some details regarding the deployment environment:
- OS: Ubuntu 16.04 (system, LXD container)
- filesystem: ZFS (like @hallyn, ubuntu was installed like explained in https://github.com/rlaager/zfs/wiki/Ubuntu-16.04-Root-on-ZFS)
- `setuid` and `exec` settings are set to `on` for the LXD dataset
- docker-engine: 
    - 1.12 for the one installed on the host following https://docs.docker.com/engine/installation/linux/ubuntulinux/
    - 1.11.2: from the docker.io package for the one installed in the LXD container following @stgraber's article https://www.stgraber.org/2016/04/13/lxd-2-0-docker-in-lxd-712/
- LXD profiles:
    - default
    - docker

Tested in unprivileged and privileged mode.
In unprivileged mode, I also tested using the following id mappings:
```yaml
config:
  raw.lxc:|
    lxc.id_map = 
    lxc.id_map = u 0 165536 999
    lxc.id_map = g 0 165536 999
    lxc.id_map = u 1000 1000 1
    lxc.id_map = g 1000 1000 1
    lxc.id_map = u 1001 166537 64535
    lxc.id_map = g 1001 166537 64535
```
I tested this on my own computer and a VMware virtual machine.

**Comment by brauner** [comment] 2016-09-01 15:39
@eviweb, @jokogr , can you try upgrading to `Docker 1.12.1` inside the container (https://docs.docker.com/engine/installation/linux/ubuntulinux/)?. You also need to set

```
lxc config set docker security.privileged true
```

(But consider possible security implications for your specific case, please. :))

After this I get:

```
root@docker:~# docker run --name=gogs -p 10022:22 -p 10080:3000 -v /var/gogs:/data gogs/gogs
Sep  1 15:34:28 syslogd started: BusyBox v1.24.2
Sep  1 15:34:28 sshd[27]: Server listening on :: port 22.
Sep  1 15:34:28 sshd[27]: Server listening on 0.0.0.0 port 22.
2016/09/01 15:34:29 [W] Custom config '/data/gogs/conf/app.ini' not found, ignore this if you're running first time
2016/09/01 15:34:29 [T] Custom path: /data/gogs
2016/09/01 15:34:29 [T] Log path: /app/gogs/log
2016/09/01 15:34:29 [I] Gogs: Go Git Service 0.9.98.0901
2016/09/01 15:34:29 [I] Build Time: 2016-09-01 09:14:04 UTC
2016/09/01 15:34:29 [I] Build Git Hash:
2016/09/01 15:34:29 [I] Log Mode: Console(Trace)
2016/09/01 15:34:29 [I] Cache Service Enabled
2016/09/01 15:34:29 [I] Session Service Enabled
2016/09/01 15:34:29 [I] SQLite3 Supported
2016/09/01 15:34:29 [I] Run Mode: Development
2016/09/01 15:34:29 [I] Listen: http://0.0.0.0:3000
```

working with `ZFS`.

**Comment by tomposmiko** [comment] 2016-09-02 07:12
Let me jump in.
My docker does not start this way:
```
-- The start-up result is done.
Sep 02 07:03:50 miko groupadd[3903]: group added to /etc/group: name=docker, GID=999
Sep 02 07:03:50 miko groupadd[3903]: group added to /etc/gshadow: name=docker
Sep 02 07:03:50 miko groupadd[3903]: new group: name=docker, GID=999
Sep 02 07:03:50 miko systemd[1]: Reloading.
Sep 02 07:03:50 miko systemd[1]: apt-daily.timer: Adding 9h 7min 56.998223s random time.
Sep 02 07:03:50 miko systemd[1]: Reloading.
Sep 02 07:03:50 miko systemd[1]: apt-daily.timer: Adding 51min 59.109925s random time.
Sep 02 07:03:50 miko systemd[1]: Reloading.
Sep 02 07:03:50 miko systemd[1]: apt-daily.timer: Adding 7h 27min 55.294011s random time.
Sep 02 07:03:50 miko systemd[1]: Reloading.
Sep 02 07:03:50 miko systemd[1]: apt-daily.timer: Adding 1h 1.876584s random time.
Sep 02 07:03:50 miko systemd[1]: Starting Docker Socket for the API.
-- Subject: Unit docker.socket has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.socket has begun starting up.
Sep 02 07:03:50 miko systemd[1]: Listening on Docker Socket for the API.
-- Subject: Unit docker.socket has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.socket has finished starting up.
-- 
-- The start-up result is done.
Sep 02 07:03:50 miko systemd[1]: Failed to reset devices.list on /system.slice/docker.service: Operation not permitted
Sep 02 07:03:50 miko systemd[1]: Starting Docker Application Container Engine...
-- Subject: Unit docker.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has begun starting up.
Sep 02 07:03:50 miko systemd[1]: Failed to reset devices.list on /init.scope: Operation not permitted
Sep 02 07:03:50 miko systemd[1]: Failed to reset devices.list on /system.slice/cgroupfs-mount.service: Operation not permitted
Sep 02 07:03:50 miko systemd[1]: Failed to reset devices.list on /system.slice/sys-kernel-debug.mount: Operation not permitted
Sep 02 07:03:50 miko systemd[1]: Failed to reset devices.list on /system.slice/proc-cpuinfo.mount: Operation not permitted
Sep 02 07:03:50 miko systemd[1]: Failed to reset devices.list on /system.slice/system-getty.slice: Operation not permitted
Sep 02 07:03:50 miko systemd[1]: Failed to reset devices.list on /system.slice/dev-hugepages.mount: Operation not permitted
Sep 02 07:03:50 miko systemd[1]: Failed to reset devices.list on /system.slice/proc-meminfo.mount: Operation not permitted
Sep 02 07:03:50 miko systemd[1]: Failed to reset devices.list on /system.slice/proc-sys-net.mount: Operation not permitted
Sep 02 07:03:50 miko systemd[1]: Failed to reset devices.list on /system.slice/networking.service: Operation not permitted
Sep 02 07:03:50 miko systemd[1]: Failed to reset devices.list on /system.slice/proc-swaps.mount: Operation not permitted
Sep 02 07:03:50 miko systemd[1]: Failed to reset devices.list on /system.slice/systemd-journal-flush.service: Operation not permitted
Sep 02 07:03:50 miko systemd[1]: Failed to reset devices.list on /system.slice/proc-diskstats.mount: Operation not permitted
Sep 02 07:03:50 miko systemd[1]: Failed to reset devices.list on /system.slice/systemd-random-seed.service: Operation not permitted
Sep 02 07:03:50 miko systemd[1]: Failed to reset devices.list on /system.slice/rc-local.service: Operation not permitted
Sep 02 07:03:50 miko systemd[1]: Failed to reset devices.list on /system.slice/rsyslog.service: Operation not permitted
Sep 02 07:03:50 miko systemd[1]: Failed to reset devices.list on /system.slice/proc-sysrq\x2dtrigger.mount: Operation not permitted
Sep 02 07:03:50 miko systemd[1]: Failed to reset devices.list on /system.slice/cron.service: Operation not permitted
Sep 02 07:03:50 miko systemd[1]: Failed to reset devices.list on /system.slice/resolvconf.service: Operation not permitted
Sep 02 07:03:50 miko systemd[1]: Failed to reset devices.list on /system.slice/proc-uptime.mount: Operation not permitted
Sep 02 07:03:50 miko systemd[1]: Failed to reset devices.list on /system.slice/dev-.lxd\x2dmounts.mount: Operation not permitted
Sep 02 07:03:50 miko systemd[1]: Failed to reset devices.list on /system.slice/dev-fuse.mount: Operation not permitted
Sep 02 07:03:50 miko systemd[1]: Failed to reset devices.list on /system.slice/systemd-journald.service: Operation not permitted
Sep 02 07:03:50 miko systemd[1]: Failed to reset devices.list on /system.slice/ondemand.service: Operation not permitted
Sep 02 07:03:50 miko systemd[1]: Failed to reset devices.list on /system.slice/systemd-user-sessions.service: Operation not permitted
Sep 02 07:03:50 miko systemd[1]: Failed to reset devices.list on /system.slice/systemd-tmpfiles-setup.service: Operation not permitted
Sep 02 07:03:50 miko systemd[1]: Failed to reset devices.list on /system.slice/sys-fs-fuse-connections.mount: Operation not permitted
Sep 02 07:03:50 miko systemd[1]: Failed to reset devices.list on /system.slice/dev-lxd.mount: Operation not permitted
Sep 02 07:03:50 miko systemd[1]: Failed to reset devices.list on /system.slice/-.mount: Operation not permitted
Sep 02 07:03:50 miko systemd[1]: Failed to reset devices.list on /system.slice/console-getty.service: Operation not permitted
Sep 02 07:03:50 miko systemd[1]: Failed to reset devices.list on /system.slice/dev-net-tun.mount: Operation not permitted
Sep 02 07:03:50 miko systemd[1]: Failed to reset devices.list on /system.slice/proc-stat.mount: Operation not permitted
Sep 02 07:03:50 miko systemd[1]: Failed to reset devices.list on /system.slice/sys-devices-virtual-net.mount: Operation not permitted
Sep 02 07:03:50 miko systemd[1]: Failed to reset devices.list on /system.slice/dev-mqueue.mount: Operation not permitted
Sep 02 07:03:50 miko systemd[1]: Failed to reset devices.list on /system.slice/systemd-remount-fs.service: Operation not permitted
Sep 02 07:03:50 miko systemd[1]: Failed to reset devices.list on /system.slice/systemd-update-utmp.service: Operation not permitted
Sep 02 07:03:50 miko systemd[1]: Failed to reset devices.list on /system.slice/proc-sys-fs-binfmt_misc.mount: Operation not permitted
Sep 02 07:03:50 miko dockerd[3989]: time="2016-09-02T07:03:50.726963573Z" level=info msg="libcontainerd: new containerd process, pid: 3996"
Sep 02 07:03:51 miko dockerd[3989]: time="2016-09-02T07:03:51.774991939Z" level=error msg="AppArmor enabled on system but the docker-default profile could not be loaded."
Sep 02 07:03:51 miko dockerd[3989]: time="2016-09-02T07:03:51.783395701Z" level=fatal msg="Error starting daemon: error initializing graphdriver: permission denied"
Sep 02 07:03:51 miko systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Sep 02 07:03:51 miko systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has failed.
-- 
-- The result is failed.
Sep 02 07:03:51 miko systemd[1]: docker.service: Unit entered failed state.
Sep 02 07:03:51 miko systemd[1]: docker.service: Failed with result 'exit-code'.
Sep 02 07:03:51 miko systemd[1]: Reloading.
Sep 02 07:03:51 miko systemd[1]: apt-daily.timer: Adding 6h 31min 39.562487s random time.
```

LXD launch:
```
lxc launch images:ubuntu/xenial/amd64 miko -c security.privileged=true
```

```
config:
  core.https_address: 0.0.0.0
  core.trust_password: true
  storage.zfs_pool_name: tank/lxd
```

**Comment by brauner** [comment] 2016-09-02 10:12
@tomposmiko, thanks for testing. Did you also use `-p default -p docker` to launch your container? If not please retry with these options added.

**Comment by tomposmiko** [comment] 2016-09-02 10:33
@brauner 
Sorry for that, I forgot to update my comment, when later I realized my mistake.
Yes, that was the problem.
And yes, it works properly with privileged containers and docker v1.12.1 on ZFS.

**Comment by brauner** [comment] 2016-09-02 12:01
@tomposmiko, no problem. @eviweb, @jokogr closing for now. If the issue still persists, please re-open.

**Closed by brauner** 2016-09-02 12:01 UTC

**Comment by ChemAxon** [comment] 2017-11-25 19:43
@jokogr @brauner @hallyn 
Plese take a look at this:

```
root@v101:~# lxc launch images:ubuntu/xenial/amd64 t1 -p default -p docker 
Creating t1
Starting t1
root@v101:~# lxc config set t1 security.nesting true
root@v101:~# lxc stop t1
root@v101:~# lxc start t1
root@v101:~# lxc exec t1 bash
root@t1:~# apt install docker.io -y
[...doing everything...]
root@t1:~# docker run mysql
Unable to find image 'mysql:latest' locally
latest: Pulling from library/mysql
85b1f47fba49: Pull complete 
5671503d4f93: Pull complete 
3b43b3b913cb: Pull complete 
4fbb803665d0: Pull complete 
05808866e6f9: Pull complete 
1d8c65d48cfa: Pull complete 
e189e187b2b5: Pull complete 
02d3e6011ee8: Pull complete 
d43b32d5ce04: Pull complete 
2a809168ab45: Pull complete 
Digest: sha256:1a2f9361228e9b10b4c77a651b460828514845dc7ac51735b919c2c4aec864b7
Status: Downloaded newer image for mysql:latest
error: exec: "/usr/local/bin/docker-entrypoint.sh": stat /usr/local/bin/docker-entrypoint.sh: permission denied
root@t1:~# docker info|grep ^Storage
Storage Driver: vfs
WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
root@t1:~# echo '{ "storage-driver": "vfs" }' > /etc/docker/daemon.json
root@t1:~# systemctl restart docker
root@t1:~# docker info|grep ^Storage
Storage Driver: vfs
WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
root@t1:~# docker run mysql
error: database is uninitialized and password option is not specified 
  You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD
```

Credits go to my colleague, Laszlo Mucsi.

**Comment by ChemAxon** [comment] 2017-11-25 19:44
Bonus question?
When is the driver aufs and when is it vfs?

**Comment by brauner** [comment] 2017-11-26 14:31
What LXD version are you using? The `docker` profile is not needed on newer LXD versions.

I'm unsure what the problem is you're trying to show. Is the container successfully starting or not after you've changed the docker daemon config?

**Comment by tomposmiko** [comment] 2017-11-26 15:37
> What LXD version are you using? The docker profile is not needed on newer LXD versions.

I was not aware of that, thanks.

> I'm unsure what the problem is you're tryinzg to show. Is the container successfully starting or not after you've changed the docker daemon config?

See the discussion above.
MySQL docker container does not start (entrypoint.sh permission denied) in LXD container in case of following situation:

- LXD is unprivileged
- LXD storage driver is zfs

unless

- docker storage driver fixed for vfs, but defaulting to vfs is not enough

**Comment by brauner** [comment] 2017-11-26 18:24
@tomposmiko, I was actually referring to @ChemAxon's issue with running a mysql container but I tried to reproduce both issues:

Running an unprivileged container with `security.nesting` set to `true` and the docker `vfs` driver I can run `mysql` and `gogs` just fine.

**Comment by tomposmiko** [comment] 2017-11-26 19:17
@ChemAxon is a company account, I just forgot to change it to private.

> Running an unprivileged container with security.nesting set to true and the docker vfs driver I can run mysql and gogs just fine.

**Without** setting vfs explicitly? Are you sure?

**Comment by brauner** [comment] 2017-11-26 20:04
On Sun, Nov 26, 2017 at 07:17:13PM +0000, Tamas Papp wrote:
> @ChemAxon is a company account, I just forgot to change it to private.

ah, that makes sense. :)

> 
> > Running an unprivileged container with security.nesting set to true and the docker vfs driver I can run mysql and gogs just fine.
> 
> **Without** setting vfs explicitly? Are you sure?

No, I meant setting vfs explicitly.
By default Docker will apparently use overlay2 which won't work with kernels
that don't carry a patch for unprivileged overlay fs mounts. You could try to
run with upstream Docker instead of Ubuntu's docker.io.

**Comment by tomposmiko** [comment] 2017-11-26 20:57
> No, I meant setting vfs explicitly.

That's the point. Setting in explicitly you can run it successfully. If not, you can't. Despite of the vfs storage driver. Look at the above messages.
Until now AFAIK nobody was able to do that so.

@hallyn even said, that unspriv LXD + docker is unsupported now:
https://github.com/lxc/lxc/issues/1001#issuecomment-217953848

> By default Docker will apparently use overlay2 which won't work with kernels that don't carry a patch for unprivileged overlay fs mounts

No. By default earlier it was aufs and recently vfs (I've just figured out from docker docs, that aufs is obsolote) .
At least in LXD on  ZFS.
I have never seen overlay.

I might miss some points, pls enlighten me!

**Comment by brauner** [comment] 2017-11-26 21:22
> > No, I meant setting vfs explicitly.
> 
> That's the point. Setting in explicitly you can run it successfully. If not, you can't. Despite of the vfs > > > storage driver. Look at the above messages.

I don't understand. You're saying that you can run unprivileged docker containers but then you're saying "despite of the vfs driver". I think you're mixing something up. The vfs driver in Docker is nothing but a directory driver with a fancy name. If not then maybe Docker is misreporting the storage driver or uses the term "vfs" differently in some releases as this seems to be Docker 1.13 which is prior to the new naming scheme they use.

> Until now AFAIK nobody was able to do that so.

We have users running unprivileged docker containers in LXD successully and I just did it myself.

> @hallyn even said, that unspriv LXD + docker is unsupported now:
https://github.com/lxc/lxc/issues/1001#issuecomment-217953848

No, that's not what he's saying. What he's saying is that overlay on top of zfs is unsupported. Which is exactly what happens when your LXD containers are zfs based but Docker uses the overlay driver which it will do by default.
If you set the vfs driver directly it should work as you already pointed out. At least for me it does with both mysql and gogs. You should also try to run upstream Docker via https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/ and see if that fixes a bunch of those issues.

**Comment by tomposmiko** [comment] 2017-11-26 21:50
>  don't understand. You're saying that you can run unprivileged docker containers but then you're saying "despite of the vfs driver"

To be exact, despite that vfs driver is in use (according to docker info), mysql docker in unpriv lxd does not work. See @ChemAxon's comment above.

> We have users running unprivileged docker containers in LXD successully and I just did it myself.
I do that as well. There are problem only with certain scenarios like running official mysql and prostgres.
I have never tracked it down from that point.
It just does not work by default settings.

> No, that's not what he's saying. What he's saying is that overlay on top of zfs is unsupported. 

Well, my understanding was not that. It was that it does not work at all.

> Which is exactly what happens when your LXD containers are zfs based but Docker uses the overlay driver which it will do by default.

Is it the default for you?
As you can see above, for me and my colleagues the default is vfs.
So what I'm saying is that explicit setting to vfs is needed, otherwise it will be failing in certain cases, despite the fact, that vfs is in use.

That what I demoed above.
