### ISSUE TITLE
Fails to start

### ISSUE THREAD

**Issue by achow101** [lxc/lxc#1159] opened 2016-08-27 15:14 UTC
lxc is failing to start.

I am using lxc in [gitian-builder](https://github.com/devrandom/gitian-builder) and it fails to start. 

It has the following error:

```
init.lxc: failed to mount /dev/shm : No such file or directory
sudo: unknown user: ubuntu
sudo: unable to initialize policy plugin
```

This is on Ubuntu 16.04

The config file used is https://github.com/devrandom/gitian-builder/blob/master/etc/lxc.config.in

The command used to run a command on lxc is at https://github.com/devrandom/gitian-builder/blob/master/libexec/on-target

**Comment by stgraber** [comment] 2016-08-27 15:23
I think you're running into lxc.autodev. It does mount a bunch of things for you by default, including /dev/shm (I "think").

Does adding "lxc.autodev = 0" to your config fix this problem?

**Comment by brauner** [comment] 2016-08-27 15:30
You said this is on `Ubuntu 16.04` "on" as in the host is `Ubuntu 16.04` or "on" as in the container is `Ubuntu 16.04`. If the former but not the latter, does the user `ubuntu` exist? `lxc-execute` works fine without `/dev/shm` here.

**Comment by achow101** [comment] 2016-08-27 15:31
The host is Ubuntu 16.04. The container is trusty 64-bit.

The user ubuntu does not exist on the host.

**Comment by brauner** [comment] 2016-08-27 15:35
Thanks, I meant does the user `ubuntu` exist in the container? :)

**Comment by achow101** [comment] 2016-08-27 15:37
How do I check?

@stgraber Adding that removed the first error, but it still doesn't work.

**Comment by brauner** [comment] 2016-08-27 15:37
So here I can do: 

```
sudo lxc-create -n trust -t download -- -d ubuntu -r trusty -a amd64
chb@conventiont|~
> sudo lxc-execute -n trust -- sudo -u ubuntu $ENV -i bash
init.lxc.static: initutils.c: mount_fs: 36 failed to mount /proc : Device or resource busy
bash: cannot set terminal process group (1): Inappropriate ioctl for device
bash: no job control in this shell
ubuntu@trust:~$

```

**Comment by brauner** [comment] 2016-08-27 15:40
Ah, to check whether the user exists, you can chroot into the containers rootfs:

```
chb@conventiont|~
> sudo chroot /var/lib/lxc/trust/rootfs
root@conventiont:/# su ubuntu
ubuntu@conventiont:/$
```

or start the container with:

```
chb@conventiont|~
> sudo lxc-start -n trust
chb@conventiont|~
> sudo lxc-attach -n trust
root@trust:/# su ubuntu
ubuntu@trust:/$
```

**Comment by achow101** [comment] 2016-08-27 15:45
I can't attach to the container but it seems to be running

**Comment by brauner** [comment] 2016-08-27 15:51
Can you confirm this with `lxc-ls -f`? Does it show the container as running and what error do you get from `lxc-attach`?

**Comment by achow101** [comment] 2016-08-27 15:55
`lxc-ls -f` doesn't return anything. Running `sudo lxc-attach -n gitian` returns 
   
    Error: container gitian is not defined

I started the container with `sudo lxc-start -n gitian -f gitian-builder/var/lxc.config`. Running that command again says that the container is already running.

**Comment by brauner** [comment] 2016-08-27 15:59
You probably need to pass the config to `lxc-ls` and `lxc-attach` as well:

```
sudo lxc-ls -n gitian -f gitian-builder/var/lxc.config
sudo lxc-attach -n gitian -f gitian-builder/var/lxc.config
```

**Comment by achow101** [comment] 2016-08-27 16:00
No, that's not it. Passing the config to lxc-attach tells me that `-f` is an invalid option. `lxc-ls` still gives nothing.

**Comment by brauner** [comment] 2016-08-27 16:05
Hm, I'm not sure if this is before the relevant patches by Wolfgang. Can you please try

```
sudo lxc-attach -n gitian --rcfile gitian-builder/var/lxc.config
```

**Comment by achow101** [comment] 2016-08-27 16:07
That doesn't work either

**Comment by brauner** [comment] 2016-08-27 16:10
Can you chroot into the rootfs then?

**Comment by achow101** [comment] 2016-08-27 16:13
There is no gitian folder inside of /var/lib/lxc

**Comment by achow101** [comment] 2016-08-27 16:14
interestingly though I see two volumes mounted in my file explorer that appear to be for the containers.

**Comment by achow101** [comment] 2016-08-27 16:16
oh, wait. I see what's wrong. The config file specified a different rootfs.

**Comment by brauner** [comment] 2016-08-27 16:18
Yeah, that's also why `lxc-attach` doesn't work. You can pass the path to the rootfs to `lxc-attach` as well.

```
sudo lxc-attach -n trust -P /path/to/container
```

**Comment by achow101** [comment] 2016-08-27 16:21
Still get `Error: container gitian is not defined` from lxc-attach.

If I use chroot, I see that there is no user ubuntu.

**Comment by brauner** [comment] 2016-08-27 16:23
Well, at least we tracked down that error, albeigt with some difficulty. What does

```
sudo lxc-execute -n trust -- bash
```

do for you? (Which would have been the easier way to test this (But let's ignore this for now. :)).

**Comment by achow101** [comment] 2016-08-27 16:25
bash: cannot set terminal process group (1): Inappropriate ioctl for device
    bash: no job control in this shell

**Comment by brauner** [comment] 2016-08-27 16:25
But you get a shell in the container?

**Comment by achow101** [comment] 2016-08-27 16:26
Yeah

**Comment by brauner** [comment] 2016-08-27 16:29
So I don't know how you create your trusty container but on a reasonable new version of `lxc` you can do:

```
sudo lxc-create -n trust -t download -- -d ubuntu -r trusty -a amd64
```

which will download a container that comes with a user `ubuntu` already configured. In other cases you will have to create that user yourself with `lxc-attach`. However, I'm too unfamiliar with your particular setup to debug why `lxc-attach` is so refusing. If this did help you could you close the issue?

**Comment by achow101** [comment] 2016-08-27 16:33
AFAICT the system I am using uses lxc-execute to do everything. I think the problem has to do with the config file. Can you take a look at that? I linked it in the first post.

**Comment by achow101** [comment] 2016-08-27 16:40
Here is the actual config file which is generated by the .in file I linked earlier: 

```
lxc.tty = 4
lxc.pts = 1024
lxc.rootfs = /home/andy/bitcoin/gitian-builder/target-trusty-amd64
lxc.arch = amd64
lxc.cgroup.devices.deny = a
# /dev/null and zero
lxc.cgroup.devices.allow = c 1:3 rwm
lxc.cgroup.devices.allow = c 1:5 rwm
# consoles
lxc.cgroup.devices.allow = c 5:1 rwm
lxc.cgroup.devices.allow = c 5:0 rwm
lxc.cgroup.devices.allow = c 4:0 rwm
lxc.cgroup.devices.allow = c 4:1 rwm
# /dev/{,u}random
lxc.cgroup.devices.allow = c 1:9 rwm
lxc.cgroup.devices.allow = c 1:8 rwm
lxc.cgroup.devices.allow = c 136:* rwm
lxc.cgroup.devices.allow = c 5:2 rwm
# rtc
lxc.cgroup.devices.allow = c 254:0 rwm

# mounts points
lxc.mount.entry=proc /home/andy/bitcoin/gitian-builder/target-trusty-amd64/proc proc nodev,noexec,nosuid 0 0
lxc.mount.entry=sysfs /home/andy/bitcoin/gitian-builder/target-trusty-amd64/sys sysfs defaults  0 0

# Container with network virtualized using a pre-configured bridge named br0 and
# veth pair virtual network devices
# On the host, run: ifconfig br0 up 10.0.2.2
# Alternatively, you can use another IP range for the bridge interface, in this case set
# the environment variables GITIAN_HOST_IP and LXC_GUEST_IP appropriately.
lxc.network.type = veth
lxc.network.flags = up
lxc.network.link = lxcbr0
lxc.network.ipv4 = 10.0.2.5/24
lxc.network.ipv4.gateway = auto

lxc.utsname = gitian
lxc.autodev = 0
```
(I added the autodev line)

**Comment by stgraber** [comment] 2016-08-27 16:42
The problem is that the rootfs you've put in /home/andy/bitcoin/gitian-builder/target-trusty-amd64 doesn't have an ubuntu user defined.

What @brauner is asking is where did that rootfs come from in the first place, since the one that we produce (and is downloaded by lxc-create) does have that user in there.

**Comment by achow101** [comment] 2016-08-27 16:47
That rootfs is created by the script here: https://github.com/devrandom/gitian-builder/blob/master/bin/make-base-vm and copied for use here https://github.com/devrandom/gitian-builder/blob/master/libexec/make-clean-vm

**Comment by brauner** [comment] 2016-08-27 17:17
@achow101, ok, so you either should adapt your scripts to create the `ubuntu` user for you or use our `templates` via `lxc-create` (See above for the full command.). Does that help?

**Comment by achow101** [comment] 2016-08-27 17:48
Yes, thank you.

**Comment by achow101** [comment] 2016-08-27 18:09
I think I resolved the users thing, I just added a command that added the ubuntu user and that ran as root.

However, now I am getting a different problem. This is the error

```
lxc-start: lxc_start.c: main: 344 The container failed to start.
lxc-start: lxc_start.c: main: 346 To get more details, run the container in foreground mode.
lxc-start: lxc_start.c: main: 348 Additional information can be obtained by setting the --logfile and --logpriority options.
```
That happens when I do ` sudo lxc-start -n gitian -f gitian-builder/var/lxc.config`. I also see this error:
```
lxc-execute: cgfsng.c: cgfsng_create: 1072 No such file or directory - Failed to create /sys/fs/cgroup/systemd//lxc/gitian: No such file or directory
```
when I run lxc-execute.

**Comment by brauner** [comment] 2016-08-27 18:12
Can you run the command with

```
 sudo lxc-start -n gitian -f gitian-builder/var/lxc.config -l DEBUG -o gitian_debug.log
```

and append the log, please?

**Comment by achow101** [comment] 2016-08-27 18:15
```
      lxc-start 20160827141435.026 INFO     lxc_start - start.c:lxc_check_inherited:251 - closed inherited fd 4
      lxc-start 20160827141435.028 INFO     lxc_container - lxccontainer.c:do_lxcapi_start:797 - Attempting to set proc title to [lxc monitor] /var/lib/lxc gitian
      lxc-start 20160827141435.029 INFO     lxc_lsm - lsm/lsm.c:lsm_init:48 - LSM security driver AppArmor
      lxc-start 20160827141435.029 DEBUG    lxc_start - start.c:setup_signal_fd:289 - sigchild handler set
      lxc-start 20160827141435.030 DEBUG    lxc_console - console.c:lxc_console_peer_default:469 - no console peer
      lxc-start 20160827141435.030 INFO     lxc_start - start.c:lxc_init:488 - 'gitian' is initialized
      lxc-start 20160827141435.030 DEBUG    lxc_start - start.c:__lxc_start:1326 - Not dropping cap_sys_boot or watching utmp
      lxc-start 20160827141435.030 INFO     lxc_start - start.c:lxc_check_inherited:251 - closed inherited fd 4
      lxc-start 20160827141435.032 DEBUG    lxc_conf - conf.c:instantiate_veth:2614 - instantiated veth 'vethK04EGD/vethHYOA2F', index is '470'
      lxc-start 20160827141435.032 INFO     lxc_cgroup - cgroup.c:cgroup_init:68 - cgroup driver cgroupfs-ng initing for gitian
      lxc-start 20160827141435.032 ERROR    lxc_cgfsng - cgfsng.c:cgfsng_create:1072 - No such file or directory - Failed to create /sys/fs/cgroup/systemd//lxc/gitian: No such file or directory
      lxc-start 20160827141435.033 INFO     lxc_monitor - monitor.c:lxc_monitor_sock_name:178 - using monitor sock name lxc/ad055575fe28ddd5//var/lib/lxc
      lxc-start 20160827141435.036 DEBUG    lxc_cgfsng - cgfsng.c:cgfsng_setup_limits:1667 - cgroup 'devices.deny' set to 'a'
      lxc-start 20160827141435.036 DEBUG    lxc_cgfsng - cgfsng.c:cgfsng_setup_limits:1667 - cgroup 'devices.allow' set to 'c 1:3 rwm'
      lxc-start 20160827141435.036 DEBUG    lxc_cgfsng - cgfsng.c:cgfsng_setup_limits:1667 - cgroup 'devices.allow' set to 'c 1:5 rwm'
      lxc-start 20160827141435.036 DEBUG    lxc_cgfsng - cgfsng.c:cgfsng_setup_limits:1667 - cgroup 'devices.allow' set to 'c 5:1 rwm'
      lxc-start 20160827141435.036 DEBUG    lxc_cgfsng - cgfsng.c:cgfsng_setup_limits:1667 - cgroup 'devices.allow' set to 'c 5:0 rwm'
      lxc-start 20160827141435.036 DEBUG    lxc_cgfsng - cgfsng.c:cgfsng_setup_limits:1667 - cgroup 'devices.allow' set to 'c 4:0 rwm'
      lxc-start 20160827141435.036 DEBUG    lxc_cgfsng - cgfsng.c:cgfsng_setup_limits:1667 - cgroup 'devices.allow' set to 'c 4:1 rwm'
      lxc-start 20160827141435.036 DEBUG    lxc_cgfsng - cgfsng.c:cgfsng_setup_limits:1667 - cgroup 'devices.allow' set to 'c 1:9 rwm'
      lxc-start 20160827141435.036 DEBUG    lxc_cgfsng - cgfsng.c:cgfsng_setup_limits:1667 - cgroup 'devices.allow' set to 'c 1:8 rwm'
      lxc-start 20160827141435.036 DEBUG    lxc_cgfsng - cgfsng.c:cgfsng_setup_limits:1667 - cgroup 'devices.allow' set to 'c 136:* rwm'
      lxc-start 20160827141435.037 DEBUG    lxc_cgfsng - cgfsng.c:cgfsng_setup_limits:1667 - cgroup 'devices.allow' set to 'c 5:2 rwm'
      lxc-start 20160827141435.037 DEBUG    lxc_cgfsng - cgfsng.c:cgfsng_setup_limits:1667 - cgroup 'devices.allow' set to 'c 254:0 rwm'
      lxc-start 20160827141435.037 INFO     lxc_cgfsng - cgfsng.c:cgfsng_setup_limits:1671 - cgroup has been setup
      lxc-start 20160827141435.071 DEBUG    lxc_conf - conf.c:lxc_assign_network:3048 - move '(null)' to '718'
      lxc-start 20160827141435.071 WARN     lxc_start - start.c:do_start:828 - using host's /dev/null for container init's std fds, migraiton won't work
      lxc-start 20160827141435.073 DEBUG    lxc_conf - conf.c:mount_rootfs_file:559 - found '/dev/loop7' free lodev
      lxc-start 20160827141435.073 DEBUG    bdev - bdev/bdev.c:find_fstype_cb:902 - trying to mount '/dev/loop7'->'/usr/lib/x86_64-linux-gnu/lxc' with fstype 'ext3'
      lxc-start 20160827141435.073 DEBUG    bdev - bdev/bdev.c:find_fstype_cb:910 - mount failed with error: Invalid argument
      lxc-start 20160827141435.073 DEBUG    bdev - bdev/bdev.c:find_fstype_cb:902 - trying to mount '/dev/loop7'->'/usr/lib/x86_64-linux-gnu/lxc' with fstype 'ext2'
      lxc-start 20160827141435.073 DEBUG    bdev - bdev/bdev.c:find_fstype_cb:910 - mount failed with error: Invalid argument
      lxc-start 20160827141435.073 DEBUG    bdev - bdev/bdev.c:find_fstype_cb:902 - trying to mount '/dev/loop7'->'/usr/lib/x86_64-linux-gnu/lxc' with fstype 'ext4'
      lxc-start 20160827141435.073 DEBUG    bdev - bdev/bdev.c:find_fstype_cb:910 - mount failed with error: Invalid argument
      lxc-start 20160827141435.073 DEBUG    bdev - bdev/bdev.c:find_fstype_cb:902 - trying to mount '/dev/loop7'->'/usr/lib/x86_64-linux-gnu/lxc' with fstype 'squashfs'
      lxc-start 20160827141435.073 DEBUG    bdev - bdev/bdev.c:find_fstype_cb:910 - mount failed with error: Invalid argument
      lxc-start 20160827141435.073 DEBUG    bdev - bdev/bdev.c:find_fstype_cb:902 - trying to mount '/dev/loop7'->'/usr/lib/x86_64-linux-gnu/lxc' with fstype 'vfat'
      lxc-start 20160827141435.073 DEBUG    bdev - bdev/bdev.c:find_fstype_cb:910 - mount failed with error: Invalid argument
      lxc-start 20160827141435.073 DEBUG    bdev - bdev/bdev.c:find_fstype_cb:902 - trying to mount '/dev/loop7'->'/usr/lib/x86_64-linux-gnu/lxc' with fstype 'fuseblk'
      lxc-start 20160827141435.073 DEBUG    bdev - bdev/bdev.c:find_fstype_cb:910 - mount failed with error: Invalid argument
      lxc-start 20160827141435.073 ERROR    bdev - bdev/bdev.c:mount_unknown_fs:780 - failed to determine fs type for '/dev/loop7'
      lxc-start 20160827141435.087 ERROR    lxc_conf - conf.c:setup_rootfs:1221 - failed to mount rootfs
      lxc-start 20160827141435.087 ERROR    lxc_conf - conf.c:do_rootfs_setup:3612 - failed to setup rootfs for 'gitian'
      lxc-start 20160827141435.087 ERROR    lxc_conf - conf.c:lxc_setup:3694 - Error setting up rootfs mount after spawn
      lxc-start 20160827141435.087 ERROR    lxc_start - start.c:do_start:833 - failed to setup the container
      lxc-start 20160827141435.087 ERROR    lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 3)
      lxc-start 20160827141435.087 WARN     lxc_conf - conf.c:lxc_delete_network:2909 - failed to remove interface 470 '(null)'
      lxc-start 20160827141435.087 ERROR    lxc_start - start.c:__lxc_start:1353 - failed to spawn 'gitian'
      lxc-start 20160827141435.119 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - command get_cgroup failed to receive response
      lxc-start 20160827141440.124 ERROR    lxc_start_ui - lxc_start.c:main:344 - The container failed to start.
      lxc-start 20160827141440.124 ERROR    lxc_start_ui - lxc_start.c:main:346 - To get more details, run the container in foreground mode.
      lxc-start 20160827141440.124 ERROR    lxc_start_ui - lxc_start.c:main:348 - Additional information can be obtained by setting the --logfile and --logpriority options.
```

**Comment by brauner** [comment] 2016-09-01 15:57
This is sort of hard to debug given that you're not using our standard `lxc-create` tool to setup the `rootfs`. I can't consolidate the config file you pasted above and the log output you pasted. Why is it trying to mount `/dev/loop7`?

**Comment by achow101** [comment] 2016-09-01 16:15
I haven't the faintest idea. I did not write the project.

I guess I will try modifying it so that it uses lxc-create for the rootfs instead of debootstrap.

**Comment by brauner** [comment] 2016-09-01 16:20
Well, that was sort of a rhetorical question. You must be doing something with loop devices when creating the container or on your system which isn't correctly reflected in the config file of the container. Debugging loop devices on the `LXC` side is not the problem.

**Closed** 2017-04-25 12:56 UTC

**Comment by spiderywookie** [comment] 2018-05-16 03:16
Did this ever get resolved?  I'm having almost the exact same issues.
