### ISSUE TITLE
Can't start a container with lxc.mount.auto= proc:rw sys:rw cgroup:rw:force

### ISSUE THREAD

**Issue by jacquesgelinas** [lxc/lxc#3640] opened 2021-01-31 03:29 UTC
# Required information

 * Distribution: Fedora
 * Distribution version: 32
 * The output of
   * `lxc-start --version` 4.0.6
   * `lxc-checkconfig`
LXC version 4.0.6
Kernel configuration not found at /proc/config.gz; searching...
Kernel configuration found at /boot/config-5.10.8-100.fc32.x86_64
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Warning: newuidmap is not setuid-root
Warning: newgidmap is not setuid-root
Network namespace: enabled

--- Control groups ---
Cgroups: enabled

Cgroup v1 mount points: 
/sys/fs/cgroup/systemd
/sys/fs/cgroup/freezer
/sys/fs/cgroup/pids
/sys/fs/cgroup/memory
/sys/fs/cgroup/devices
/sys/fs/cgroup/blkio
/sys/fs/cgroup/cpu,cpuacct
/sys/fs/cgroup/net_cls,net_prio
/sys/fs/cgroup/cpuset
/sys/fs/cgroup/hugetlb
/sys/fs/cgroup/perf_event

Cgroup v2 mount points: 
/sys/fs/cgroup/unified

Cgroup v1 clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, loaded
Macvlan: enabled, not loaded
Vlan: enabled, not loaded
Bridges: enabled, loaded
Advanced netfilter: enabled, not loaded
CONFIG_NF_NAT_IPV4: missing
CONFIG_NF_NAT_IPV6: missing
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
FUSE (for use with lxcfs): enabled, loaded

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities: 

   * `uname -a` 5.10.8-100.fc32.x86_64 #1 SMP Sun Jan 17 19:52:43 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
   * `cat /proc/self/cgroup`
11:perf_event:/
10:hugetlb:/
9:cpuset:/
8:net_cls,net_prio:/
7:cpu,cpuacct:/user.slice
6:blkio:/user.slice
5:devices:/user.slice
4:memory:/user.slice/user-1000.slice/session-1.scope
3:pids:/user.slice/user-1000.slice/session-1.scope
2:freezer:/
1:name=systemd:/user.slice/user-1000.slice/session-1.scope
0::/user.slice/user-1000.slice/session-1.scope

   * `cat /proc/1/mounts`
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
devtmpfs /dev devtmpfs rw,nosuid,size=8128104k,nr_inodes=2032026,mode=755,inode64 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev,inode64 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,nodev,mode=755,inode64 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755,inode64 0 0
cgroup2 /sys/fs/cgroup/unified cgroup2 rw,nosuid,nodev,noexec,relatime,nsdelegate 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
none /sys/fs/bpf bpf rw,nosuid,nodev,noexec,relatime,mode=700 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
configfs /sys/kernel/config configfs rw,nosuid,nodev,noexec,relatime 0 0
/dev/sdb4 / ext4 rw,relatime 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=31,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=500 0 0
debugfs /sys/kernel/debug debugfs rw,nosuid,nodev,noexec,relatime 0 0
mqueue /dev/mqueue mqueue rw,nosuid,nodev,noexec,relatime 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime,pagesize=2M 0 0
tracefs /sys/kernel/tracing tracefs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /tmp tmpfs rw,nosuid,nodev,inode64 0 0
fusectl /sys/fs/fuse/connections fusectl rw,nosuid,nodev,noexec,relatime 0 0
none /var/www/html/printer tmpfs rw,relatime,inode64 0 0
/dev/sdb2 /boot ext4 rw,relatime 0 0
/dev/sda2 /d2 ext4 rw,relatime 0 0
/dev/sda2 /home ext4 rw,relatime 0 0
/dev/sda2 /var/lib/bolixo ext4 rw,relatime 0 0
/dev/sda2 /var/lib/bolixod ext4 rw,relatime 0 0
/dev/sda2 /var/lib/lxc ext4 rw,relatime 0 0
tmpfs /run/user/1000 tmpfs rw,nosuid,nodev,relatime,size=1629512k,mode=700,uid=1000,gid=1000,inode64 0 0
gvfsd-fuse /run/user/1000/gvfs fuse.gvfsd-fuse rw,nosuid,nodev,relatime,user_id=1000,group_id=1000 0 0
/dev/sda2 /var/lib/lxc/bolixod/rootfs/var/lib/bolixod ext4 rw,relatime 0 0
/dev/sda2 /d2/var_lib/lxc/bolixod/rootfs/var/lib/bolixod ext4 rw,relatime 0 0
/dev/sda2 /var/lib/lxc/publishd/rootfs/var/lib/bolixo ext4 ro,relatime 0 0
/dev/sda2 /d2/var_lib/lxc/publishd/rootfs/var/lib/bolixo ext4 rw,relatime 0 0
/dev/sda2 /var/lib/lxc/writed/rootfs/var/lib/bolixo ext4 rw,relatime 0 0
/dev/sda2 /d2/var_lib/lxc/writed/rootfs/var/lib/bolixo ext4 rw,relatime 0 0
/dev/sda2 /var/lib/lxc/bod/rootfs/var/lib/bolixo ext4 ro,relatime 0 0
/dev/sda2 /d2/var_lib/lxc/bod/rootfs/var/lib/bolixo ext4 rw,relatime 0 0

# Issue description

Can't start a container with cgroup:rw:force in lxc.mount.auto. The force is the issue. It was working with lxc-3. I am using force because this container (running a fedora 32 distro) is itself starting containers. The error reported is

conf.c: lxc_mount_auto_mounts: 725 Invalid cross-device link - Failed to mount "/sys/fs/cgroup"

# Steps to reproduce

The problem shows all the time. lxc-start fails.

# Information to attach

I studied lxc-start and found that by doing this simple modificatrion (patch below), it works. Now, my modification is just a hint at the problem and certainly not a real fix. For some reason mount /usr/lib64/lxc/rootfs/sys/fs/cgroup works but mount /proc/self/fd/dir-handle does not. Further openat2 fails if RESOLVE_BENEATH is used.

```
*** ../../../lxc-4.0.6/src/lxc/utils.c  2021-01-11 19:20:05.000000000 -0500
--- utils.c     2021-01-30 22:23:09.661039965 -0500
***************
*** 1082,1091 ****
        __do_close int source_fd = -EBADF, target_fd = -EBADF;
        struct lxc_open_how how = {
                .flags          = O_RDONLY | O_CLOEXEC | O_PATH,
!               .resolve        = RESOLVE_NO_SYMLINKS | RESOLVE_NO_MAGICLINKS | RESOLVE_BENEATH,
        };
        int ret;
!       char src_buf[LXC_PROC_PID_FD_LEN], tgt_buf[LXC_PROC_PID_FD_LEN];
  
        if (beneath_fd < 0)
                return -EINVAL;
--- 1082,1091 ----
        __do_close int source_fd = -EBADF, target_fd = -EBADF;
        struct lxc_open_how how = {
                .flags          = O_RDONLY | O_CLOEXEC | O_PATH,
!               .resolve        = RESOLVE_NO_SYMLINKS | RESOLVE_NO_MAGICLINKS, // | RESOLVE_BENEATH,
        };
        int ret;
!       char src_buf[LXC_PROC_PID_FD_LEN], tgt_buf[100+LXC_PROC_PID_FD_LEN];
  
        if (beneath_fd < 0)
                return -EINVAL;
***************
*** 1104,1110 ****
        target_fd = openat2(beneath_fd, dst, &how, sizeof(how));
        if (target_fd < 0)
                return -errno;
!       ret = snprintf(tgt_buf, sizeof(tgt_buf), "/proc/self/fd/%d", target_fd);
        if (ret < 0 || ret >= sizeof(tgt_buf))
                return -EIO;
  
--- 1104,1114 ----
        target_fd = openat2(beneath_fd, dst, &how, sizeof(how));
        if (target_fd < 0)
                return -errno;
!       if (strcmp(dst,"/sys/fs/cgroup")==0){
!               ret = snprintf(tgt_buf, sizeof(tgt_buf), "/usr/lib64/lxc/rootfs%s", dst);
!       }else{
!               ret = snprintf(tgt_buf, sizeof(tgt_buf), "/proc/self/fd/%d", target_fd);
!       }
        if (ret < 0 || ret >= sizeof(tgt_buf))
                return -EIO;
```

**Comment by shibe2** [comment] 2021-02-03 20:38
I have the same error with `lxc.mount.auto=cgroup:mixed`

**Comment by brauner** [comment] 2021-02-04 09:01
I'm digging into this now trying to reproduce!

**Comment by brauner** [comment] 2021-02-04 09:13
Can someone please provide the container's config and a full trace log `-l trace` from a failing container, please?

**Comment by brauner** [comment] 2021-02-04 11:07
I found and understood the issue. I created a PR for master but will backport a patch to stable-4.0 that distros can cherry-pick and ask @stgraber to publish a new point release.

**Comment by emansom** [comment] 2021-05-02 11:49
Observing this same issue on Arch with LXD version 4.13-1.

**Comment by talhazan** [comment] 2021-05-02 13:05
I have similiar issue, container starts but the mounts doesn't work
I Apply the settings through profile:

```
-----+
aurax@aurax:~/freqtrade-k8s/scripts$ lxc profile show rancher
config:
  linux.kernel_modules: overlay
  raw.lxc: |-
    lxc.apparmor.profile = unconfined
    lxc.cgroup.devices.allow = a
    lxc.mount.auto=proc:rw sys:rw
    lxc.cap.drop =
  security.nesting: "true"
  security.privileged: "true"
description: ""
devices: {}
name: rancher
used_by:

```

**Comment by stgraber** [comment] 2021-05-02 14:30
@talhazan that's most likely because your config is appending to the list instead of overriding it.

Try setting it to empty first to clear, then set to the value you want.

**Comment by brauner** [comment] 2021-07-15 16:28
Seems to be fixed. Closing. If not, please reopen.

**Closed by brauner** 2021-07-15 16:28 UTC
