### ISSUE TITLE
Permission error on /dev/stderr with unprivileged container

### ISSUE THREAD

**Issue by flx42** [lxc/lxc#2234] opened 2018-03-24 05:08 UTC
```
$ lxc-create -t oci -n nginx -- --url docker://nginx --dhcp 
$ lxc-execute -n nginx
nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
2018/03/24 05:07:15 [emerg] 3#3: open() "/var/log/nginx/error.log" failed (13: Permission denied)
```
Note: you need to modify the config manually until I fix https://github.com/lxc/lxc/issues/2195

In this image, `/var/log/nginx/error.log` is a symlink to `/dev/stderr`:
https://github.com/nginxinc/docker-nginx/blob/4f5bae5928baee89433ecb20a50283546f217dfa/mainline/stretch/Dockerfile#L92-L93

**Comment by stgraber** [comment] 2018-03-24 05:11
Isn't /dev/stderr a symlink to /proc/self/fd/2? If so, then the permission error would come because of missing world write permissions on your shell's stderr.

**Comment by flx42** [comment] 2018-03-24 05:30
Indeed, it is. Is this intended? Or should the mode be changed?

**Comment by brauner** [comment] 2018-03-24 11:18
Hm, that works for me fine after I edited the config. Oh, I bet I know what's going on. What's your kernel version?

**Comment by brauner** [comment] 2018-03-24 11:24
`/dev/stderr` is likely attached to a pty which means this should be:

`/dev/stderr -> /proc/self/fd/2 -> /dev/pts/<idx` 

but it could be:

`/dev/stderr -> /proc/self/fd/2 -> /` 

on systems with `glibc >= 2.27` and a kernels that don't include my kernel patches:
- https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=7d71109df186d630a41280670c8d71d0cf9b0da9
and especially
- https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=a319b01d9095da6f6c54bd20c1f1300762506255

**Comment by flx42** [comment] 2018-03-24 16:55
This is Ubuntu 16.04 LTS HWE: `4.13.0-37-generic`
So glibc is `2.23-0ubuntu10`.

**Comment by brauner** [comment] 2018-03-24 19:00
Hm, how bad would it for you to reproduce this with my patch?

**Comment by flx42** [comment] 2018-03-24 19:49
Is your patch in 4.16-rc6? If yes, I have a debian buster AMI with this version (created it recently for investigating https://github.com/moby/moby/issues/36674).

**Comment by brauner** [comment] 2018-03-24 20:05
@flx42, nope, it's in linux-next. When I fixed the bug it was already `rc7` so no chance of it getting in then given that it's conceptually complex. :)

**Comment by brauner** [comment] 2018-03-24 20:08
@flx42, sent you an invite to a folder with a binary that contains the fix right now.

**Comment by flx42** [comment] 2018-03-24 20:26
Thanks, maybe I'll have time to test that next week.
You said it works fine for you, was it with this kernel version?

If your kernel patch does fix the problem, will it have a chance of being backported to an Ubuntu LTS release? Or should we have a workaround in the meantime?

**Comment by brauner** [comment] 2018-03-26 00:52
@flx42, I've already took care that it will be in Bionic and Xenial. :)

**Comment by flx42** [comment] 2018-03-29 17:51
@brauner as we discussed, this works with `runc` in rootless mode:
```
$ docker-runc run ubuntu
# tty
/dev/pts/0
# ls -la /dev/stderr /proc/self/fd/2
lrwxrwxrwx 1 root root 15 Mar 29 17:41 /dev/stderr -> /proc/self/fd/2
lrwx------ 1 root root 64 Mar 29 17:43 /proc/self/fd/2 -> /dev/pts/0
# ls -la /dev/pts/0
crw--w---- 1 root root 136, 0 Mar 29 17:43 /dev/pts/0
# echo foo > /dev/stderr
foo
```

But there is something weird with lxc, it points to `/dev/pts/4` which doesn't exist, and `tty` gives `/dev/console`:
```
$ lxc-execute -n ubuntu
root@ubuntu:/# ls -la /dev/stderr /proc/self/fd/2
lrwxrwxrwx 1 root root 15 Mar 29 17:43 /dev/stderr -> /proc/self/fd/2
lrwx------ 1 root root 64 Mar 29 17:43 /proc/self/fd/2 -> /dev/pts/4
root@ubuntu:/# ls -la /dev/pts/4
ls: cannot access '/dev/pts/4': No such file or directory
root@ubuntu:/# tty
/dev/console
root@ubuntu:/# ls -la /dev/console
c--x--x--x 1 root nogroup 136, 4 Mar 29  2018 /dev/console
root@ubuntu:/# echo foo > /dev/console
bash: /dev/console: Permission denied
```

**Comment by stgraber** [comment] 2020-03-20 22:19
So ended up being a kernel and libc issue in this case, I believe we've sorted out both by now.

**Closed by stgraber** 2020-03-20 22:19 UTC

**Comment by dr-bonez** [comment] 2024-08-15 20:18
@stgraber I am struggling with an issue with these exact same symptoms on 
lxc@1:5.0.2-1+deb12u2
glibc@2.36-9+deb12u7
linux@6.9.7-1~bpo12+1

am I missing something?

**Comment by dr-bonez** [comment] 2024-08-16 20:20
I have confirmed this is also an issue on
lxc@1:6.0.1-1
glibc@2.39-6
linux@6.10.3-1
