### ISSUE TITLE
Extreme load usecase, lxc-* commands become slow

### ISSUE THREAD

**Issue by skamoen** [lxc/lxc#2093] opened 2018-01-18 20:24 UTC
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of
   * `lxc-start --version` -> 2.1.1
   * `uname -a` -> 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

# Issue description
I'm using LXC in a network honeypot scenario, where I'm cloning from a template and starting roughly 2400 containers per hour. Yes, that's a rather extreme scenario, but I have a very beefy server with 16 cores and 48GB to handle the load. 

Anyway, the system is able to handle the load for some time (roughly 2 hours without much trouble), but after a while the `lxc-*` commands become slow and unresponsive, clogging up the entire system and filling RAM with uncontrollable containers. 

For my application, I'm using the go-lxc bindings to keep track of and control the containers. A dedicated go-routine checks for container activity and freezes and stops the container after 1 and 3 minutes, respectively. [See here for the code](https://github.com/skamoen/honeytrap/blob/telnet-service_and_data-dir/director/lxc/lxc_linux.go), it's not trivial code so proceed with caution :)

Coming from 2.08, where the `lxc-*` commands stopped working altogether, 2.1 is already a big improvement but commands just aren't being processed in time. 

When things start getting sluggish, system resources definitely aren't at 100%, so I'd like to find out what the bottleneck is. Can anyone suggest some tips and tricks to increase performance? It's very hard to objectively reproduce the failures. Providing logs is difficult as we're talking thousands of containers here, and I'm not sure it's the actual containers itself are causing the issue. 

My apologies for the rather vague description. I'd be more than happy to provide any information upon request, but I'm not sure where to start looking for the improvements here. 

May be related to https://github.com/lxc/lxc/issues/1701

**Comment by brauner** [comment] 2018-01-18 20:39
Hm, interesting. What happens if you don't freeze and unfreeze the containers? The freezer cgroup in the v1 hierarchy is intrinsically racy and buggy.

**Comment by skamoen** [comment] 2018-01-18 21:18
I'll try that out and report back in a few hours with the results!

**Comment by skamoen** [comment] 2018-01-21 15:27
I think we're seeing some improvement if we skip freezing, but it's hard to tell as there are some bugs left in our application causing a buch of other issues. I'll leave this open for a bit until we can rule out LXC as the limiting factor 👍

**Comment by skamoen** [comment] 2018-01-23 22:01
After fixing a number of bugs in our application, we're left with some crashes caused by LXC. The crash log is _huge_ (4.1M), but this is the top entry. Related code [here](https://github.com/skamoen/honeytrap/blob/track-director/director/track/track.go):

```
goroutine 632862 [syscall, locked to thread]:
runtime.cgocall(0xae64e0, 0xc4301258d0, 0xc4301258d8)
        /usr/lib/go-1.9/src/runtime/cgocall.go:132 +0xe4 fp=0xc4301258a0 sp=0xc430125860 pc=0x40c444
github.com/honeytrap/honeytrap/vendor/gopkg.in/lxc/go-lxc%2ev2._Cfunc_lxc_container_new(0x7fcef02cca50, 0x0, 0x0)
        github.com/honeytrap/honeytrap/vendor/gopkg.in/lxc/go-lxc.v2/_obj/_cgo_gotypes.go:1117 +0x4e fp=0xc4301258d0 sp=0xc4301258a0 pc=0x60317e
github.com/honeytrap/honeytrap/vendor/gopkg.in/lxc/go-lxc%2ev2.NewContainer(0xc42a30bba0, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/sillekamoen/go/src/github.com/honeytrap/honeytrap/vendor/gopkg.in/lxc/go-lxc.v2/lxc-binding.go:39 +0xb4 fp=0xc430125920 sp=0xc4301258d0 pc=0x60fe54
github.com/honeytrap/honeytrap/director/track.(*trackDirector).cloneWithName(0xc420cc6480, 0xc42a30bba0, 0x11, 0x0, 0x0, 0x0)
        /home/sillekamoen/go/src/github.com/honeytrap/honeytrap/director/track/track.go:130 +0x25a fp=0xc4301259b0 sp=0xc430125920 pc=0x61f68a
github.com/honeytrap/honeytrap/director/track.(*trackDirector).getContainerMeta(0xc420cc6480, 0x14c5320, 0xc43335d088, 0x0, 0x0, 0x0)
        /home/sillekamoen/go/src/github.com/honeytrap/honeytrap/director/track/track.go:100 +0x2fd fp=0xc430125a40 sp=0xc4301259b0 pc=0x61f2ad
github.com/honeytrap/honeytrap/director/track.(*trackDirector).Dial(0xc420cc6480, 0x14c5320, 0xc43335d088, 0x0, 0x0, 0x0, 0x0)
        /home/sillekamoen/go/src/github.com/honeytrap/honeytrap/director/track/track.go:42 +0x1f2 fp=0xc430125af8 sp=0xc430125a40 pc=0x61ec22
github.com/honeytrap/honeytrap/services/telnet.(*telnetService).dialContainer(0xc420c722a0, 0x14c5320, 0xc43335d088, 0x1, 0xc42a30bac0, 0x12, 0xc431af4bf8, 0xc4289ba000)
        /home/sillekamoen/go/src/github.com/honeytrap/honeytrap/services/telnet/telnet-interaction.go:246 +0x63 fp=0xc430125ba0 sp=0xc430125af8 pc=0x89b463
github.com/honeytrap/honeytrap/services/telnet.(*telnetService).highInteraction(0xc420c722a0, 0x14c5320, 0xc43335d088, 0xc420c72301, 0x0, 0x0, 0x0)
        /home/sillekamoen/go/src/github.com/honeytrap/honeytrap/services/telnet/telnet-interaction.go:21 +0xfc fp=0xc430125e58 sp=0xc430125ba0 pc=0x89907c
github.com/honeytrap/honeytrap/services/telnet.(*telnetService).Handle(0xc420c722a0, 0x14bfa80, 0xc4200b2010, 0x14c5320, 0xc43335d088, 0x0, 0x0)
        /home/sillekamoen/go/src/github.com/honeytrap/honeytrap/services/telnet/telnet.go:118 +0x2d7 fp=0xc430125f18 sp=0xc430125e58 pc=0x89d027
github.com/honeytrap/honeytrap/server.(*Honeytrap).handle(0xc4200bd810, 0x14c5320, 0xc43335d088)
        /home/sillekamoen/go/src/github.com/honeytrap/honeytrap/server/honeytrap.go:565 +0x575 fp=0xc430125fc8 sp=0xc430125f18 pc=0xae0195
runtime.goexit()
        /usr/lib/go-1.9/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc430125fd0 sp=0xc430125fc8 pc=0x4677b1
created by github.com/honeytrap/honeytrap/server.(*Honeytrap).Run
        /home/sillekamoen/go/src/github.com/honeytrap/honeytrap/server/honeytrap.go:489 +0x31d6
```

As there are thousands of goroutines stuck before the application crashes, is there anything I should look for to make this analyzable?

**Comment by brauner** [comment] 2018-01-24 09:40
On Tue, Jan 23, 2018 at 10:02:00PM +0000, Sille Kamoen wrote:
> After fixing a number of bugs in our application, we're left with some crashes caused by LXC. The crash log is _huge_ (4.1M), but this is the top entry. Related code [here](https://github.com/skamoen/honeytrap/blob/track-director/director/track/track.go):
> 
> ```
> goroutine 632862 [syscall, locked to thread]:
> runtime.cgocall(0xae64e0, 0xc4301258d0, 0xc4301258d8)
>         /usr/lib/go-1.9/src/runtime/cgocall.go:132 +0xe4 fp=0xc4301258a0 sp=0xc430125860 pc=0x40c444
> github.com/honeytrap/honeytrap/vendor/gopkg.in/lxc/go-lxc%2ev2._Cfunc_lxc_container_new(0x7fcef02cca50, 0x0, 0x0)
>         github.com/honeytrap/honeytrap/vendor/gopkg.in/lxc/go-lxc.v2/_obj/_cgo_gotypes.go:1117 +0x4e fp=0xc4301258d0 sp=0xc4301258a0 pc=0x60317e
> github.com/honeytrap/honeytrap/vendor/gopkg.in/lxc/go-lxc%2ev2.NewContainer(0xc42a30bba0, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
>         /home/sillekamoen/go/src/github.com/honeytrap/honeytrap/vendor/gopkg.in/lxc/go-lxc.v2/lxc-binding.go:39 +0xb4 fp=0xc430125920 sp=0xc4301258d0 pc=0x60fe54
> github.com/honeytrap/honeytrap/director/track.(*trackDirector).cloneWithName(0xc420cc6480, 0xc42a30bba0, 0x11, 0x0, 0x0, 0x0)
>         /home/sillekamoen/go/src/github.com/honeytrap/honeytrap/director/track/track.go:130 +0x25a fp=0xc4301259b0 sp=0xc430125920 pc=0x61f68a
> github.com/honeytrap/honeytrap/director/track.(*trackDirector).getContainerMeta(0xc420cc6480, 0x14c5320, 0xc43335d088, 0x0, 0x0, 0x0)
>         /home/sillekamoen/go/src/github.com/honeytrap/honeytrap/director/track/track.go:100 +0x2fd fp=0xc430125a40 sp=0xc4301259b0 pc=0x61f2ad
> github.com/honeytrap/honeytrap/director/track.(*trackDirector).Dial(0xc420cc6480, 0x14c5320, 0xc43335d088, 0x0, 0x0, 0x0, 0x0)
>         /home/sillekamoen/go/src/github.com/honeytrap/honeytrap/director/track/track.go:42 +0x1f2 fp=0xc430125af8 sp=0xc430125a40 pc=0x61ec22
> github.com/honeytrap/honeytrap/services/telnet.(*telnetService).dialContainer(0xc420c722a0, 0x14c5320, 0xc43335d088, 0x1, 0xc42a30bac0, 0x12, 0xc431af4bf8, 0xc4289ba000)
>         /home/sillekamoen/go/src/github.com/honeytrap/honeytrap/services/telnet/telnet-interaction.go:246 +0x63 fp=0xc430125ba0 sp=0xc430125af8 pc=0x89b463
> github.com/honeytrap/honeytrap/services/telnet.(*telnetService).highInteraction(0xc420c722a0, 0x14c5320, 0xc43335d088, 0xc420c72301, 0x0, 0x0, 0x0)
>         /home/sillekamoen/go/src/github.com/honeytrap/honeytrap/services/telnet/telnet-interaction.go:21 +0xfc fp=0xc430125e58 sp=0xc430125ba0 pc=0x89907c
> github.com/honeytrap/honeytrap/services/telnet.(*telnetService).Handle(0xc420c722a0, 0x14bfa80, 0xc4200b2010, 0x14c5320, 0xc43335d088, 0x0, 0x0)
>         /home/sillekamoen/go/src/github.com/honeytrap/honeytrap/services/telnet/telnet.go:118 +0x2d7 fp=0xc430125f18 sp=0xc430125e58 pc=0x89d027
> github.com/honeytrap/honeytrap/server.(*Honeytrap).handle(0xc4200bd810, 0x14c5320, 0xc43335d088)
>         /home/sillekamoen/go/src/github.com/honeytrap/honeytrap/server/honeytrap.go:565 +0x575 fp=0xc430125fc8 sp=0xc430125f18 pc=0xae0195
> runtime.goexit()
>         /usr/lib/go-1.9/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc430125fd0 sp=0xc430125fc8 pc=0x4677b1
> created by github.com/honeytrap/honeytrap/server.(*Honeytrap).Run
>         /home/sillekamoen/go/src/github.com/honeytrap/honeytrap/server/honeytrap.go:489 +0x31d6
> ```
> 
> As there are thousands of goroutines stuck before the application crashes, is there anything I should look for to make this analyzable?

This looks like a locking issue. Is this reproducible with current git
master? It is not obvious that this is lxc. The deadlocks could also be
caused by your code.

**Comment by skamoen** [comment] 2018-01-24 15:09
So I switched to the master ppa for testing, but that brings a couple of new issues, which seem to get worse over time.

For about 10 minutes, everything is going alright. No issues with cloning new containers, however sometimes I get a "container failed to start". Nothing too bad. 

Later on, the cloning process becomes worse. I Mutexed the clone function, so only one at a time
```
	log.Debugf("Cloning new container %s from template %s", name, d.Template)
	if err := d.templateHandle.Clone(name, lxc.CloneOptions{
		Backend:  lxc.Overlayfs,
		Snapshot: true,
		KeepName: true,
	}); err != nil {
		log.Errorf("Failed clone container %s: %s", name, err.Error())
		return nil, err
	}

	newContainerHandle, err := lxc.NewContainer(name)
	if err != nil {
		log.Errorf("Couldn't get a handle for container %s while cloning", name)
		return nil, err
	}
```
In this snippet the templateHandle is `handle, err := lxc.NewContainer(templatename)` at the beginning of the program. Sometimes it fails at the `clone()` call, and other times it fails at getting a handle of the new container. Error messages are super generic so not much I can get from that.

**Comment by skamoen** [comment] 2018-01-24 20:19
I'll make a sample program and see if I can replicate this behaviour outside my application. Anything specific I should record to make this easier to analyze?

**Comment by brauner** [comment] 2018-01-24 20:29
On Wed, Jan 24, 2018 at 9:19 PM, Sille Kamoen <notifications@github.com>
wrote:

> I'll make a sample program and see if I can replicate this behaviour
> outside my application. Anything specific I should record to make this
> easier to analyze?
>

It should be as minimal as possible. The go-runtime and certain
namespace-sensitive syscalls do not like each other
at all.

**Comment by brauner** [comment] 2018-02-09 11:07
Did you have time to reproduce/debug? :)

**Comment by brauner** [comment] 2018-02-11 13:35
@skamoen, excellent. Thanks!

**Comment by skamoen** [comment] 2018-02-12 12:01
Unfortunately (for me) my first example is perfectly stable under similar loads, so there must be a difference somewhere. I'll keep trying to reproduce, but it'll take longer than anticipated. If you're interested, you can follow progress here: https://github.com/skamoen/lxc-stresstest

**Comment by brauner** [comment] 2018-02-12 12:56
> Unfortunately (for me) my first example is perfectly stable under similar loads, so there must be a 

Hm, what do you mean? You mean you can't reproduce anymore or you can reliably reproduce the slowdown?

> difference somewhere. I'll keep trying to reproduce, but it'll take longer than anticipated. If you're 

No worries. Thanks for the effort you're putting into this.

**Comment by brauner** [comment] 2018-06-26 13:57
There have been a bunch of thread-safety improvements in the last couple of months so tentatively closing. If you can reproduce, please re-open!

**Closed by brauner** 2018-06-26 13:57 UTC
Labels: Incomplete
