### ISSUE TITLE
lxc-start sometimes failed when start 200 containers with 40 concurrent lxc-start processes

### ISSUE THREAD

**Issue by tanyifeng** [lxc/lxc#1701] opened 2017-07-14 07:33 UTC
# Required information

 * Distribution: ubuntu
 * Distribution version: ubuntu16.04
 * The output of
   * `lxc-start --version`: 2.0.0
   * `lxc-checkconfig`
```
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Warning: newuidmap is not setuid-root
Warning: newgidmap is not setuid-root
Network namespace: enabled
Multiple /dev/pts instances: enabled
--- Control groups ---
Cgroup: enabled
Cgroup clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, not loaded
Macvlan: enabled, not loaded
Vlan: enabled, not loaded
Bridges: enabled, loaded
Advanced netfilter: enabled, not loaded
CONFIG_NF_NAT_IPV4: enabled, loaded
CONFIG_NF_NAT_IPV6: enabled, not loaded
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, not loaded
FUSE (for use with lxcfs): enabled, not loaded

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities: enabled
```
   * `uname -a`
` Linux ubuntu 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
   * `cat /proc/self/cgroup`
```
11:cpuset:/
10:blkio:/user.slice/user-0.slice/session-2.scope
9:perf_event:/
8:pids:/user.slice/user-0.slice/session-2.scope
7:freezer:/
6:net_cls,net_prio:/
5:devices:/user.slice/user-0.slice/session-2.scope
4:memory:/user.slice/user-0.slice/session-2.scope
3:cpu,cpuacct:/user.slice/user-0.slice/session-2.scope
2:hugetlb:/
1:name=systemd:/user.slice/user-0.slice/session-2.scope
```
   * `cat /proc/1/mounts`

# Issue description

lxc-start sometimes failed when start 200 containers with 40 concurrent lxc-start processes.

# Steps to reproduce

 1. Step one

create 200 containers using ubuntu template, named from 1 to 200.

 2. Step two

I write a simple concurrent program using go language, executing `lxc-start -n number_of_container.` And start the 200 containers with 40 concurrent goroutine. 

3. Step three

Sometimes, some containers actually not started, and their state is STOPPED, lxc.log writed some error message, but is not a failed container's error.

# Information to attach

 - [ ] container state out put

```
NAME STATE   PID   interface IPV4 IPV6 
1    STOPPED -     -         -    -         "1 is failed"
10   RUNNING 9820  -         -    -    
100  RUNNING 12632 -         -    -    
101  RUNNING 12575 -         -    -    
102  RUNNING 12644 -         -    -    
103  RUNNING 12904 -         -    -    
104  RUNNING 12894 -         -    -    
105  RUNNING 12918 -         -    -    
106  RUNNING 13807 -         -    -    
107  RUNNING 13121 -         -    -    
108  RUNNING 13479 -         -    -    
109  RUNNING 13588 -         -    -    
11   RUNNING 9609  -         -    -    
110  RUNNING 13505 -         -    -    
111  RUNNING 13541 -         -    -    
112  RUNNING 13519 -         -    -    
113  RUNNING 13529 -         -    -    
114  RUNNING 13551 -         -    -    
115  RUNNING 13823 -         -    -    
116  RUNNING 13580 -         -    -    
117  RUNNING 13569 -         -    -    
118  RUNNING 13795 -         -    -    
119  RUNNING 14076 -         -    -    
12   RUNNING 9807  -         -    -    
120  RUNNING 14602 -         -    -    
121  RUNNING 14088 -         -    -    
122  RUNNING 14317 -         -    -    
123  RUNNING 14102 -         -    -    
124  RUNNING 13496 -         -    -    
125  RUNNING 14890 -         -    -    
126  RUNNING 15183 -         -    -    
127  RUNNING 14310 -         -    -    
128  RUNNING 14326 -         -    -    
129  RUNNING 15778 -         -    -    
13   RUNNING 9828  -         -    -    
130  RUNNING 14339 -         -    -    
131  RUNNING 15815 -         -    -    
132  RUNNING 14593 -         -    -    
133  RUNNING 14349 -         -    -    
134  RUNNING 16157 -         -    -    
135  RUNNING 15814 -         -    -    
136  RUNNING 16188 -         -    -    
137  RUNNING 16165 -         -    -    
138  RUNNING 16142 -         -    -    
139  RUNNING 17386 -         -    -    
14   RUNNING 9797  -         -    -    
140  RUNNING 17369 -         -    -    
141  RUNNING 17807 -         -    -    
142  RUNNING 16528 -         -    -    
143  RUNNING 16197 -         -    -    
144  RUNNING 16174 -         -    -    
145  RUNNING 16221 -         -    -    
146  RUNNING 16962 -         -    -    
147  RUNNING 17427 -         -    -    
148  RUNNING 17401 -         -    -    
149  RUNNING 17791 -         -    -    
15   RUNNING 9787  -         -    -    
150  RUNNING 17412 -         -    -    
151  RUNNING 17853 -         -    -    
152  RUNNING 18200 -         -    -    
153  RUNNING 17842 -         -    -    
154  RUNNING 18214 -         -    -    
155  RUNNING 18181 -         -    -    
156  RUNNING 18222 -         -    -    
157  RUNNING 18574 -         -    -    
158  RUNNING 18636 -         -    -    
159  RUNNING 18561 -         -    -    
16   RUNNING 9824  -         -    -    
160  RUNNING 18589 -         -    -    
161  RUNNING 18629 -         -    -    
162  RUNNING 18650 -         -    -    
163  RUNNING 18599 -         -    -    
164  RUNNING 19406 -         -    -    
165  RUNNING 18609 -         -    -    
166  RUNNING 18580 -         -    -    
167  RUNNING 19369 -         -    -    
168  RUNNING 18962 -         -    -    
169  RUNNING 19422 -         -    -    
17   RUNNING 9973  -         -    -    
170  STOPPED -     -         -    -       "170 is failed"
171  RUNNING 19613 -         -    -    
172  RUNNING 19597 -         -    -    
173  RUNNING 19718 -         -    -    
174  RUNNING 19669 -         -    -    
175  RUNNING 19629 -         -    -    
176  RUNNING 19646 -         -    -    
177  RUNNING 19682 -         -    -    
178  RUNNING 19706 -         -    -    
179  RUNNING 19658 -         -    -    
18   RUNNING 9933  -         -    -    
180  RUNNING 19673 -         -    -    
181  RUNNING 19690 -         -    -    
182  RUNNING 21369 -         -    -    
183  RUNNING 20918 -         -    -    
184  RUNNING 20953 -         -    -    
185  RUNNING 20966 -         -    -    
186  RUNNING 21914 -         -    -    
187  RUNNING 20567 -         -    -    
188  RUNNING 23590 -         -    -    
189  RUNNING 21985 -         -    -    
19   RUNNING 9832  -         -    -    
190  RUNNING 22532 -         -    -    
191  RUNNING 20931 -         -    -    
192  RUNNING 20978 -         -    -    
193  RUNNING 21009 -         -    -    
194  RUNNING 20993 -         -    -    
195  RUNNING 21021 -         -    -    
196  RUNNING 22508 -         -    -    
197  RUNNING 21948 -         -    -    
198  RUNNING 22546 -         -    -    
199  RUNNING 24631 -         -    -    
2    RUNNING 9592  -         -    -    
20   RUNNING 9883  -         -    -    
200  RUNNING 22486 -         -    -    
21   RUNNING 9885  -         -    -    
22   RUNNING 10007 -         -    -    
23   RUNNING 9816  -         -    -    
24   RUNNING 9967  -         -    -    
25   RUNNING 9862  -         -    -    
26   RUNNING 9982  -         -    -    
27   RUNNING 9955  -         -    -    
28   RUNNING 9783  -         -    -    
29   RUNNING 9793  -         -    -    
3    RUNNING 9846  -         -    -    
30   RUNNING 9799  -         -    -    
31   RUNNING 9977  -         -    -    
32   RUNNING 9997  -         -    -    
33   RUNNING 9947  -         -    -    
34   RUNNING 9985  -         -    -    
35   RUNNING 9928  -         -    -    
36   RUNNING 9921  -         -    -    
37   RUNNING 9907  -         -    -    
38   RUNNING 9871  -         -    -    
39   RUNNING 9944  -         -    -    
4    RUNNING 9586  -         -    -    
40   RUNNING 9855  -         -    -    
41   RUNNING 10057 -         -    -    
42   RUNNING 10062 -         -    -    
43   RUNNING 10067 -         -    -    
44   RUNNING 10081 -         -    -    
45   RUNNING 10083 -         -    -    
46   RUNNING 10124 -         -    -    
47   RUNNING 10126 -         -    -    
48   RUNNING 10146 -         -    -    
49   RUNNING 10240 -         -    -    
5    RUNNING 9602  -         -    -    
50   RUNNING 10367 -         -    -    
51   RUNNING 11195 -         -    -    
52   RUNNING 10402 -         -    -    
53   RUNNING 10860 -         -    -    
54   RUNNING 10372 -         -    -    
55   RUNNING 10627 -         -    -    
56   RUNNING 10850 -         -    -    
57   RUNNING 11626 -         -    -    
58   RUNNING 11060 -         -    -    
59   RUNNING 11797 -         -    -    
6    RUNNING 9605  -         -    -    
60   RUNNING 11185 -         -    -    
61   RUNNING 11158 -         -    -    
62   RUNNING 10965 -         -    -    
63   RUNNING 11210 -         -    -    
64   RUNNING 11491 -         -    -    
65   RUNNING 10971 -         -    -    
66   RUNNING 11149 -         -    -    
67   RUNNING 11176 -         -    -    
68   RUNNING 11199 -         -    -    
69   STOPPED -     -         -    -       "69 is failed"
7    RUNNING 9809  -         -    -    
70   RUNNING 10877 -         -    -    
71   RUNNING 11251 -         -    -    
72   RUNNING 11265 -         -    -    
73   RUNNING 11350 -         -    -    
74   RUNNING 10962 -         -    -    
75   RUNNING 11824 -         -    -    
76   RUNNING 10957 -         -    -    
77   RUNNING 11065 -         -    -    
78   RUNNING 11170 -         -    -    
79   RUNNING 11231 -         -    -    
8    RUNNING 9780  -         -    -    
80   RUNNING 11832 -         -    -    
81   RUNNING 11814 -         -    -    
82   RUNNING 11786 -         -    -    
83   RUNNING 11806 -         -    -    
84   RUNNING 12063 -         -    -    
85   RUNNING 11858 -         -    -    
86   RUNNING 11844 -         -    -    
87   RUNNING 12083 -         -    -    
88   RUNNING 11869 -         -    -    
89   RUNNING 12150 -         -    -    
9    RUNNING 9857  -         -    -    
90   RUNNING 12072 -         -    -    
91   RUNNING 12314 -         -    -    
92   RUNNING 12078 -         -    -    
93   RUNNING 12308 -         -    -    
94   RUNNING 13128 -         -    -    
95   RUNNING 13447 -         -    -    
96   RUNNING 12580 -         -    -    
97   RUNNING 12565 -         -    -    
98   RUNNING 13467 -         -    -    
99   RUNNING 12579 -         -    -
```

 - [ ] container log (The <log> file from running `lxc-start -n <c> -l <log> -o DEBUG`)
```
      lxc-start 2 20170714150150.676 ERROR    lxc_start_ui - tools/lxc_start.c:main:308 - Container is already running.
      lxc-start 70 20170714150151.558 ERROR    lxc_start_ui - tools/lxc_start.c:main:308 - Container is already running.
      lxc-start 171 20170714150154.584 ERROR    lxc_start_ui - tools/lxc_start.c:main:308 - Container is already running.
```
 - [ ] the containers configuration file
```
lxc.arch = x86_64
lxc.utsname = ubuntu
lxc.init_cmd = /sbin/init
lxc.environment = PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
lxc.environment = TERM=xterm
lxc.rootfs = rootfs
lxc.rootfs.options = ro
lxc.rootfs.backend = dir
lxc.mount.entry = /sys/kernel/debug sys/kernel/debug none bind,optional 0 0
lxc.mount.entry = tmpfs tmp tmpfs nosuid,noexec,nodev,mode=1777,size=65536k 0 0
lxc.mount.entry = /sys/kernel/security sys/kernel/security none bind,optional 0 0
lxc.mount.entry = /sys/fs/pstore sys/fs/pstore none bind,optional 0 0
lxc.mount.entry = mqueue dev/mqueue mqueue rw,realtime,create=dir,optional 0 0
lxc.mount.entry = /sys/fs/fuse/connections sys/fs/fuse/connections non bind,optional 0 0
lxc.cgroup.devices.allow = c 254:* rm
lxc.cgroup.devices.allow = c 10:200 rwm
lxc.cgroup.devices.allow = c 10:228 rwm
lxc.cgroup.devices.allow = c 10:232 rwm
lxc.cgroup.devices.deny = a
lxc.cgroup.devices.allow = c *:* m
lxc.cgroup.devices.allow = b *:* m
lxc.cgroup.devices.allow = c 1:3 rwm
lxc.cgroup.devices.allow = c 1:5 rwm
lxc.cgroup.devices.allow = c 1:7 rwm
lxc.cgroup.devices.allow = c 5:* rwm
lxc.cgroup.devices.allow = c 5:1 rwm
lxc.cgroup.devices.allow = c 5:2 rwm
lxc.cgroup.devices.allow = c 1:8 rwm
lxc.cgroup.devices.allow = c 1:9 rwm
lxc.cgroup.devices.allow = c 136:* rwm
lxc.cgroup.devices.allow = c 10:229 rwm
lxc.tty = 4
lxc.pts = 1024
lxc.devttydir = lxc
lxc.rootfs = my_containers_rootfs_path
```

**Comment by tanyifeng** [comment] 2017-07-14 08:00
I set `lxc-start -l DEBUG`, and got this message when a container 1 is failed to start, but error is about container 2.
```
lxc-start 2 20170714161445.485 INFO     lxc_start_ui - tools/lxc_start.c:main:282 - using rcfile /var/lib/lcrd/lcr/2/config
      lxc-start 2 20170714161445.486 INFO     lxc_container - lxccontainer.c:do_lxcapi_start:890 - Attempting to set proc title to [lxc monitor] /var/lib/lcrd/lcr 2
      lxc-start 2 20170714161445.486 INFO     lxc_start - start.c:lxc_check_inherited:245 - Closed inherited fd: 3.
      lxc-start 2 20170714161445.487 INFO     lxc_lsm - lsm/lsm.c:lsm_init:48 - LSM security driver AppArmor
      lxc-start 2 20170714161445.487 DEBUG    lxc_start - start.c:setup_signal_fd:289 - Set SIGCHLD handler with file descriptor: 3.
      lxc-start 2 20170714161445.487 DEBUG    console - console.c:lxc_console_peer_default:446 - process does not have a controlling terminal
      lxc-start 2 20170714161445.487 INFO     lxc_start - start.c:lxc_init:670 - container "2" is initialized
      lxc-start 2 20170714161445.488 DEBUG    lxc_start - start.c:__lxc_start:1566 - Not dropping CAP_SYS_BOOT or watching utmp.
      lxc-start 2 20170714161445.488 INFO     lxc_cgroup - cgroups/cgroup.c:cgroup_init:68 - cgroup driver cgroupfs-ng initing for 2
      lxc-start 2 20170714161445.493 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:filter_and_set_cpus:480 - No isolated cpus detected.
      lxc-start 2 20170714161445.493 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:handle_cpuset_hierarchy:650 - "cgroup.clone_children" was already set to "1".
      lxc-start 2 20170714161445.508 INFO     lxc_start - start.c:lxc_spawn:1402 - Cloned CLONE_NEWNS.
      lxc-start 2 20170714161445.508 INFO     lxc_start - start.c:lxc_spawn:1402 - Cloned CLONE_NEWPID.
      lxc-start 2 20170714161445.508 INFO     lxc_start - start.c:lxc_spawn:1402 - Cloned CLONE_NEWUTS.
      lxc-start 2 20170714161445.508 INFO     lxc_start - start.c:lxc_spawn:1402 - Cloned CLONE_NEWIPC.
      lxc-start 2 20170714161445.508 INFO     lxc_start - start.c:lxc_spawn:1402 - Cloned CLONE_NEWNET.
      lxc-start 2 20170714161445.510 INFO     lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1980 - cgroup has been setup
      lxc-start 2 20170714161445.545 INFO     lxc_start_ui - tools/lxc_start.c:main:282 - using rcfile /var/lib/lcrd/lcr/2/config
      lxc-start 2 20170714161445.591 DEBUG    bdev - bdev/bdev.c:bdev_query:239 - Detected rootfs type "dir"
      lxc-start 2 20170714161445.593 DEBUG    lxc_conf - conf.c:lxc_setup_rootfs:1211 - Mounted rootfs "/var/lib/lcrd/lcr/2/rootfs" onto "/usr/local/lib/lxc/rootfs" with options "ro".
      lxc-start 2 20170714161445.593 INFO     lxc_conf - conf.c:setup_utsname:802 - 'ubuntu' hostname has been setup
      lxc-start 2 20170714161445.593 INFO     lxc_conf - conf.c:mount_autodev:1047 - Mounting container /dev
      lxc-start 2 20170714161445.595 INFO     lxc_conf - conf.c:mount_autodev:1070 - Mounted tmpfs onto /usr/local/lib/lxc/rootfs/dev
      lxc-start 2 20170714161445.595 INFO     lxc_conf - conf.c:mount_autodev:1088 - Mounted container /dev
      lxc-start 2 20170714161445.595 INFO     lxc_conf - conf.c:mount_entry:1732 - failed to mount '/sys/kernel/debug' on '/usr/local/lib/lxc/rootfs/sys/kernel/debug' (optional): No such file or directory
      lxc-start 2 20170714161445.596 DEBUG    lxc_conf - conf.c:mount_entry:1793 - mounted 'tmpfs' on '/usr/local/lib/lxc/rootfs/tmp', type 'tmpfs'
      lxc-start 2 20170714161445.596 INFO     lxc_conf - conf.c:mount_entry:1732 - failed to mount '/sys/kernel/security' on '/usr/local/lib/lxc/rootfs/sys/kernel/security' (optional): No such file or directory
      lxc-start 2 20170714161445.596 INFO     lxc_conf - conf.c:mount_entry:1732 - failed to mount '/sys/fs/pstore' on '/usr/local/lib/lxc/rootfs/sys/fs/pstore' (optional): No such file or directory
      lxc-start 2 20170714161445.599 DEBUG    lxc_conf - conf.c:mount_entry:1793 - mounted 'mqueue' on '/usr/local/lib/lxc/rootfs/dev/mqueue', type 'mqueue'
      lxc-start 2 20170714161445.599 INFO     lxc_conf - conf.c:mount_entry:1732 - failed to mount '/sys/fs/fuse/connections' on '/usr/local/lib/lxc/rootfs/sys/fs/fuse/connections' (optional): No such file or directory
      lxc-start 2 20170714161445.599 INFO     lxc_conf - conf.c:mount_file_entries:2013 - mount points have been setup
      lxc-start 2 20170714161445.599 INFO     lxc_conf - conf.c:lxc_fill_autodev:1125 - populating container /dev
      lxc-start 2 20170714161445.599 DEBUG    lxc_conf - conf.c:lxc_fill_autodev:1162 - created device node "/usr/local/lib/lxc/rootfs/dev/null"
      lxc-start 2 20170714161445.599 DEBUG    lxc_conf - conf.c:lxc_fill_autodev:1162 - created device node "/usr/local/lib/lxc/rootfs/dev/zero"
      lxc-start 2 20170714161445.599 DEBUG    lxc_conf - conf.c:lxc_fill_autodev:1162 - created device node "/usr/local/lib/lxc/rootfs/dev/full"
      lxc-start 2 20170714161445.600 DEBUG    lxc_conf - conf.c:lxc_fill_autodev:1162 - created device node "/usr/local/lib/lxc/rootfs/dev/urandom"
      lxc-start 2 20170714161445.600 DEBUG    lxc_conf - conf.c:lxc_fill_autodev:1162 - created device node "/usr/local/lib/lxc/rootfs/dev/random"
      lxc-start 2 20170714161445.600 DEBUG    lxc_conf - conf.c:lxc_fill_autodev:1162 - created device node "/usr/local/lib/lxc/rootfs/dev/tty"
      lxc-start 2 20170714161445.600 INFO     lxc_conf - conf.c:lxc_fill_autodev:1167 - populated container /dev
      lxc-start 2 20170714161445.600 DEBUG    lxc_conf - conf.c:lxc_setup_ttydir_console:1510 - created directory for console and tty devices at /usr/local/lib/lxc/rootfs/dev/lxc"
      lxc-start 2 20170714161445.600 DEBUG    lxc_conf - conf.c:lxc_setup_ttydir_console:1596 - mounted "/dev/pts/21" onto "/usr/local/lib/lxc/rootfs/dev/lxc/console"
      lxc-start 2 20170714161445.600 DEBUG    lxc_conf - conf.c:lxc_setup_ttydir_console:1616 - console has been setup under "lxc/console" and symlinked to "/usr/local/lib/lxc/rootfs/dev/console"
      lxc-start 2 20170714161445.600 INFO     lxc_utils - utils.c:lxc_mount_proc_if_needed:1809 - mounted /proc in container for security transition
      lxc-start 2 20170714161445.698 DEBUG    lxc_conf - conf.c:setup_rootfs_pivot_root:1025 - pivot_root syscall to '/usr/local/lib/lxc/rootfs' successful
      lxc-start 2 20170714161445.698 DEBUG    lxc_conf - conf.c:setup_pivot_root:1328 - finished pivot root
      lxc-start 2 20170714161445.712 DEBUG    lxc_conf - conf.c:lxc_setup_devpts:1367 - mount new devpts instance with options "newinstance,ptmxmode=0666,mode=0620,gid=5"
      lxc-start 2 20170714161445.712 DEBUG    lxc_conf - conf.c:lxc_setup_devpts:1387 - created dummy "/dev/ptmx" file as bind mount target
      lxc-start 2 20170714161445.720 DEBUG    lxc_conf - conf.c:lxc_setup_devpts:1392 - bind mounted "/dev/pts/ptmx" to "/dev/ptmx"
      lxc-start 2 20170714161445.720 DEBUG    lxc_conf - conf.c:lxc_create_tty:3666 - allocated pty "/dev/pts/0" with master fd 11 and slave fd 14
      lxc-start 2 20170714161445.720 DEBUG    lxc_conf - conf.c:lxc_create_tty:3666 - allocated pty "/dev/pts/1" with master fd 15 and slave fd 16
      lxc-start 2 20170714161445.720 DEBUG    lxc_conf - conf.c:lxc_create_tty:3666 - allocated pty "/dev/pts/2" with master fd 17 and slave fd 18
      lxc-start 2 20170714161445.720 DEBUG    lxc_conf - conf.c:lxc_create_tty:3666 - allocated pty "/dev/pts/3" with master fd 19 and slave fd 20
      lxc-start 2 20170714161445.720 INFO     lxc_conf - conf.c:lxc_create_tty:3686 - finished allocating 4 pts devices
      lxc-start 2 20170714161445.727 DEBUG    lxc_conf - conf.c:lxc_setup_tty:926 - bind mounted "/dev/pts/0" onto "/dev/tty1"
      lxc-start 2 20170714161445.727 DEBUG    lxc_conf - conf.c:lxc_setup_tty:926 - bind mounted "/dev/pts/1" onto "/dev/tty2"
      lxc-start 2 20170714161445.727 DEBUG    lxc_conf - conf.c:lxc_setup_tty:926 - bind mounted "/dev/pts/2" onto "/dev/tty3"
      lxc-start 2 20170714161445.727 DEBUG    lxc_conf - conf.c:lxc_setup_tty:926 - bind mounted "/dev/pts/3" onto "/dev/tty4"
      lxc-start 2 20170714161445.727 INFO     lxc_conf - conf.c:lxc_setup_tty:972 - finished setting up 4 /dev/tty<N> device(s)
      lxc-start 2 20170714161445.727 INFO     lxc_conf - conf.c:setup_personality:1428 - set personality to '0x0'
      lxc-start 2 20170714161445.727 DEBUG    lxc_conf - conf.c:setup_caps:2172 - capabilities have been setup
      lxc-start 2 20170714161445.727 NOTICE   lxc_conf - conf.c:lxc_setup:4240 - '2' is setup.
      lxc-start 2 20170714161445.728 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1975 - cgroup 'devices.allow' set to 'c 254:* rm'
      lxc-start 2 20170714161445.728 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1975 - cgroup 'devices.allow' set to 'c 10:200 rwm'
      lxc-start 2 20170714161445.728 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1975 - cgroup 'devices.allow' set to 'c 10:228 rwm'
      lxc-start 2 20170714161445.728 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1975 - cgroup 'devices.allow' set to 'c 10:232 rwm'
      lxc-start 2 20170714161445.728 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1975 - cgroup 'devices.deny' set to 'a *:* (null)'
      lxc-start 2 20170714161445.728 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1975 - cgroup 'devices.allow' set to 'c *:* m'
      lxc-start 2 20170714161445.728 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1975 - cgroup 'devices.allow' set to 'b *:* m'
      lxc-start 2 20170714161445.728 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1975 - cgroup 'devices.allow' set to 'c 1:3 rwm'
      lxc-start 2 20170714161445.728 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1975 - cgroup 'devices.allow' set to 'c 1:5 rwm'
      lxc-start 2 20170714161445.728 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1975 - cgroup 'devices.allow' set to 'c 1:7 rwm'
      lxc-start 2 20170714161445.728 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1975 - cgroup 'devices.allow' set to 'c 5:* rwm'
      lxc-start 2 20170714161445.728 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1975 - cgroup 'devices.allow' set to 'c 5:1 rwm'
      lxc-start 2 20170714161445.728 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1975 - cgroup 'devices.allow' set to 'c 5:2 rwm'
      lxc-start 2 20170714161445.729 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1975 - cgroup 'devices.allow' set to 'c 1:8 rwm'
      lxc-start 2 20170714161445.729 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1975 - cgroup 'devices.allow' set to 'c 1:9 rwm'
      lxc-start 2 20170714161445.729 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1975 - cgroup 'devices.allow' set to 'c 136:* rwm'
      lxc-start 2 20170714161445.729 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1975 - cgroup 'devices.allow' set to 'c 10:229 rwm'
      lxc-start 2 20170714161445.729 INFO     lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1980 - cgroup has been setup
      lxc-start 2 20170714161445.759 INFO     lxc_start - start.c:do_start:1042 - Unshared CLONE_NEWCGROUP.
      lxc-start 2 20170714161445.759 INFO     lxc_apparmor - lsm/apparmor.c:apparmor_process_label_set:238 - changed apparmor profile to lxc-container-default-cgns
      lxc-start 2 20170714161445.799 NOTICE   lxc_start - start.c:start:1677 - Exec'ing "/sbin/init".
      lxc-start 2 20170714161445.809 NOTICE   lxc_start - start.c:post_start:1688 - Started "/sbin/init" with pid "31836".
      lxc-start 2 20170714161445.809 NOTICE   lxc_start - start.c:signal_handler:338 - Received SIGCHLD from pid 31754 instead of container init 31836.
      lxc-start 2 20170714161445.809 DEBUG    lxc_commands - commands.c:lxc_cmd_rsp_recv:152 - command get_init_pid response data length is 0
      lxc-start 2 20170714161445.809 DEBUG    lxc_commands - commands.c:lxc_cmd_handler:993 - Peer has disconnected for "get_init_pid"
      lxc-start 2 20170714161445.809 DEBUG    lxc_commands - commands.c:lxc_cmd_handler:993 - Peer has disconnected for "get_cgroup"
      lxc-start 2 20170714161445.810 DEBUG    lxc_commands - commands.c:lxc_cmd_rsp_recv:152 - command get_state response data length is 0
      lxc-start 2 20170714161445.810 DEBUG    lxc_commands - commands.c:lxc_cmd_get_state:569 - Container "2" is in "RUNNING" state.
      lxc-start 2 20170714161445.810 DEBUG    lxc_commands - commands.c:lxc_cmd_handler:993 - Peer has disconnected for "get_state"
     ###  lxc-start 2 20170714161445.810 ERROR    lxc_start_ui - tools/lxc_start.c:main:308 - Container is already running.
      lxc-start 2 20170714161934.119 DEBUG    lxc_commands - commands.c:lxc_cmd_handler:993 - Peer has disconnected for "get_cgroup"
      lxc-start 2 20170714161934.119 DEBUG    lxc_commands - commands.c:lxc_cmd_handler:993 - Peer has disconnected for "get_state"
      lxc-start 2 20170714161934.119 DEBUG    lxc_commands - commands.c:lxc_cmd_handler:993 - Peer has disconnected for "get_cgroup"
      lxc-start 2 20170714161934.119 DEBUG    lxc_commands - commands.c:lxc_cmd_handler:993 - Peer has disconnected for "get_state"
      lxc-start 2 20170714161934.119 DEBUG    lxc_commands - commands.c:lxc_cmd_handler:993 - Peer has disconnected for "get_init_pid"
      lxc-start 2 20170714161934.120 DEBUG    lxc_commands - commands.c:lxc_cmd_handler:993 - Peer has disconnected for "get_init_pid"
```

**Comment by brauner** [comment] 2017-07-14 09:36
- I'd need to know what you're go program is exactly doing.
- The log you showed me is from a container that started successfully. I'd need a log for e.g. container `1`.

**Comment by tanyifeng** [comment] 2017-07-14 10:06
sorry, container 1 has no log, maybe my go program is wrong, but it's modified reference to  [docker-stress](https://github.com/crosbymichael/docker-stress)， it should be right, cause the error above will occur when I set larger than 20 or more goroutine. 

This is  my modified lxc-start-stress:


[main.txt](https://github.com/lxc/lxc/files/1148042/main.txt)

**Comment by brauner** [comment] 2018-02-12 10:26
@tanyifeng, can you try and reproduce this with current git master? That would be helpful.

**Comment by tanyifeng** [comment] 2018-02-13 01:15
OK, I'll try it after Chinese New Year for 7 days. Happy New Year.

**Comment by brauner** [comment] 2018-02-13 04:56
On Mon, Feb 12, 2018 at 05:15:06PM -0800, tanyifeng wrote:
> OK, I'll try it after Chinese New Year for 7 days. Happy New Year.

Oh right, I thought about Chinese New Year yesterday but then forgot
about it again. :) Happy New Year to you and @lifeng68 too.

Cool, I'd appreciate trying to reproduce!

**Comment by brauner** [comment] 2018-03-03 14:09
@tanyifeng, gentle ping. Any update on this?

**Comment by tanyifeng** [comment] 2018-03-06 11:12
Sorry, I have been dispatched to another place for emergency work, maybe it will be delayed until April.

**Comment by stgraber** [comment] 2020-03-18 22:54
Closing due to lack of update.

**Closed by stgraber** 2020-03-18 22:54 UTC
Labels: Incomplete
