### ISSUE TITLE
'systemctl reboot' freezes the container and strips off the ipv4 address

### ISSUE THREAD

**Issue by developerinlondon** [lxc/lxc#1018] opened 2016-05-11 10:49 UTC
```
root@vagrant-ubuntu-wily-64:/home/vagrant/vagrant-in-vagrant# lxc-create -n xtest -t download -- --dist ubuntu --release xenial --arch amd64
Setting up the GPG keyring
Downloading the image index
Downloading the rootfs
Downloading the metadata
The image cache is now ready
Unpacking the rootfs

---
You just created an Ubuntu container (release=xenial, arch=amd64, variant=default)

To enable sshd, run: apt-get install openssh-server

For security reason, container images ship without user accounts
and without a root password.

Use lxc-attach or chroot directly into the rootfs to set a root password
or create user accounts.
root@vagrant-ubuntu-wily-64:/home/vagrant/vagrant-in-vagrant# lxc-attach -n xtest
lxc-attach: attach.c: lxc_attach: 710 failed to get the init pid
root@vagrant-ubuntu-wily-64:/home/vagrant/vagrant-in-vagrant# lxc-ls
vagrant-in-vagrant_ubuntu-001_1462788049815_38640    vagrant-in-vagrant_ubuntu-005_1462788049837_15344    
vagrant-in-vagrant_ubuntu-002_1462788049777_60232    vagrant-in-vagrant_ubuntu-15-10_1462883136996_63269  
vagrant-in-vagrant_ubuntu-003_1462788049849_19510    vagrant-in-vagrant_ubuntu-16-04_1462811708371_24690  
vagrant-in-vagrant_ubuntu-004_1462788049830_64465    xtest                                                
root@vagrant-ubuntu-wily-64:/home/vagrant/vagrant-in-vagrant# lxc-
lxc-attach           lxc-checkpoint       lxc-create           lxc-freeze           lxc-snapshot         lxc-top              lxc-wait
lxc-autostart        lxc-clone            lxc-destroy          lxc-info             lxc-start            lxc-unfreeze         
lxc-cgroup           lxc-config           lxc-device           lxc-ls               lxc-start-ephemeral  lxc-unshare          
lxc-checkconfig      lxc-console          lxc-execute          lxc-monitor          lxc-stop             lxc-usernsexec       
root@vagrant-ubuntu-wily-64:/home/vagrant/vagrant-in-vagrant# lxc-attach -n xtest
lxc-attach: attach.c: lxc_attach: 710 failed to get the init pid
root@vagrant-ubuntu-wily-64:/home/vagrant/vagrant-in-vagrant# lxc-start 0n xtest
lxc-start: missing container name, use --name option
root@vagrant-ubuntu-wily-64:/home/vagrant/vagrant-in-vagrant# lxc-start -n xtest
root@vagrant-ubuntu-wily-64:/home/vagrant/vagrant-in-vagrant# lxc-start 0n xtest
lxc-start: missing container name, use --name option
root@vagrant-ubuntu-wily-64:/home/vagrant/vagrant-in-vagrant# lxc-attach -n xtest
root@xtest:/# ls
bin  boot  dev  etc  home  lib  lib64  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
root@xtest:/# exit
exit
root@vagrant-ubuntu-wily-64:/home/vagrant/vagrant-in-vagrant# lxc-ls --fancy
NAME                                                 STATE    IPV4        IPV6  GROUPS  AUTOSTART  
-------------------------------------------------------------------------------------------------
vagrant-in-vagrant_ubuntu-001_1462788049815_38640    RUNNING  10.0.3.236  -     -       NO         
vagrant-in-vagrant_ubuntu-002_1462788049777_60232    RUNNING  10.0.3.211  -     -       NO         
vagrant-in-vagrant_ubuntu-003_1462788049849_19510    STOPPED  -           -     -       NO         
vagrant-in-vagrant_ubuntu-004_1462788049830_64465    STOPPED  -           -     -       NO         
vagrant-in-vagrant_ubuntu-005_1462788049837_15344    STOPPED  -           -     -       NO         
vagrant-in-vagrant_ubuntu-15-10_1462883136996_63269  RUNNING  10.0.3.49   -     -       NO         
vagrant-in-vagrant_ubuntu-16-04_1462811708371_24690  RUNNING  -           -     -       NO         
xtest                                                RUNNING  10.0.3.242  -     -       NO         
root@vagrant-ubuntu-wily-64:/home/vagrant/vagrant-in-vagrant# lxc-attach -n xtest
root@xtest:/# systemctl reboot
Failed to connect to bus: No such file or directory
Failed to connect to bus: No such file or directory
root@xtest:/# root@vagrant-ubuntu-wily-64:/home/vagrant/vagrant-in-vagrant# 
root@vagrant-ubuntu-wily-64:/home/vagrant/vagrant-in-vagrant# 
root@vagrant-ubuntu-wily-64:/home/vagrant/vagrant-in-vagrant# lxc-ls --fancy
NAME                                                 STATE    IPV4        IPV6  GROUPS  AUTOSTART  
-------------------------------------------------------------------------------------------------
vagrant-in-vagrant_ubuntu-001_1462788049815_38640    RUNNING  10.0.3.236  -     -       NO         
vagrant-in-vagrant_ubuntu-002_1462788049777_60232    RUNNING  10.0.3.211  -     -       NO         
vagrant-in-vagrant_ubuntu-003_1462788049849_19510    STOPPED  -           -     -       NO         
vagrant-in-vagrant_ubuntu-004_1462788049830_64465    STOPPED  -           -     -       NO         
vagrant-in-vagrant_ubuntu-005_1462788049837_15344    STOPPED  -           -     -       NO         
vagrant-in-vagrant_ubuntu-15-10_1462883136996_63269  RUNNING  10.0.3.49   -     -       NO         
vagrant-in-vagrant_ubuntu-16-04_1462811708371_24690  RUNNING  -           -     -       NO         
xtest                                                RUNNING  -           -     -       NO         
root@vagrant-ubuntu-wily-64:/home/vagrant/vagrant-in-vagrant#    
```

as you can see above. the xtest container lost its ipv4 after running 'systemctl reboot'

**Comment by brauner** [comment] 2017-04-25 12:40
Did the reboot even work correctly? It seems that the `sytemctl reboot` command wasn't able to run successfully.

**Comment by brauner** [comment] 2018-02-09 10:17
There hasn't been a response to the issue in quite a while so closing. It looks like systemd did not restart correctly since it can't talk to the system bus. That's usually a good sign that systemd is very unhappy. If this issue is still reproducible with current master, please re-open.

**Closed by brauner** 2018-02-09 10:17 UTC
