### ISSUE TITLE
LXC: Failed to pass wlan0 interface physically to container

### ISSUE THREAD

**Issue by thusharams** [lxc/lxc#1744] opened 2017-08-15 13:34 UTC
I am trying to move `wlan0` interface from host to container with the below configuration,

    lxc.network.type = phys
    lxc.network.link = wlan0
    lxc.network.hwaddr = ab:cd:ef:gh:ij
    lxc.network.flags = up

Which works perfectly with my external TP-Link wifi dongle and I can see `wlan0` interface available inside the container by running `ifconfig`

But I do also have an integrated ALPS wifi chip for which the same container configuration won't work and fails with the below error.

    lxc-start 20170704134254.641 ERROR    lxc_conf - conf.c:lxc_assign_network:3102 - failed to move 'wlan0' to the container : Operation not permitted
          lxc-start 20170704134254.641 ERROR    lxc_start - start.c:lxc_spawn:1199 - Failed to create the configured network.
          lxc-start 20170704134254.641 INFO     lxc_conf - conf.c:lxc_delete_network:2926 - Interface "eth0" with index 6 already deleted or existing in different network namespace.
          lxc-start 20170704134254.710 INFO     lxc_conf - conf.c:lxc_delete_network:2961 - Removed interface "vethQVT9W2" from host.
          lxc-start 20170704134254.711 ERROR    lxc_start - start.c:__lxc_start:1338 - Failed to spawn container "my-cont".
          lxc-start 20170704134254.779 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - command get_cgroup failed to receive response
          lxc-start 20170704134259.784 ERROR    lxc_start_ui - lxc_start.c:main:360 - The container failed to start.
          lxc-start 20170704134259.784 ERROR    lxc_start_ui - lxc_start.c:main:362 - To get more details, run the container in foreground mode.
          lxc-start 20170704134259.784 ERROR    lxc_start_ui - lxc_start.c:main:364 - Additional information can be obtained by setting the --logfile and --logpriority options.

I have also found a [**thread**][1] where it says till `sysfs` virtualization is not finalized the kernel will have this limitation.

If that's the case, how did it worked for my external wifi dongle? 

Or is it something else which I'm missing?

  [1]: https://lists.linuxcontainers.org/pipermail/lxc-devel/2009-June/000197.html

**Comment by thusharams** [comment] 2017-09-11 15:14
Hello, Any updates for this?

**Comment by brauner** [comment] 2017-09-11 15:17
Can you please show me the container's config file. Also, please try to reproduce with current liblxc 2.1.

**Comment by thusharams** [comment] 2017-09-11 15:41
@brauner : Please find the container configuration pasted below,

```
# Host name
lxc.utsname = my-lxc

# root file system
lxc.rootfs = /my-cont/

# Setup apparmor profile
#lxc.aa_profile = lxc-cont//&:lxc-cont-namespace://unconfined

# Setup tty's for container
lxc.tty = 1
lxc.pts = 1024

# Setup eth0 for container 
lxc.network.type = veth
lxc.network.name = eth0
lxc.network.link = br0
lxc.network.ipv4.address = xxx.xx.x.x/24
lxc.network.flags = up

# Allow UART interfaces to container
lxc.cgroup.devices.allow = c 204:* rwm 
lxc.hook.start = /usr/local/bin/serialdevice

# Move wlan0 to container
lxc.network.type = phys
lxc.network.link = wlan0
lxc.network.flags = up
lxc.network.hwaddr = xx:xx:xx:xx:xx:xx

```

It's not straight forward for me to update the `liblxc` to latest version but will try to do that.
Even if the problem persists on the latest version, I have to fix this in the current lxc version which I am using(2.0.6). It will be great if we can identify the issue in this particular version! 

Thanks in advance!

**Comment by Blub** [comment] 2017-09-14 07:04
Since one works and the other doesn't, and the error you get is 'operation not permitted', I wonder if maybe this one just doesn't allow you to set the MAC address?

**Comment by thusharams** [comment] 2017-09-14 11:46
@brauner : By any chance did you get some time to have a look at my configuration :) Did you found anything nasty in my configuration?

**Comment by thusharams** [comment] 2017-09-14 11:49
@Blub : Sorry, I didn't refreshed this page and missed out your comment. Ok but how can I make sure that it's throwing error for setting the MAC address? Because from the container logs all I got is "operation not permitted".

**Comment by thusharams** [comment] 2017-09-14 12:08
@Blub @brauner : It's pretty strange, I ran the above configuration with strace that is,
`strace -s 250 -f -o log-file-path lxc-start -n my-cont -f my-cont.conf -d`. With this I can see wlan0 interface inside the container. :/

**Comment by thusharams** [comment] 2017-09-14 13:18
@Blub @brauner : Also,
`lxc-device -n my-cont -- add wlan0`
```
command failed: Operation not supported (-95)
lxc-device: lxc_device.c: main: 166 Failed to add wlan0 to my-cont.
```

using `lxc-device` says the "Operation is not supported". So, Not supported by the `lxc` or the Wifi driver which I am using?

**Comment by brauner** [comment] 2017-09-14 21:13
`ENOTSUP` comes directly from the kernel. It means that you have permissions to perform the operation but that this is not something that is implemented. For example, trying to delete the loopback interface in a network namespace will give you `ENOTSUP`.

**Comment by thusharams** [comment] 2017-09-18 11:29
@brauner : Aah ok, Thanks for the information. Is there any plans to support this in future from the LXC community? Or is there any patche available for the same which I can try myself?

**Comment by riddhiterminator** [comment] 2019-02-25 12:12
@brauner .
I am trying to perform same thing, passing wlan0 physically to container. 
I am also getting same error. "Operation not supported". I am using LXC 2.0.

Since this is very older thread, just wanted to know,
1) Is that now supported in kernel 4.9 onward or still not implemented ?
2) If not implemented then passing wifi interface physically to container is not possible (correct if I am wrong). In this case, is there any alternative to do so ?

**Comment by d00428514** [comment] 2019-04-04 02:09
@thusharams , @brauner .
I also meet the issue. I can't make sure if the different wifi dongle make the different results.
Can you provide your opinions?

**Comment by rkkoszewski** [comment] 2019-06-19 16:07
Any progress with this issue?

I'm getting this exceptions when trying to add the Wifi devices to an LXC container: 

USB Wifi Dongle:
```
lxc-device -n 150 -- add wlx00805a540c2a
lxc-device: 150: tools/lxc_device.c: main: 172 Failed to add wlx00805a540c2a to 150
```

PCI Wifi Device (Intel Wireless)
```
lxc-device -n 150 -- add wlp4s0
lxc-device: 150: tools/lxc_device.c: main: 172 Failed to add wlp4s0 to 150
```

The exception description seems utterly useless and doesn't seem to explain anything. Anybody has made any kind of progress with this? Anybody knows what exactly is failing here? Are there any hopes to get full control (AP/Cli) of a Wifi device from inside an LXC container?

**Comment by riddhiterminator** [comment] 2019-06-20 07:14
In my case, there were two problems.
1) WiFi driver was not aware of namespace. So I added "WIPHY_FLAG_NETNS_OK" flag in driver (in struct wiphy *wiphy) . so that it can allow changing of network space.
2) In my host file system, "iw" utility was not present, which is used by lxc source (via exec() calls). So I copied that too.

In both the above case it will give "operation not permitted" error.

**Comment by hallyn** [comment] 2019-07-18 13:58
Thanks for the update.  I will close this issue as neither is really an lxc issue.  Actually, if you want to say that lxc should give a more informative error when iw is not found, please re-open, that seems valid.  Or better yet, if you want to submit a patch for it that would be great :)

It would be worth working with kernel community to fix the wifi driver there.  (I haven't looked, but simply *marking* the drive as ns aware may or may not make it so :)

**Closed by hallyn** 2019-07-18 13:58 UTC

**Comment by rkkoszewski** [comment] 2019-07-18 16:27
Just for the sake of completeness (In case somebody finds this thread with a similar issue). I finally managed to also add the WiFi device via phy to the container.

In my case I didn't have "iw" installed. Once installed the WiFi device was able to appear in the container. One last thing preventing me from using the WiFi inside the container was that is was soft blocked. You can check the soft lock status and unlock it with "rfkill". Once unlocked everything seems working fine.

One issue that I did notice is that when you rename the WiFi device inside the container, when the container is stopped and the WiFi device is returned to the host, the WiFi device name is changed to the one that was used inside the container.
