### ISSUE TITLE
Daemontools installation throws SIGHUP

### ISSUE THREAD

**Issue by cesys** [lxc/lxc#2127] opened 2018-02-02 23:11 UTC
# Issue description

Daemontools installation throws SIGHUP

# Steps to reproduce

When I run daemontools installation script at:

https://cr.yp.to/daemontools/install.html

under lxc-execute, the container exits with the following error:
"failed to start container .working"
because of SIGHUP.

**Comment by hallyn** [comment] 2018-02-02 23:14
Thanks, I'll send a patch to ignore sighup.

@brauner can you think of any reason why we'd need sighup to kill init?

**Comment by hallyn** [comment] 2018-02-03 03:44
Unfortunately, when we do that, if the caller of lxc_execute goes away, then lxc-execute and the init don't go away.  As it is now, if I

ssh host1  lxc-execute -n x1 -- /bin/bash

and then type ~. to close the ssh session, when I log back in the container is exited.

**Comment by hallyn** [comment] 2018-02-03 03:55
Yeah this kinda sucks but I don't have any good ideas, since we can't tell the signal sender in userspace.  I'll leave it open for a bit to see whether someone else does have an idea, but I'm afraid we'll have to close it as a CANTFIX.

**Comment by tych0** [comment] 2018-02-03 15:57
What if we have the monitor listen for sighup and send sigkill to the init? That way init can ignore sighup, but the container still dies when we want it to.

**Comment by tych0** [comment] 2018-02-05 10:17
So I just started looking into this... and it seems like lxc init should already handle this. When I add some printfs it works, but when I take them out it doesn't. Seems like gcc just isn't generating the code https://github.com/lxc/lxc/blob/master/src/lxc/lxc_init.c#L419 there, but it's not obvious to me why. I'm still looking.

**Comment by brauner** [comment] 2018-02-05 11:35
On Feb 5, 2018 11:17, "Tycho Andersen" <notifications@github.com> wrote:

So I just started looking into this... and it seems like lxc init should
already handle this. When I add some printfs it works, but when I take them
out it doesn't. Seems like gcc just isn't generating the code
https://github.com/lxc/lxc/blob/master/src/lxc/lxc_init.c#L419 there, but
it's not obvious to me why. I'm still looking.


Can you verify this by compiling with -O0? If that's the case it would be
interesting to see whether this can be reproduced when compiling with clang.

**Comment by tych0** [comment] 2018-02-05 13:18
I'm sorry, it was actually a race condition in my test code and then a bad reading of objdump -d. I think liblxc was doing what was advertised. I'll send a patch shortly.

**Comment by hallyn** [comment] 2018-02-05 15:00
Excellent, thanks.

**Closed by hallyn** 2018-02-05 15:00 UTC
