### ISSUE TITLE
status of lxc-checkpoint

### ISSUE THREAD

**Issue by devonblzx** [lxc/lxc#459] opened 2015-03-03 22:54 UTC
Is lxc-checkpoint supposed to be functioning at this point in time?

All I receive is a failed message with no real error message.  I have tried using criu 1.3.1 (fc21) and 1.4.1 (fc22 beta), both fail.  tty is 0 and console access is denied in the config.

This is the only relative information:
# lxc-checkpoint -n ct -D /var/lib/lxc/chkpnt/ -v -l DEBUG -o checkpoint.log

Checkpointing ct failed.
# cat checkpoint.log

 lxc-checkpoint 1425423047.906 WARN     lxc_confile - confile.c:config_pivotdir:1782 - lxc.pivotdir is ignored.  It will soon become an error.
 lxc-checkpoint 1425423047.907 WARN     lxc_log - log.c:lxc_log_init:316 - lxc_log_init called with log already initialized
 lxc-checkpoint 1425423047.910 DEBUG    lxc_commands - commands.c:lxc_cmd_get_state:574 - 'ct' is in 'RUNNING' state

**Comment by tuapuikia** [comment] 2015-05-15 09:17
I get the same error too.

sudo lxc-checkpoint -n devbox -D /tmp/checkpoint -v -l DEBUG -o debug
Checkpointing devbox failed.


cat debug 
 lxc-checkpoint 1431681291.855 WARN     lxc_confile - confile.c:config_pivotdir:1782 - lxc.pivotdir is ignored.  It will soon become an error.
 lxc-checkpoint 1431681291.863 DEBUG    lxc_commands - commands.c:lxc_cmd_get_state:574 - 'devbox' is in 'RUNNING' state

**Comment by devonblzx** [comment] 2015-05-16 01:27
I tried on Ubuntu and Fedora and had the same thing.  Concerns me a bit that this hasn't gotten even a simple reply yet.  The feature appears to be implemented but still unsure of the real status of it.  Does it work for anyone?

**Comment by stgraber** [comment] 2015-05-16 01:40
@tych0

**Comment by tuapuikia** [comment] 2015-05-18 07:17
OK, I found out what is the root cause of why cr_dump is failed. CRIU is conflict with binfmt, all you can do is sudo stop binfmt-support.

I using latest git version of CRIU and dump log give me the hint why it fail. :)

tested with
lxc - 1.1.2+master
criu - Version: 1.5
GitID: v1.5-227-gd8ee1b7

**Comment by tych0** [comment] 2015-05-19 12:39
Hi,

Apologies for the delay.

Yes, systemd in vivid makes use of a few filesystems (autofs for binfmt support and hugetlbfs and one other one that I can't remember right now). Trunk LXC has some of these exempted, but I think we'll still need to teach CRIU about some of them (systemd's use of autofs in particular is perplexing and I haven't come up with a nice way of dealing with it).

Anyway, for the initial reporter, there is a more detailed criu log file in `/var/lib/lxc/chkpnt/dump.log` (or whatever is provided by the `-D` argument). If you can paste that we can see which particular problem you're running into :)

**Comment by BecauseofLxcCheckpoint** [comment] 2015-12-22 06:16
@tych0 ,hi:
I have read your article named "Doom migration at ODS 2014", the URL is https://github.com/tych0/presentations/blob/master/ods2014.md . 
You said the way of LXC live-migration is very dumb. Can you tell me a better way to live-migrate a lxc container using LXC?

**Comment by tych0** [comment] 2015-12-23 15:03
On Mon, Dec 21, 2015 at 10:16:50PM -0800, BecauseofLxcCheckpoint wrote:
> @tych0 ,hi:
> I have read your article named "Doom migration at ODS 2014", the URL is https://github.com/tych0/presentations/blob/master/ods2014.md . 
> You said the way of LXC live-migration is very dumb. Can you tell me a better way to live-migrate a lxc container using LXC?

Sure, one better way would be to have the container's rootfs on NFS,
so you don't have to rsync it according to that script. You could also
use LXD w/ ZFS, as that will use `zfs send` to send the filesystem,
which should be much faster than rsync.

I'm also currently working on integrating p.haul into LXD, which
should hopefully make things even faster.

**Comment by BecauseofLxcCheckpoint** [comment] 2015-12-24 02:10
@tych0 ，I am so happy and excited to see your reply, : )
Thanks for your advice, but I notice that,  although using 'zfs send' can make sending filesystem and *.img files faster, in the meanwhile the the container  is in stop state, also the services in the container are stopped. Maybe the size of container is more bigger, the sending time is more longer, and the services in container are stopped for a longer time, is this a real live migration?

**Comment by tych0** [comment] 2016-01-06 14:07
On Wed, Dec 23, 2015 at 06:10:49PM -0800, BecauseofLxcCheckpoint wrote:
> @tych0 ，I am so happy and excited to see your reply, : )
> Thanks for your advice, but I notice that,  although using 'zfs send' can make sending filesystem and *.img files faster, in the meanwhile the the container  is in stop state, also the services in the container are stopped. Maybe the size of container is more bigger, the sending time is more longer, and the services in container are stopped for a longer time, is this a real live migration? 

The end goal is to coordinate p.haul with LXD, so that we can do
incremental transfers of both memory and filesystem snapshots until we
do the final migration to minimized the stop time.

**Comment by ramy150** [comment] 2017-02-13 18:03
@tych0 any news about the coordination of LXD with p.haul project ??

**Comment by tych0** [comment] 2017-02-13 18:22
The latest news is that there's a p.haul implementation in golang, but we have no plans to integrate it into LXD at this time, because we have no paying customers for live migration. Once we have paying customers, we'd do this work.

**Comment by brauner** [comment] 2017-04-25 09:30
`p.haul` integration into LXD should and is tracked in the LXD repo itself. Closing this as we are tracking this in LXD. Feel free to ping me have you want this issue to be kept open!

**Closed by brauner** 2017-04-25 09:30 UTC
