### ISSUE TITLE
[FWIW] cpuset.cpus not picked up by nginx

### ISSUE THREAD

**Issue by markc** [lxc/lxc#474] opened 2015-03-20 13:19 UTC
When using cpuset.cpus to limit the number of cpus available to a container and then using nginx with a config option of "worker_processes auto;" (which normally autodetects the number of cpu processors available to the system and forks that may instances of nginx) then whatever nginx uses to detect the number of cpus available does not pick up the container cpuset.cpus setting.

**Comment by dikei** [comment] 2015-04-10 21:23
Do you have lxcfs running? AFAIK, if you don't have lxcfs, then processes inside container will only see the resources of the host machine, not the resources limitted to the container.

**Comment by celsius** [comment] 2016-08-29 19:48
Sorry to dig up this old issue, but as it is still open ... (feel free to tell me to open a new issue)

I'm currently facing the same (or a very similar) issue with nginx not picking up the right number of CPUs in a container. Only difference is that I'm on LXD 2.0 so I used the "lxc config set my-container limits.cpu N" command instead of editing the config file with the cpuset.cpus setting. Note that a `cat /proc/cpuinfo` correctly shows only N cpus.

Now, according to [this other old issue](https://github.com/nginxinc/docker-nginx/issues/31#issuecomment-128049321) in a different project, this is a limitation of how nginx detects the number of available CPUs (using sysconf(_SC_NPROCESSORS_ONLN)) which supposedly doesn't take into account the limitations set by cgroups.

Does that explanation make sense to you? If that is the case, is this something that should be reported to the nginx bug tracker or maybe someplace else? Thanks.

**Comment by stgraber** [comment] 2016-08-30 17:07
Right, there are 2-3 ways to know how many CPUs you have. Currently lxcfs only patches /proc/cpuinfo. Getting the CPU count through a syscall will always return the "wrong" (as in host) value and short of patching the kernel, there's nothing we can do about this.

You can also get the CPU count by reading /sys/class/cpu, for that one, we have a lxcfs issue to consider masking stuff in sysfs, but it'll be very difficult and may impact performance significantly.

https://github.com/lxc/lxcfs/issues/88


At the end of the day, the problem is that the kernel doesn't want to return cgroup limits when asked about hardware availability. A bunch of us think that this is wrong and causes a variety of problems, but we've had no success getting the kernel changed...

That's why we started lxcfs as a way to workaround a bunch of those problems in user space but it won't ever be as good as an in-kernel solution.

Closing this issue in favor of the aforementioned lxcfs one.

**Closed by stgraber** 2016-08-30 17:07 UTC

**Comment by IT-huang** [comment] 2018-01-03 12:49
I wonder if one container have two cores(cpuset=0-1),however the host have 20 cores，Them the nginx container will start 20worker_process(because sysconf get host core number)  in two cores（cpu affinity 0-1），so do you know the influence to nginx at such condition? And how to test that？

**Comment by brauner** [comment] 2018-01-03 12:54
That's not something lxc or lxcfs can fix. Either `nginx` needs to be taught to look at the cgroup values for the cpuset controller or at least `/proc/cpuinfo` or `sysconf()` needs to be partially virtualized at the syscall and or libc level.
