### ISSUE TITLE
alpine LXD container fills /var/log/messages with getty errors

### ISSUE THREAD

**Issue by melato** [lxc/lxc#1096] opened 2016-07-23 15:54 UTC
In a fresh LXD Alpine 3.4 container, I see the following 8 messages repeat once per second in /var/log/messages:
daemon.info init: process '/sbin/getty 38400 tty1' (pid 485) exited. Scheduling for restart.
daemon.info init: process '/sbin/getty 38400 tty2' (pid 486) exited. Scheduling for restart.
daemon.info init: process '/sbin/getty 38400 tty3' (pid 487) exited. Scheduling for restart.
daemon.info init: process '/sbin/getty 38400 tty4' (pid 488) exited. Scheduling for restart.
daemon.info init: can't open /dev/tty1: No such file or directory
daemon.info init: can't open /dev/tty2: No such file or directory
daemon.info init: can't open /dev/tty3: No such file or directory
daemon.info init: can't open /dev/tty4: No such file or directory

Steps to Reproduce:
On an Ubuntu 16.04 host:
```
sudo lxc launch images:alpine/3.4/amd64 alpine34
sudo lxc exec alpine34 sh
# tail -f /var/log/messages

```
Result:  /var/log/messages grows at a rate of 68 MB per day.
Expected Result:  /var/log/messages should not be growing endlessly if I did nothing to cause a problem.

/etc/inittab is modified by the function setup_inittab in the script https://github.com/lxc/lxc/blob/master/templates/lxc-alpine.in

```
setup_inittab() {
	# Remove unwanted ttys.
	sed -i '/^tty[5-9]\:\:.*$/d' etc/inittab

	cat <<-EOF >> etc/inittab
		# Main LXC console console
		::respawn:/sbin/getty 38400 console
	EOF
}
```
The code is from 2016-07-22, commit 5429ec248a1090edde6285e4bc729641f6f79b57

Why not remove all ttys, or comment the first 4?
I also don't see the use for the LXC console with LXD, but it does not cause a problem (other than an extra process).  Perhaps it's useful with lxc-console, but LXD uses lxc exec

**Comment by brauner** [comment] 2016-07-23 16:23
Sorry, how does https://github.com/lxc/lxc/commit/5429ec248a1090edde6285e4bc729641f6f79b57 relate to this problem? Did you reference the wrong commit?

**Comment by stgraber** [comment] 2016-07-23 16:31
So the problem is that LXC defaults to providing 4 ttys, LXD on the other hand doesn't provide any. As the rootfs is used by both LXC and LXD, you get in this situation.

All the systemd based distros don't run into that problem as they read the number of ttys from an environment variable passed to their PID 1. The upstart based distros will try to spawn a getty, fail and move on, same for the sysvinit based ones, so that leaves whatever the alpine init system is.

Maybe the template could tweak the init system configuration somehow to only attempt to run getty if the tty device actually exists?

**Comment by stgraber** [comment] 2016-07-23 16:32
Alternatively, there is a very hackish way for me to override random files in the LXD image, so I could override inittab, but then any change done on the alpine side would be lost, so not ideal.

**Comment by melato** [comment] 2016-07-23 17:01
Shouldn't there be some image template scripts that are run only when LXD launches an image?
One of these scripts could comment out the ttys in /etc/inittab.

Should the alpine gyus have a say on how to fix this?  I've already posted it on their forum.  I could also enter it as a bug.

**Comment by stgraber** [comment] 2016-07-23 19:46
You could certainly suggest that they only attempt to spawn getty when the target tty exists, that seems like a good idea no matter the actual environment.

**Comment by brauner** [comment] 2016-09-01 16:00
Closing as not our bug for now.

**Closed by brauner** 2016-09-01 16:00 UTC

**Comment by barl0g** [comment] 2018-03-21 19:48
Try this
```
for i in {1..4}; do
  systemctl mask getty@tty${i}.service
done

```

**Comment by Cerberooo** [comment] 2018-07-05 10:21
@barl0g This isn't working for alpine linux, because there is no systemctl.

@melato Any news?

**Comment by melato** [comment] 2018-07-05 10:35
@Cerberooo I have been editing /etc/inittab, by commenting out all the /sbin/getty lines.  Only the tty* ones cause a problem, but lately I also comment the console, since I don't see any use for it.

Here's the script that I use:
```
#!/bin/sh

# this prevents lots of tty messages to be logged to syslog
sed -i 's/^tty/# tty/g' /etc/inittab

# the console tty doesn't hurt, but I see no use of it either.
sed -i 's-^::respawn:/sbin/getty-# ::respawn:/sbin/getty-g' /etc/inittab

rm /var/log/messages
```
