### ISSUE TITLE
regression: lxc-start works, systemctl start lxc@.service doesn't work

### ISSUE THREAD

**Issue by Dushistov** [lxc/lxc#3364] opened 2020-04-08 19:35 UTC
# Required information

 * Distribution: Arch Linux
 * The output of
   * `lxc-start --version`
```
3.0.3
```
   * `lxc-checkconfig`
```
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Warning: newuidmap is not setuid-root
Warning: newgidmap is not setuid-root
Network namespace: enabled

--- Control groups ---
Cgroups: enabled

Cgroup v1 mount points: 
/sys/fs/cgroup/systemd
/sys/fs/cgroup/pids
/sys/fs/cgroup/rdma
/sys/fs/cgroup/devices
/sys/fs/cgroup/net_cls,net_prio
/sys/fs/cgroup/memory
/sys/fs/cgroup/cpu,cpuacct
/sys/fs/cgroup/freezer
/sys/fs/cgroup/blkio
/sys/fs/cgroup/perf_event
/sys/fs/cgroup/hugetlb
/sys/fs/cgroup/cpuset

Cgroup v2 mount points: 
/sys/fs/cgroup/unified

Cgroup v1 clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, loaded
Macvlan: enabled, not loaded
Vlan: enabled, loaded
Bridges: enabled, loaded
Advanced netfilter: enabled, not loaded
CONFIG_NF_NAT_IPV4: missing
CONFIG_NF_NAT_IPV6: missing
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, not loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
FUSE (for use with lxcfs): enabled, loaded

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities: 

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/local/lxc/bin/lxc-checkconfig
```

   * `uname -a`
Linux 15inch 5.4.30-1-lts #1 SMP Thu, 02 Apr 2020 14:39:46 +0000 x86_64 GNU/Linux
   * `cat /proc/self/cgroup`
```
12:cpuset:/
11:hugetlb:/
10:perf_event:/
9:blkio:/user.slice
8:freezer:/
7:cpu,cpuacct:/user.slice
6:memory:/user.slice/user-1000.slice/session-2.scope
5:net_cls,net_prio:/
4:devices:/user.slice
3:rdma:/
2:pids:/user.slice/user-1000.slice/session-2.scope
1:name=systemd:/user.slice/user-1000.slice/session-2.scope
0::/user.slice/user-1000.slice/session-2.scope
```
   * `cat /proc/1/mounts`
```
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
sys /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
dev /dev devtmpfs rw,nosuid,relatime,size=32847356k,nr_inodes=8211839,mode=755 0 0
run /run tmpfs rw,nosuid,nodev,relatime,mode=755 0 0
efivarfs /sys/firmware/efi/efivars efivarfs rw,nosuid,nodev,noexec,relatime 0 0
/dev/sda2 / ext4 rw,relatime 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
cgroup2 /sys/fs/cgroup/unified cgroup2 rw,nosuid,nodev,noexec,relatime,nsdelegate 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
none /sys/fs/bpf bpf rw,nosuid,nodev,noexec,relatime,mode=700 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/rdma cgroup rw,nosuid,nodev,noexec,relatime,rdma 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=29,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=30514 0 0
debugfs /sys/kernel/debug debugfs rw,nosuid,nodev,noexec,relatime 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime,pagesize=2M 0 0
mqueue /dev/mqueue mqueue rw,nosuid,nodev,noexec,relatime 0 0
tracefs /sys/kernel/tracing tracefs rw,nosuid,nodev,noexec,relatime 0 0
binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc rw,nosuid,nodev,noexec,relatime 0 0
configfs /sys/kernel/config configfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /tmp tmpfs rw,nosuid,nodev 0 0
/dev/sdf2 /home/evgeniy/bigdisk1 ext4 rw,relatime,data=ordered 0 0
/dev/nvme0n1 /samsung_ssd_970pro ext4 rw,relatime,data=ordered 0 0
/dev/sdc /var ext4 rw,relatime,data=ordered 0 0
/dev/sda1 /boot vfat rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,utf8,errors=remount-ro 0 0
/dev/mapper/Main-lvolhome /home/ext ext4 rw,relatime,data=ordered 0 0
tmpfs /run/user/1000 tmpfs rw,nosuid,nodev,relatime,size=6577784k,mode=700,uid=1000,gid=1000 0 0
gvfsd-fuse /run/user/1000/gvfs fuse.gvfsd-fuse rw,nosuid,nodev,relatime,user_id=1000,group_id=1000 0 0
fusectl /sys/fs/fuse/connections fusectl rw,nosuid,nodev,noexec,relatime 0 0
```
# Issue description

A brief description of what failed or what could be improved.

I can run container just fine with command:
```
sudo lxc-start -F -n mycontainer
```
but 
```
sudo systemctl start lxc@mycontainer
```

hangup (lxc-3.0.4), start and immediately failed (lxc-4.0.1).

But lxc-3.0.3 works just fine, it can starts container via both commands.

# Steps to reproduce
```
sudo systemctl start lxc@mycontainer
```
 
# Information to attach

I run git bisect between 3.0.3 and 3.0.4 and failure commit: 
1e04bb71da3ed829761ae8c729c3d021a6a709df

cc @brauner

**Comment by brauner** [comment] 2020-04-13 12:42
Hm, that works for me here
```
● lxc@b1.service - LXC Container: b1
     Loaded: loaded (/lib/systemd/system/lxc@.service; disabled; vendor preset: enabled)
     Active: active (running) since Mon 2020-04-13 14:41:26 CEST; 3s ago
       Docs: man:lxc-start
             man:lxc
   Main PID: 61125 (lxc-start)
      Tasks: 1 (limit: 18807)
     Memory: 1.8M
     CGroup: /system.slice/system-lxc.slice/lxc@b1.service
             ‣ 61125 /usr/bin/lxc-start -F -n b1
```

**Comment by Dushistov** [comment] 2020-04-15 20:42
@brauner 

I tried ubuntu 19.10 instead of arch linux. It has lxc 3.0.4, and it works fine with same container.
May be it is somehow related to systemd, there are different versions of systemd on arch linux (245.4-2) and ubuntu (242-7).

What I noticed, when I run systemctl **start** container,
I see:
```
root       94126  0.0  0.0  19200  6232 pts/6    S+   23:36   0:00 systemctl start lxc@container
root       94130  0.5  0.0  10008  3552 ?        Ss   23:36   0:00 [lxc monitor] /usr/local/lxc/var/lib/lxc container
root       94142  0.0  0.0   9928  5148 ?        Ss   23:36   0:00 /usr/local/lxc/bin/lxc-stop -n container
```

have no idea why it run `lxc-stop` where I run `start`, but if I kill `lxc-stop`, it looks like this:
```
(gdb) bt
#0  0x00007f8be22ba970 in recv () from /usr/lib/libpthread.so.0
#1  0x00007f8be258f752 in lxc_recv_nointr (sockfd=sockfd@entry=3, buf=buf@entry=0x7ffe9f144200, len=len@entry=264, flags=flags@entry=0) at file_utils.c:138
#2  0x00007f8be257564d in lxc_cmd_sock_rcv_state (state_client_fd=3, timeout=timeout@entry=60) at commands_utils.c:70
#3  0x00007f8be2597209 in do_lxcapi_shutdown (timeout=60, c=0x557ba9b97210) at lxccontainer.c:2089
#4  lxcapi_shutdown (c=0x557ba9b97210, a1=60) at lxccontainer.c:2101
#5  0x0000557ba7f33331 in main (argc=<optimized out>, argv=<optimized out>) at tools/lxc_stop.c:217
```

source code is corresponding to 1e04bb71da3ed829761ae8c729c3d021a6a709df

**Comment by edacval** [comment] 2020-04-15 23:42
Duplicate of https://github.com/lxc/lxc/issues/2754  and [old still unfixed Arch Linux bug](https://bugs.archlinux.org/task/61078) ?

**Comment by brauner** [comment] 2020-04-23 10:33
Yeah, it seems this needs to be fixed in the Archlinux service file. If there's still something we can do here please re-open. Thanks!

**Closed by brauner** 2020-04-23 10:33 UTC
Labels: Bug
