### ISSUE TITLE
network doesn't work by using LXC 1.0.7 create Debian jessie container

### ISSUE THREAD

**Issue by linlinlinlin** [lxc/lxc#578] opened 2015-07-01 02:59 UTC
My env: 
- lxc version: 1.0.7
- ubuntu version: 14.04

```
root@debian-jessie:/# ifconfig
eth0      Link encap:Ethernet  HWaddr 00:16:3e:34:d8:de  
          inet6 addr: fe80::216:3eff:fe34:d8de/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:8 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:648 (648.0 B)  TX bytes:648 (648.0 B)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)


```

**Comment by stgraber** [comment] 2015-07-01 14:51
is that with systemd as the init system for your container?

**Comment by linlinlinlin** [comment] 2015-07-02 04:06
Inside container, it is using systemd. 
```
root@debian-jessie:/# readlink /sbin/init
/lib/systemd/systemd

```
But the host Ubuntu:14.04 is not. Ubuntu 14.04 doesn't support systemd.

**Comment by stgraber** [comment] 2015-07-02 21:33
ok, is that a privileged or unprivileged container?

**Comment by linlinlinlin** [comment] 2015-07-03 00:11
Should be a privileged container by default. Doesn't change settings by myself.
Create container by:
```
lxc-create -t debian -n c1
```

**Comment by jakemagee** [comment] 2015-07-07 19:06
Without using sudo, wouldn't that lxc-create command create an unprivileged container?

I believe I'm seeing the same issue with lxc 1.1.2 (Ubuntu 15.04 host) and an unprivileged 15.04 container template.  It also seems that this is a duplicate of issue #539 ?

**Comment by brauner** [comment] 2017-04-25 10:11
This is not really `LXC`'s fault. If the init system doesn't start a dhcp client on startup you need to do it manually afterwards.

**Closed by brauner** 2017-04-25 10:11 UTC

**Comment by jakemagee** [comment] 2017-04-25 12:18
I agree with closing the issue... its really old and if the problem still exists we can open a new ticket.  However, the issue wasn't explicitly with the container's init system not starting a dhcp client.  The same OS had no problem if installed outside of LXC.
