### ISSUE TITLE
LXC erased my whole system (rm -rf /)

### ISSUE THREAD

**Issue by sim590** [lxc/lxc#2766] opened 2019-01-02 04:33 UTC
# Required information

 * Distribution: Debian buster
 * Distribution version: testing (buster)

# Issue description

*I'm writing this from memory... I have no PC to get the info from so...*

I created a container using

```
sudo lxc-create -t download -n foo1
```

I launched a terminal inside  using `sudo lxc-attach -n foo1 bash`. Then, I created a second one called some name like `foo2`, but I didn't want it anymore, so I deleted it using `sudo lxc-destroy -n foo2`.

After that... I'm not sure if something else I did, but I started to lose my binaries `ls`, `bash`, etc and by the time I tried to reboot, it was too late and I ended up in `initramfs` shell when rebooting.

**Comment by sim590** [comment] 2019-01-02 04:37
I don't know if it is related to #1051, but I'm linking it...

**Comment by brauner** [comment] 2019-01-02 16:46
We've never had that problem and I haven't been able to reproduce this. The only way that this could happen is if you had set:
```
lxc.rootfs.path = <storage-type>:/
```
which you would have needed to do manually. LXC never does this.

**Comment by brauner** [comment] 2019-01-02 16:46
Could it be that something else went wrong at the same time?

**Comment by sim590** [comment] 2019-01-03 18:12
I don't think anything else could have done that. I wasn't doing anything out of the ordinary of a normal person (nothing fancy) at the time other than using LXC. Plus, this is the only program I have executed using `sudo` during this time, so I cannot imagine nothing else could have caused that.

One thing I tried to do was to bind host's `/tmp` with `/tmp` on `foo1`. Could that have caused the issue if I destroyed that container? I don't remember if I tried to remove `foo1`, but may be that's a hint.

When I launched a live USB key to see what was left of my system, I saw that `/var/lib/lxc/foo1` was left there intact (may be because LXC doesn't delete other containers).

**Comment by jafd** [comment] 2019-02-18 21:15
Your problem is this slash:
```
lxc.mount.entry = /tmp /tmp none bind 0 0
-----------------------↑
```

The entry should look like this instead:
```
lxc.mount.entry = /tmp tmp none bind 0 0
```

I wonder how exactly is `lxc-destroy` destroying things since it was able to traverse up your host's `/tmp`...

**Comment by hallyn** [comment] 2019-02-19 15:03
We've talked in the past about throwing an error if the mount target is an absolute path but does not start with the lxc rootfs mountpoint.  So long as we support a config option to say "no really I *am* that crazy", I think that would be a good thing.

**Comment by sim590** [comment] 2019-02-19 15:28
I'm sorry that I can't give much more details about the issue. It's hard when your whole system is deleted. :disappointed:

**Comment by hallyn** [comment] 2019-02-19 15:36
It is.  Very sorry to hear about that.

@brauner any objections to the change I mentioned above?  Do you know about sites where they really need the mount target to be an absolute path?

**Comment by brauner** [comment] 2019-02-19 17:03
@hallyn, no objections. Can you send it?

**Comment by hallyn** [comment] 2019-02-19 19:42
Will do.

**Comment by hallyn** [comment] 2019-02-20 22:44
Nope, turns out this could not have happened through the lxc.mount.entry.  The 'lxc.mount.entry = /tmp /tmp"...  would have been ignored, since 2011.

**Comment by brauner** [comment] 2020-03-20 14:07
There has been no reproducer for this and all our investigations have not allowed us to come up with a reasonable explanation so closing this.

**Closed by brauner** 2020-03-20 14:07 UTC
