### ISSUE TITLE
fixed ip addresses don't work with centos guest images

### ISSUE THREAD

**Issue by Russell-IO** [lxc/lxc#1372] opened 2016-12-31 09:06 UTC
```
  lxc network attach bridge c1 eth0
  lxc config device set c1 eth0 ipv4.address 1.2.3.4
```

With an Ubuntu Machine, it picks up the assigned IP address, but with a CentOS machine it selects one randomly from the pool.
N.B. it seems that on first attempt this works, but on relaunches it dones't

**Comment by brauner** [comment] 2017-01-02 10:00
This has nothing to do with the template. I suspect that the configuration required to setup a static ip is a little more involved. @stgraber has discussed this issue her: https://github.com/lxc/lxd/issues/2083. Also, this issue should be opened against `LXD`. If you don't mind closing this one and re-opening on `LXD` would be great if you could do it.

**Comment by stgraber** [comment] 2017-01-03 17:21
```
stgraber@dakara:~$ lxc init images:centos/7 centos
Creating centos
stgraber@dakara:~$ lxc network attach lxdbr0 centos eth0
stgraber@dakara:~$ lxc config device set centos eth0 ipv4.address 10.156.0.4
stgraber@dakara:~$ lxc start centos
stgraber@dakara:~$ lxc list centos
+--------+---------+-------------------+-----------------------------------------------+------------+-----------+
|  NAME  |  STATE  |       IPV4        |                     IPV6                      |    TYPE    | SNAPSHOTS |
+--------+---------+-------------------+-----------------------------------------------+------------+-----------+
| centos | RUNNING | 10.156.0.4 (eth0) | fd42:a4f6:6365:4106:216:3eff:fe89:375d (eth0) | PERSISTENT | 0         |
+--------+---------+-------------------+-----------------------------------------------+------------+-----------+
stgraber@dakara:~$ lxc stop centos
stgraber@dakara:~$ lxc start centos
stgraber@dakara:~$ lxc list centos
+--------+---------+-------------------+-----------------------------------------------+------------+-----------+
|  NAME  |  STATE  |       IPV4        |                     IPV6                      |    TYPE    | SNAPSHOTS |
+--------+---------+-------------------+-----------------------------------------------+------------+-----------+
| centos | RUNNING | 10.156.0.4 (eth0) | fd42:a4f6:6365:4106:216:3eff:fe89:375d (eth0) | PERSISTENT | 0         |
+--------+---------+-------------------+-----------------------------------------------+------------+-----------+
stgraber@dakara:~$
```

**Comment by stgraber** [comment] 2017-01-03 17:22
So I'm unable to reproduce the described problem on LXD 2.7 here.

As @brauner said, LXD issues should be filed at https://github.com/lxc/lxd, so I'll close this issue.
If you can reproduce your problem with the steps above, please file a lxd issue and we'll take a look.

Thanks

**Closed by stgraber** 2017-01-03 17:22 UTC
