### ISSUE TITLE
cannot destory container which has a long custom lxcpath

### ISSUE THREAD

**Issue by record** [lxc/lxc#284] opened 2014-07-29 03:24 UTC
I'm using lxc 1.0.4 from Ubuntu Trusty.

Container can be created without problem with a long lxcpath, for example:
```text
/media/ssd-data/lxc-test/work/lxc/lxc/lxc/lxc/lxc/lxc/lxc/lxc/lxc/lxc/lxc/lxc/lxc/lxc/lxc/lxc/lxc/lxc/lxc/lxc/lxc/lxc/lxc/lxc/lxc/lxc/lxc/lxc/lxc/lxc/lxc/lxc/lxc/lxc/lxc/lxc
```

But lxc-destroy will fail and say:
```
lxc_container: Name too long
lxc_container: container 9876543210 is not stopped
Destroying 9876543210 failed
```

Additionally, lxc-start will fail, too.

**Comment by Kentoseth** [comment] 2016-06-23 02:44
@stgraber @hallyn 

I think this issue can be closed, as the reference to #343 indicates that the issue has been fixed and this is a duplicate of that.

**Closed** 2016-06-23 14:29 UTC
