### ISSUE TITLE
attach_wait ignores env_policy when passing a python function

### ISSUE THREAD

**Issue by Sorunome** [lxc/lxc#1112] opened 2016-08-02 15:43 UTC
Assuming `c` is a container object, the following works fine:

```
c.attach_wait(lxc.attach_run_command,['ls','/'],env_policy=lxc.LXC_ATTACH_CLEAR_ENV)
```

While the following yeilds "No such file or directory: 'ls'" (because the $PATH variable is too different on my host)

```
def test():
    subprocess.call(['ls','/'])
c.attach_wait(test,env_policy=lxc.LXC_ATTACH_CLEAR_ENV)
```

Or perhaps there is a way to manually clear the enviroment variables?

**Comment by stgraber** [comment] 2016-08-02 16:00
I wonder if the problem isn't subprocess carrying the host environment there.

**Comment by Sorunome** [comment] 2016-08-02 16:13
Is there a way for me to check?

**Comment by stgraber** [comment] 2016-08-02 16:19
You could try to print os.environ from within test() maybe?

**Comment by Sorunome** [comment] 2016-08-02 16:21
Ok, I just tried the following:

a `subprocess.call('/bin/echo $PATH',shell=True)` inside of the container returns the containers $PATH variable 

`subprocess.call('ls /',shell=True)` returns the correct, expected, listing of the root of the container. So it's probably an issue with subprocess?

**Comment by stgraber** [comment] 2016-08-02 16:23
So technically attach_run_command does go through the exact same code path as running an individual command, the only difference being that it's not using any python code.

So my guess is that subprocess/os may be making a copy of the process environment at loading time and so not noticing that the environment was cleared in the child.

**Comment by Sorunome** [comment] 2016-08-02 16:31
`os.environ` contains the old system variables, so it's a bug with `os`? Is there a way to manually refresh the enviroment variables?

**Comment by stgraber** [comment] 2016-08-02 16:53
I'm not sure, but I at least confirmed that lxc does seem to do the right thing with:

```
>>> def test():
...     import os
...     os.system("env")
... 

>>> lxc.Container("zerotier", "/var/lib/lxd/containers").attach_wait(test)
SUDO_GID=200512
MAIL=/var/mail/root
LANGUAGE=en_CA:en
USER=root
HOME=/home/stgraber
COLORTERM=gnome-terminal
container=lxc
SUDO_UID=201105
LOGNAME=root
TERM=xterm
USERNAME=root
COLUMNS=159
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
DISPLAY=:0
LANG=en_CA.UTF-8
XAUTHORITY=/home/stgraber/.Xauthority
SUDO_COMMAND=/usr/bin/python3
KRB5CCNAME=FILE:/tmp/krb5cc_201105_vCQjdE
SHELL=/bin/bash
SUDO_USER=stgraber
PWD=/
LINES=33
-1

>>> lxc.Container("zerotier", "/var/lib/lxd/containers").attach_wait(test, env_policy=lxc.LXC_ATTACH_CLEAR_ENV)
container=lxc
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
-1
>>> 
```

To be fair, this feature while very useful is pretty magic and I can certainly see how upstream python may not want to support this use case :)

**Comment by Sorunome** [comment] 2016-08-02 16:55
Yep, that gives me
```
container=lxc
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
```
So it isn't lxc's fault

**Comment by brauner** [comment] 2018-02-09 10:10
This isn't lxc's fault, so closing this issue.

**Closed by brauner** 2018-02-09 10:10 UTC
