### ISSUE TITLE
Privileged LXC container steals ZFS mountpoint from host

### ISSUE THREAD

**Issue by jefft** [lxc/lxc#1216] opened 2016-09-29 03:52 UTC
I have a ZFS filesystem `tank/dotfiles` mounted at `/dotfiles`, that I'd like to make `/dotfiles` visible in a ZFS-enabled LXD container (`storage.zfs_pool_name: tank/lxd`). I share the filesystem with:

`$ lxc config device add $CONTAINER shareddir disk source=/dotfiles path=/dotfiles`

When I start the container, the contents of `/dotfiles` on the server disappears (causing chaos). lxc has remounted it at /var/lib/lxd/devices/testzfs/disk.dotfiles, leaving zfs confused as to the real mountpoint.

Stopping the lxc container lets me remount the ZFS filesystem.

```
$ sudo zfs list -o name,mountpoint,mounted tank/dotfiles  # Everything is fine to start with..
NAME           MOUNTPOINT  MOUNTED
tank/dotfiles  /dotfiles       yes
$ lxc init ubuntu: testzfs
Creating testzfs
$ lxc config device add testzfs shareddir disk source=/dotfiles path=/dotfiles
Device shareddir added to testzfs
$ lxc config set testzfs security.privileged true
$ lxc start testzfs
$ sudo ls /dotfiles  # Uh-oh, /dotfiles contents has disappeared
$ 
$ sudo zfs mount tank/dotfiles  # Can't remount..
cannot mount 'tank/dotfiles': filesystem already mounted
$ sudo zfs list -o name,mountpoint,mounted tank/dotfiles  # ZFS knows it is mounted somewhere, but not in the indicated mountpoint...
NAME           MOUNTPOINT  MOUNTED
tank/dotfiles  /dotfiles       yes
$ mount | grep tank/dotfiles  # LXC has stolen my mountpoint!
tank/dotfiles on /var/lib/lxd/devices/testzfs/disk.dotfiles type zfs (ro,relatime,xattr,noacl)
$ lxc stop testzfs  # Stopping the lxc container releases the mount, and lets me remount at the correct location.
$ sudo zfs mount tank/dotfiles 
```

This problem only occurs with `security.privleged=true`. When `security.privileged` is off, and the container started, the ZFS filesystem is mounted both at its correct location and at the lxc location:

```
# mount | grep dotfiles
tank/dotfiles on /dotfiles type zfs (ro,relatime,xattr,noacl)
tank/dotfiles on /var/lib/lxd/devices/testzfs/disk.dotfiles type zfs (ro,relatime,xattr,noacl)
```

I'm using Ubuntu 16.04, zfs 0.6.5.6-0ubuntu12, lxc 2.0.4-0ubuntu1~ubuntu16.04.2.

**Comment by brauner** [comment] 2017-01-02 10:16
@jefft, this issue should be opened against `LXD`, not `LXC` so I'm closing it here. Please reopen on `LXD`. Thanks!

**Closed by brauner** 2017-01-02 10:16 UTC

**Comment by stgraber** [comment] 2017-01-03 17:30
I suspect this is a zfs/kernel bug unfortunately. Having a clean reproducer for it would certainly help reporting the issue though.

My best guess here is that something that's done by root in the container (which is the difference caused by security.privileged) is tickling the ZFS driver and causing the unmount from the host.

LXD itself only bind-mounts the ZFS filesystem to /var/lib/lxd/devices/... which isn't that weird an operation to do on a filesystem and certainly works fine with just about every other filesystem.
