### ISSUE TITLE
LXCFS causes FPE with ProcPS within containers

### ISSUE THREAD

**Issue by shinji257** [lxc/lxc#534] opened 2015-05-23 20:15 UTC
First some basic information so you know my environment...
Host: Linode
OS: Ubuntu 14.04.2
Kernel: Host supplied 4.0.1 -- also tested against PV-Grub loaded 4.1-RC4
Container Privilage: Unprivileged

shinji@icarus:/proc> apt-cache policy lxcfs
lxcfs:
  Installed: 0.7-0ubuntu2~ubuntu14.04.1~ppa1
  Candidate: 0.7-0ubuntu2~ubuntu14.04.1~ppa1
  Version table:
 *** 0.7-0ubuntu2~ubuntu14.04.1~ppa1 0
        500 http://ppa.launchpad.net/ubuntu-lxc/daily/ubuntu/trusty/main amd64 Packages
        100 /var/lib/dpkg/status

shinji@icarus:/proc> apt-cache policy procps
procps:
  Installed: 1:3.3.9-1ubuntu2.2
  Candidate: 1:3.3.9-1ubuntu2.2
  Version table:
 *** 1:3.3.9-1ubuntu2.2 0
        500 http://mirrors.linode.com/ubuntu/ trusty-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     1:3.3.9-1ubuntu2 0
        500 http://mirrors.linode.com/ubuntu/ trusty/main amd64 Packages

I literally just noticed this today.  When LXCFS is started and running ProcPS throws a Floating Point Exception inside containers.  I do not know why this is the case.  Oddly enough stopping LXCFS on the host and restarting the container makes the bug go away.  Ideas?  Anything I can test to isolate?

LXCFS Stopped
shinji@trusty-x86:~> ps u
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
shinji    1506  0.0  0.1   5816  3536 pts/4    Ss+  12:42   0:00 -bash
shinji    1519  0.0  0.1   5404  2684 pts/4    S+   12:42   0:00 tmux -2 -f /usr
shinji    1573  0.3  0.1   5696  3412 pts/5    Ss   12:42   0:00 /bin/bash
shinji    1679  0.0  0.1   5228  2340 pts/5    R+   12:42   0:00 ps u

LXCFS Started
shinji@trusty-x86:~> ps u
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
Signal 8 (FPE) caught by ps (procps-ng version 3.3.9).
shinji    1521  0.0ps:display.c:66: please report this bug
Floating point exception

**Comment by stgraber** [comment] 2015-05-25 15:00
The above is usually a sign that lxcfs on the host was restarted for some reason (crashed or upgraded).

Unfortunately because of the way bind-mounts work in the kernel, a restart of lxcfs on the host breaks lxcfs in all existing containers, so you have to restart them all...

I believe what you're seeing above is the result of ps exploding on a broken /proc file.
You could confirm that hypothesis by trying to cat /proc/uptime in the container. If that returns some odd error, then that's very likely the problem.

**Comment by shinji257** [comment] 2015-05-25 15:22
Nope.  That's not the case at all.  The issue above was done real time.  I guess I forgot to mention that I restarted the container each time.  Here is a better example that I did just now.

shinji@icarus:~> lxc-stop -n trusty-x86
shinji@icarus:~> sudo service lxcfs restart
lxcfs stop/waiting
lxcfs start/running, process 30782
shinji@icarus:~> lxc-start -n trusty-x86
shinji@icarus:~> ssh trusty-x86
shinji@trusty-x86's password:
shinji@trusty-x86:~$ ps u
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
Signal 8 (FPE) caught by ps (procps-ng version 3.3.9).
shinji    1521  0.0ps:display.c:66: please report this bug
Floating point exception
shinji@trusty-x86:~$ cat /proc/uptime
93 0

**Comment by stgraber** [comment] 2015-05-25 15:34
so looks like ps opens /proc/meminfo and /proc/uptime which are both lxcfs files, can you confirm /proc/meminfo is also readable in your container?

If it is, then having the output of "strace -fF ps u" would be useful.

**Comment by shinji257** [comment] 2015-05-25 15:40
Huh... I just checked and I found that /proc/meminfo is blank for some reason.  This was probably why top was showing inf in the %mem column before (but it wasn't crashing).

-r--r--r--  1 nobody nogroup            1014 May 25 15:39 meminfo
shinji@trusty-x86:~$ sudo cat /proc/meminfo
[sudo] password for shinji:
shinji@trusty-x86:~$

**Comment by stgraber** [comment] 2015-05-25 15:44
Can you paste the content of /var/log/upstart/lxcfs.log and /var/log/upstart/cgmanager.log from your host (if they exist)?

**Comment by shinji257** [comment] 2015-05-25 15:50
/var/log/upstart/lxcfs.log
select: Resource temporarily unavailable

/var/log/upstart/cgmanager.log
cgmanager: Found no cgroup entry for pid 1737 controller 5

cgmanager:get_pid_cgroup_main: Could not determine the requestor's cgroup for 5

**Comment by stgraber** [comment] 2015-05-25 15:54
I've never seen that lxcfs error before, odd.

So does:
 - stop the container
 - sudo restart lxcfs
 - start the container

help at all?

If not, can you then try:
 - stop the container
 - sudo restart cgmanager
 - sudo restart lxcfs
 - start the container

That should tell us whether the problem is with lxcfs or with cgmanager.

**Comment by shinji257** [comment] 2015-05-25 16:06
Not even restarting cgmanager helps however it did spit out more logging.

shinji@icarus:~> lxc-stop -n trusty-x86
shinji@icarus:~> sudo restart cgmanager
cgmanager start/running, process 9628
shinji@icarus:~> sudo restart lxcfs
lxcfs start/running, process 9719
shinji@icarus:~> lxc-start -n trusty-x86
shinji@icarus:~> ssh trusty-x86
shinji@trusty-x86's password:
shinji@trusty-x86:~$ cat /proc/meminfo
shinji@trusty-x86:~$

/var/log/upstart/cgmanager.log
cgmanager: Found no cgroup entry for pid 1737 controller 7

cgmanager:get_pid_cgroup_main: Could not determine the requestor's cgroup for 7
initctl: invalid command: notify-cgroup-manager-address
Try `initctl --help' for more information.

Now then checking the bit above here it looks like 7 refers to my session.  pid 1737 is systemd-logind.  I checked a bit further but I'm not sure where it is coming from.  I have a suspicion though I'm going to check.  My host drops all the memory controller stuff from their kernels because it can't be enabled anyways.  The rebuild I did was using their kernel config.  I'm going to try a distribution kernel and report back.  

For reference. (note no memory controller)
shinji@icarus:~> cat /proc/self/cgroup
11:name=systemd:/user/1000.user/7.session
10:perf_event:/user/1000.user/7.session
9:net_prio:/user/1000.user/7.session
8:net_cls:/user/1000.user/7.session
7:freezer:/user/1000.user/7.session
6:devices:/user/1000.user/7.session
5:debug:/user/1000.user/7.session
4:cpuacct:/user/1000.user/7.session
3:blkio:/user/1000.user/7.session
2:cpu:/user/1000.user/7.session
1:cpuset:/user/1000.user/7.session
shinji@icarus:~> cat /proc($pidof cgmanager)/cgroup
bash: syntax error near unexpected token `('
2 shinji@icarus:~> cat /proc/$(pidof cgmanager)/cgroup
11:name=systemd:/
10:perf_event:/
9:net_prio:/
8:net_cls:/
7:freezer:/
6:devices:/
5:debug:/
4:cpuacct:/
3:blkio:/
2:cpu:/
1:cpuset:/

**Comment by stgraber** [comment] 2015-05-25 16:10
Oh, yeah, the lack of memory controller would totally explain what you're seeing...

**Comment by stgraber** [comment] 2015-05-25 16:11
Can you go file a bug at https://github.com/lxc/lxcfs about having lxcfs deal with missing controllers (and return the unmodified host value in that case)?

**Comment by shinji257** [comment] 2015-05-25 16:23
Yup.  Will do.  I pulled down the distribution 3.13 kernel and confirmed that getting the memory controller back resolves the "issue" even if it isn't enabled.

**Comment by shinji257** [comment] 2015-05-25 16:39
Done...
https://github.com/lxc/lxcfs/issues/30

**Comment by stgraber** [comment] 2015-05-25 16:46
Perfect, closing this issue, will track the fix in the lxcfs one.

**Closed by stgraber** 2015-05-25 16:46 UTC
