### ISSUE TITLE
If /var/lib/lxc is a zfs dataset lxc-create fails due to rsync: rsync_xal_set: lsetxattr(""/var/lib/lxc/ubuntu-17.10-amd64/rootfs/."","btrfs.compression") failed: Operation not supported (95)

### ISSUE THREAD

**Issue by krichter722** [lxc/lxc#1937] opened 2017-11-22 19:17 UTC
# Required information

 * Distribution: Ubuntu
 * Distribution version: 17.10 amd64
 * The output of
   * lxc-start --version: 2.1.0 (lxc-2.1.0-234-g0ad23532 according to `git describe`)
<details><summary><tt>lxc-checkconfig</tt></summary><pre>
Kernel configuration not found at /proc/config.gz; searching...
Kernel configuration found at /boot/config-4.13.0-16-generic
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: enabled

--- Control groups ---
Cgroups: enabled

Cgroup v1 mount points: 
/sys/fs/cgroup/systemd
/sys/fs/cgroup/devices
/sys/fs/cgroup/net_cls,net_prio
/sys/fs/cgroup/rdma
/sys/fs/cgroup/cpu,cpuacct
/sys/fs/cgroup/pids
/sys/fs/cgroup/blkio
/sys/fs/cgroup/memory
/sys/fs/cgroup/freezer
/sys/fs/cgroup/perf_event
/sys/fs/cgroup/cpuset
/sys/fs/cgroup/hugetlb

Cgroup v2 mount points: 
/sys/fs/cgroup/unified

Cgroup v1 clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, not loaded
Macvlan: enabled, not loaded
Vlan: enabled, not loaded
Bridges: enabled, loaded
Advanced netfilter: enabled, not loaded
CONFIG_NF_NAT_IPV4: enabled, loaded
CONFIG_NF_NAT_IPV6: enabled, not loaded
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, loadedCONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
FUSE (for use with lxcfs): enabled, not loaded

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities: enabled

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/local/bin/lxc-checkconfig</pre></details>
   * `uname -a`: `Linux richter-Lenovo-IdeaPad-Z500 4.13.0-16-generic #19-Ubuntu SMP Wed Oct 11 18:35:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
<details><summary><tt>cat /proc/self/cgroup</tt></summary><pre>12:hugetlb:/
11:cpuset:/
10:perf_event:/
9:freezer:/user/richter/0
8:memory:/user/richter/0
7:blkio:/user.slice
6:pids:/user.slice/user-1000.slice/user@1000.service
5:cpu,cpuacct:/user.slice
4:rdma:/
3:net_cls,net_prio:/
2:devices:/user.slice
1:name=systemd:/user.slice/user-1000.slice/user@1000.service/gnome-terminal-server.service
0::/user.slice/user-1000.slice/user@1000.service/gnome-terminal-server.service</pre>
</details>
<details><summary><tt>cat /proc/1/mounts</tt></summary><pre>sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
udev /dev devtmpfs rw,nosuid,relatime,size=8112636k,nr_inodes=2028159,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=1628080k,mode=755 0 0
/dev/sda5 / btrfs rw,relatime,compress-force=zlib,ssd,space_cache,subvolid=257,subvol=/ubuntu-main-root 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/unified cgroup2 rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
efivarfs /sys/firmware/efi/efivars efivarfs rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/rdma cgroup rw,nosuid,nodev,noexec,relatime,rdma 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset,clone_children 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime,pagesize=2M 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=37,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=19295 0 0
sunrpc /run/rpc_pipefs rpc_pipefs rw,relatime 0 0
mqueue /dev/mqueue mqueue rw,relatime 0 0
fusectl /sys/fs/fuse/connections fusectl rw,relatime 0 0
configfs /sys/kernel/config configfs rw,relatime 0 0
/dev/sda8 /boot ext4 rw,relatime,data=ordered 0 0
/dev/sda6 /boot/efi vfat rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro 0 0
/dev/sda5 /home btrfs rw,relatime,compress-force=zlib,ssd,space_cache,subvolid=258,subvol=/ubuntu-main-home 0 0
binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc rw,relatime 0 0
lxcfs /var/lib/lxcfs fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
/dev/sda5 /var/lib/docker/plugins btrfs rw,relatime,compress-force=zlib,ssd,space_cache,subvolid=257,subvol=/ubuntu-main-root/var/lib/docker/plugins 0 0
/dev/sda5 /var/lib/docker/btrfs btrfs rw,relatime,compress-force=zlib,ssd,space_cache,subvolid=257,subvol=/ubuntu-main-root/var/lib/docker/btrfs 0 0
tmpfs /run/user/1000 tmpfs rw,nosuid,nodev,relatime,size=1628076k,mode=700,uid=1000,gid=1000 0 0
gvfsd-fuse /run/user/1000/gvfs fuse.gvfsd-fuse rw,nosuid,nodev,relatime,user_id=1000,group_id=1000 0 0
data /data zfs rw,noatime,xattr,noacl 0 0
data/data/build /mnt/data/build zfs rw,noatime,xattr,noacl 0 0
data/data/home /mnt/data/home zfs rw,noatime,xattr,noacl 0 0
data/data/home-x86_64 /mnt/data/home-x86_64 zfs rw,noatime,xattr,noacl 0 0
data/data/sources /mnt/data/sources zfs rw,noatime,xattr,noacl 0 0
data/data/videos /mnt/data/videos zfs rw,noatime,xattr,noacl 0 0
data/data/virtualbox-vms /mnt/data/virtualbox-vms zfs rw,noatime,xattr,noacl 0 0
data/openafs-cache /mnt/openafs-cache zfs rw,noatime,xattr,noacl 0 0
data/coda-cache /var/lib/coda zfs rw,noatime,xattr,noacl 0 0
data/data/lxc /var/lib/lxc zfs rw,noatime,xattr,noacl 0 0
encfs /home/richter/Device9 fuse.encfs rw,nosuid,nodev,relatime,user_id=1000,group_id=1000,default_permissions 0 0
gvfsd-fuse /home/richter/.gvfs fuse.gvfsd-fuse rw,nosuid,nodev,relatime,user_id=0,group_id=0 0 0
/dev/loop0 /snap/core/3440 squashfs ro,nodev,relatime 0 0
tmpfs /run/snapd/ns tmpfs rw,nosuid,noexec,relatime,size=1628080k,mode=755 0 0
nsfs /run/snapd/ns/core.mnt nsfs rw 0 0
/dev/loop1 /snap/lxd/5061 squashfs ro,nodev,relatime 0 0
nsfs /run/snapd/ns/lxd.mnt nsfs rw 0 0</pre></details>

# Issue description
`sudo /usr/local/bin/lxc-create -n ubuntu-17.10-amd64 -t /usr/local/share/lxc/templates/lxc-ubuntu -- --arch amd64 --release artful` causes the container creation to fail due to

```
Download complete
Copy /usr/local/var/cache/lxc/artful/rootfs-amd64 to /var/lib/lxc/ubuntu-17.10-amd64/rootfs ... 
Copying rootfs to /var/lib/lxc/ubuntu-17.10-amd64/rootfs ...
rsync: rsync_xal_set: lsetxattr(""/var/lib/lxc/ubuntu-17.10-amd64/rootfs/."","btrfs.compression") failed: Operation not supported (95)
rsync: rsync_xal_set: lsetxattr(""/var/lib/lxc/ubuntu-17.10-amd64/rootfs/bin"","btrfs.compression") failed: Operation not supported (95)
rsync: rsync_xal_set: lsetxattr(""/var/lib/lxc/ubuntu-17.10-amd64/rootfs/bin/.bash.30MB8v"","btrfs.compression") failed: Operation not supported (95)
rsync: rsync_xal_set: lsetxattr(""/var/lib/lxc/ubuntu-17.10-amd64/rootfs/bin/bzcmp"","btrfs.compression") failed: Operation not supported (95)
rsync: rsync_xal_set: lsetxattr(""/var/lib/lxc/ubuntu-17.10-amd64/rootfs/bin/.bzdiff.krVoXN"","btrfs.compression") failed: Operation not supported (95)
rsync: rsync_xal_set: lsetxattr(""/var/lib/lxc/ubuntu-17.10-amd64/rootfs/bin/bzegrep"","btrfs.compression") failed: Operation not supported (95)
[same message repeated for every file of the container]
```

The root filesystem is a btrfs while `/var/lib/lxc` is a ZFS dataset. The `lxc-create` command never returns after printing the messages above. After pressing <kbd>Ctrl</kbd><kbd>C</kbd> after no I/O activity is observable for > 30 minutes in order to abort the hanging command more messages are printed followed by 

```
rsync: [receiver] write error: Broken pipe (32)
rsync error: received SIGINT, SIGTERM, or SIGHUP (code 20) at io.c(513) [receiver=3.1.2]
rsync: [sender] write error: Broken pipe (32)
```

The creation with `-P /usr/local/var/lib/lxc` which is on a btrfs and the same subvolume as the root filesystem works fine.

# Steps to reproduce

 1. `sudo /usr/local/bin/lxc-create -n ubuntu-17.10-amd64 -t /usr/local/share/lxc/templates/lxc-ubuntu -- --arch amd64 --release artful`

# Information to attach

 - [ ] any relevant kernel output (`dmesg`)
 - [ ] container log (The <log> file from running `lxc-start -n <c> -l <log> -o DEBUG`)
 - [ ] the containers configuration file

**Comment by brauner** [comment] 2017-11-22 19:25
Is this a privileged or an unprivileged container?

**Comment by brauner** [comment] 2017-11-22 19:25
Looks like the `zfs` dataset is mounted without the `xattr` option.

**Comment by krichter722** [comment] 2017-11-22 19:27
> Is this a privileged or an unprivileged container?

How do I figure this out?

> Looks like the zfs dataset is mounted without the xattr option.

If you want me to check that, I'd need to know how.

**Comment by brauner** [comment] 2017-11-22 19:30
findmnt | grep zfs
    findmnt | grep /var/lib/lxc

**Comment by krichter722** [comment] 2017-11-22 19:34
```
> findmnt | grep zfs
├─/data                               data                                                zfs             rw,noatime,xattr,noacl
├─/mnt/data/build                     data/data/build                                     zfs             rw,noatime,xattr,noacl
├─/mnt/data/home                      data/data/home                                      zfs             rw,noatime,xattr,noacl
├─/mnt/data/home-x86_64               data/data/home-x86_64                               zfs             rw,noatime,xattr,noacl
├─/mnt/data/sources                   data/data/sources                                   zfs             rw,noatime,xattr,noacl
├─/mnt/data/videos                    data/data/videos                                    zfs             rw,noatime,xattr,noacl
├─/mnt/data/virtualbox-vms            data/data/virtualbox-vms                            zfs             rw,noatime,xattr,noacl
├─/mnt/openafs-cache                  data/openafs-cache                                  zfs             rw,noatime,xattr,noacl
├─/var/lib/coda                       data/coda-cache                                     zfs             rw,noatime,xattr,noacl
└─/var/lib/lxc                        data/data/lxc                                       zfs             rw,noatime,xattr,noacl
> findmnt | grep /var/lib/lxc
├─/var/lib/lxcfs                      lxcfs                                               fuse.lxcfs      rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other
└─/var/lib/lxc                        data/data/lxc                                       zfs             rw,noatime,xattr,noacl
```

**Comment by brauner** [comment] 2017-11-22 19:45
You need to remount the `zfs` dataset for `/var/lib/lxc` with `acl` permissions enabled.

**Comment by brauner** [comment] 2017-11-22 19:46
`zfs set acltype=posixacl data/data/lxc`

**Comment by krichter722** [comment] 2017-11-22 19:49
After

    sudo zfs umount data/data/lxc
    sudo zfs set acltype=posixacl data/data/lxc
    sudo zfs mount data/data/lxc

the issue still occurs.

**Comment by brauner** [comment] 2017-11-22 19:53
How does the `btrfs` filesystem that the container will be created on come into existence?

**Comment by krichter722** [comment] 2017-11-22 19:59
The root filesystem is `btrfs` whose mounpoint is specified in `/etc/fstab`:

```
UUID=8371a2ab-969d-43fa-9c5d-365881d340b9 / btrfs subvol=ubuntu-main-root,defaults,compress-force=zlib,ssd,space_cache 0 1
UUID=8371a2ab-969d-43fa-9c5d-365881d340b9 /home btrfs subvol=ubuntu-main-home,defaults,compress-force=zlib,ssd,space_cache 0 1
UUID=592abaef-f7c2-410f-a486-ca2e76d45ae9 none            swap    sw,pri=100              0       0
UUID=1bb0bb3e-8148-4957-9673-9701bd571c0a none swap sw,pri=10 0 0
UUID=eff9227c-2b4e-4aa5-85c1-81e16766fb27 /boot ext4 defaults 0 1
UUID=7B27-4522 /boot/efi vfat defaults 0 1
```

Since `/var/lib/lxc` is a ZFS mountpoint I assume you mean "How does the ZFS filesystem that the container will be created on come into existence?", right? Since I build ZFS from source currently, the pool is imported with the following `systemd` unit:

```
[Unit]
Description=ZFS pool import for source installations of ZFS
After=local-fs.target

[Service]
Type=oneshot
ExecStart=/usr/local/sbin/zpool import -d /dev data

[Install]
WantedBy=multi-user.target
```

**Comment by brauner** [comment] 2017-11-22 20:27
> The root filesystem is a btrfs while /var/lib/lxc is a ZFS dataset. 

Ah, I was confused. I thought root filesystem was referring to the container's root filesystem. Can you please show me:

    findmnt | grep zfs

after you changed the acl type again?

**Comment by krichter722** [comment] 2017-11-22 20:29
```
> findmnt | grep zfs
├─/var/lib/lxc                        data/data/lxc                                       zfs             rw,noatime,xattr,posixacl
├─/data                               data                                                zfs             rw,noatime,xattr,noacl
├─/mnt/data/build                     data/data/build                                     zfs             rw,noatime,xattr,noacl
├─/mnt/data/home                      data/data/home                                      zfs             rw,noatime,xattr,noacl
├─/mnt/data/home-x86_64               data/data/home-x86_64                               zfs             rw,noatime,xattr,noacl
├─/mnt/data/sources                   data/data/sources                                   zfs             rw,noatime,xattr,noacl
├─/mnt/data/videos                    data/data/videos                                    zfs             rw,noatime,xattr,noacl
├─/mnt/data/virtualbox-vms            data/data/virtualbox-vms                            zfs             rw,noatime,xattr,noacl
├─/mnt/openafs-cache                  data/openafs-cache                                  zfs             rw,noatime,xattr,noacl
└─/var/lib/coda                       data/coda-cache                                     zfs             rw,noatime,xattr,noacl
```

**Comment by brauner** [comment] 2017-11-22 20:44
Ok, I think the problem is that the `btrfs.*` xattr namespace is only supported on `btrfs` filesystems. So when you download the rootfs for the container and store it on your `btrfs` filesystem all files receive the `btrfs.compression` xattr. When you now copy these files to a different filesystem (`zfs`) these xattr are not supported.
The trick here would be to probably mount a zfs dataset to `/usr/local/var/cache/lxc/` as a workaround.

**Comment by krichter722** [comment] 2017-11-22 21:53
I currently can't test the workaround because I can't remove the directory and ZFS requires it to be empty (see https://askubuntu.com/questions/979274/why-cant-i-remove-usr-local-var-cache-lxc for details). I don't mind working the a different `--lxcpath` as another workaround.

Thanks for you support so far, I hope this gets fixed soon.

**Comment by brauner** [comment] 2018-02-10 11:34
Ok, closing this then.

**Closed by brauner** 2018-02-10 11:34 UTC

**Comment by krichter722** [comment] 2018-02-10 11:43
> Ok, closing this then.

The fact that I can't test the workaround doesn't mean that the issue is no longer present and not worth fixing (not supporting ZFS in such an unintuitive way will be a problem sooner than later).
