### ISSUE TITLE
Apparmor dhclient operation denied in snapshotted container

### ISSUE THREAD

**Issue by timofurrer** [lxc/lxc#1582] opened 2017-05-22 07:33 UTC
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: **Ubuntu**
 * Distribution version: **16.04**
 * The output of
   * `lxc-start --version`: **2.0.7**
   * `lxc-checkconfig`: **everything enabled**
   * `uname -a`: **Linux <host> 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux**
   * `cat /proc/self/cgroup`
   * `cat /proc/1/mounts`

# Issue description

I create a container (profile: unconfined) with a single *veth* interface linked to `lxcbr0` on the host. 
The networking works absolute fine - I used dhcp in the container to get an IP address.

When I copy this container with something like this:

```
sudo lxc-copy --snaphost --backingstorage aufs --name <container> --newname <newcontainer>
```

And start the container I can't get an IP address for this copied container. On the host I get this apparmor logs in syslog:

```
May 22 09:25:51<host> kernel: [262567.487602] audit: type=1400 audit(1495437951.066:119): apparmor="DENIED" operation="open" profile="/sbin/dhclient" name="/var/lib/lxc/rico-ace94909-a79e-4c0e-9382-b0aa24a93f6b/rootfs/etc/ld.so.cache" pid=30188 comm="dhclient" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
May 22 09:25:51 <host>4 kernel: [262567.487799] audit: type=1400 audit(1495437951.070:120): apparmor="DENIED" operation="open" profile="/sbin/dhclient" name="/var/lib/lxc/rico-ace94909-a79e-4c0e-9382-b0aa24a93f6b/rootfs/lib/i386-linux-gnu/libirs-export.so.91.0.0" pid=30188 comm="dhclient" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
```

In the container the output of `ifup -a` is the following:

```
dhclient: error while loading shared libraries: libirs-export.so.91: cannot open shared object file: No such file or directory
Failed to bring up eth10.
```

Do you have any idea what's happening here?

**Comment by stgraber** [comment] 2017-05-22 19:55
When unconfined, apparmor profiles from the host may apply to the container, which is what's happening to your dhclient here.

The easiest workaround for it is to unload that apparmor profile from your host.

Closing as it's not an LXC issue, but rather the expected behavior of apparmor on a system with loaded profiles and apparmor disabled at the LXC level (unconfined). The reason why this would only happen when overlay filesystems are in the mix is because apparmor can't resolve paths properly with those (that's an apparmor issue).

**Closed by stgraber** 2017-05-22 19:55 UTC
