### ISSUE TITLE
lxc 5.0 cannot start container with bind mounts

### ISSUE THREAD

**Issue by RealSaltyFish** [lxc/lxc#4162] opened 2022-07-03 17:30 UTC
# Required information

 * Distribution: Arch Linux
 * Distribution version: N/A
 * The output of
   * `lxc-start --version`: 5.0.0
   * `lxc-checkconfig`: attached below
   * `uname -a`: `Linux [hostname] 5.15.50-1-lts #1 SMP Sat, 25 Jun 2022 14:58:59 +0000 x86_64 GNU/Linux`
   * `cat /proc/self/cgroup`: `0::/user.slice/user-1000.slice/session-6.scope`
   * `cat /proc/1/mounts`: attached below

```
LXC version 5.0.0
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Warning: newuidmap is not setuid-root
Warning: newgidmap is not setuid-root
Network namespace: enabled

--- Control groups ---
Cgroups: enabled
Cgroup namespace: enabled

Cgroup v1 mount points:


Cgroup v2 mount points:
/sys/fs/cgroup

Cgroup v1 systemd controller: missing
Cgroup v1 freezer controller: missing
Cgroup ns_cgroup: required
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, loaded
Macvlan: enabled, not loaded
Vlan: enabled, not loaded
Bridges: enabled, loaded
Advanced netfilter: enabled, loaded
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, not loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
FUSE (for use with lxcfs): enabled, loaded

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities:

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig

```

```
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
sys /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
dev /dev devtmpfs rw,nosuid,relatime,size=16367036k,nr_inodes=4091759,mode=755,inode64 0 0
run /run tmpfs rw,nosuid,nodev,relatime,mode=755,inode64 0 0
efivarfs /sys/firmware/efi/efivars efivarfs rw,nosuid,nodev,noexec,relatime 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
zroot/ROOT/default / zfs rw,nodev,relatime,xattr,posixacl 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev,inode64 0 0
cgroup2 /sys/fs/cgroup cgroup2 rw,nosuid,nodev,noexec,relatime 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
bpf /sys/fs/bpf bpf rw,nosuid,nodev,noexec,relatime,mode=700 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=29,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=16893 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime,pagesize=2M 0 0
mqueue /dev/mqueue mqueue rw,nosuid,nodev,noexec,relatime 0 0
debugfs /sys/kernel/debug debugfs rw,nosuid,nodev,noexec,relatime 0 0
tracefs /sys/kernel/tracing tracefs rw,nosuid,nodev,noexec,relatime 0 0
configfs /sys/kernel/config configfs rw,nosuid,nodev,noexec,relatime 0 0
none /run/credentials/systemd-sysusers.service ramfs ro,nosuid,nodev,noexec,relatime,mode=700 0 0
fusectl /sys/fs/fuse/connections fusectl rw,nosuid,nodev,noexec,relatime 0 0
zroot/data/home /home zfs rw,nodev,relatime,xattr,posixacl 0 0
zroot/var/log /var/log zfs rw,nodev,relatime,xattr,posixacl 0 0
zroot/data/home/root /root zfs rw,nodev,relatime,xattr,posixacl 0 0
zroot/var/lib/libvirt /var/lib/libvirt zfs rw,nodev,relatime,xattr,posixacl 0 0
zroot/var/lib/docker /var/lib/docker zfs rw,nodev,relatime,xattr,posixacl 0 0
tmpfs /tmp tmpfs rw,nosuid,nodev,relatime,inode64 0 0
/dev/mapper/bootdev /boot ext4 rw,relatime 0 0
/dev/nvme0n1p1 /boot/efi vfat rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,utf8,errors=remount-ro 0 0
lxcfs /var/lib/lxcfs fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
tmpfs /run/user/1000 tmpfs rw,nosuid,nodev,relatime,size=3275904k,nr_inodes=818976,mode=700,uid=1000,gid=1000,inode64 0 0
gvfsd-fuse /run/user/1000/gvfs fuse.gvfsd-fuse rw,nosuid,nodev,relatime,user_id=1000,group_id=1000 0 0
tmpfs /var/lib/lxd/shmounts tmpfs rw,relatime,size=100k,mode=711,inode64 0 0
tmpfs /var/lib/lxd/devlxd tmpfs rw,relatime,size=100k,mode=755,inode64 0 0
binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc rw,nosuid,nodev,noexec,relatime 0 0
```

# Issue description

After upgrading to lxc 5.0, all my containers with bind mounts fail to start.

# Steps to reproduce

 1. Create a new lxc container `test`.
 2. Start it. The container runs normally.
 3. Stop the container. Run `lxc config device add test something disk source=/opt path=/mnt` to add a bind mount.
 4. Start the container. It doesn't work.
 5. Run `lxc info --show-log test` to see the logs:

```
Name: test
Status: STOPPED
Type: container
Architecture: x86_64
Created: 2022/06/25 14:53 EDT
Last Used: 2022/07/02 23:36 EDT

Log:

lxc test 20220703033605.652 ERROR    conf - ../src/lxc/conf.c:mount_entry:2459 - Operation not permitted - Failed to mount "/var/lib/lxd/devices/test/disk.something.mnt" on "/usr/lib/lxc/rootfs/mnt"
lxc test 20220703033605.652 ERROR    conf - ../src/lxc/conf.c:lxc_setup:4375 - Failed to setup mount entries
lxc test 20220703033605.652 ERROR    start - ../src/lxc/start.c:do_start:1275 - Failed to setup container "test"
lxc test 20220703033605.652 ERROR    sync - ../src/lxc/sync.c:sync_wait:34 - An error occurred in another process (expected sequence number 3)
lxc test 20220703033605.660 WARN     network - ../src/lxc/network.c:lxc_delete_network_priv:3631 - Failed to rename interface with index 0 from "eth0" to its initial name "veth81215611"
lxc test 20220703033605.660 ERROR    lxccontainer - ../src/lxc/lxccontainer.c:wait_on_daemonized_start:877 - Received container state "ABORTING" instead of "RUNNING"
lxc test 20220703033605.660 ERROR    start - ../src/lxc/start.c:__lxc_start:2074 - Failed to spawn container "test"
lxc test 20220703033605.661 WARN     start - ../src/lxc/start.c:lxc_abort:1039 - No such process - Failed to send SIGKILL via pidfd 17 for process 3481996
lxc 20220703033610.910 ERROR    af_unix - ../src/lxc/af_unix.c:lxc_abstract_unix_recv_fds_iov:218 - Connection reset by peer - Failed to receive response
lxc 20220703033610.910 ERROR    commands - ../src/lxc/commands.c:lxc_cmd_rsp_recv_fds:127 - Failed to receive file descriptors for command "get_state"
```

# Information to attach

any relevant kernel output (`dmesg`): nothing happens there when the error occurs

container log (The <log> file from running `lxc-start -n <c> -l TRACE -o <logfile> `): https://pastebin.com/P4hXTa5D (Since I used lxd, I manually specified the container configuration file `/var/log/lxd/test/lxc.conf`.)

the containers configuration file:
```
lxc.log.file = /var/log/lxd/test/lxc.log
lxc.log.level = warn
lxc.console.buffer.size = auto
lxc.console.size = auto
lxc.console.logfile = /var/log/lxd/test/console.log
lxc.mount.auto = proc:rw sys:rw cgroup:rw:force
lxc.autodev = 1
lxc.pty.max = 1024
lxc.mount.entry = /dev/fuse dev/fuse none bind,create=file,optional 0 0
lxc.mount.entry = /dev/net/tun dev/net/tun none bind,create=file,optional 0 0
lxc.mount.entry = /proc/sys/fs/binfmt_misc proc/sys/fs/binfmt_misc none rbind,create=dir,optional 0 0
lxc.mount.entry = /sys/firmware/efi/efivars sys/firmware/efi/efivars none rbind,create=dir,optional 0 0
lxc.mount.entry = /sys/fs/fuse/connections sys/fs/fuse/connections none rbind,create=dir,optional 0 0
lxc.mount.entry = /sys/fs/pstore sys/fs/pstore none rbind,create=dir,optional 0 0
lxc.mount.entry = /sys/kernel/config sys/kernel/config none rbind,create=dir,optional 0 0
lxc.mount.entry = /sys/kernel/debug sys/kernel/debug none rbind,create=dir,optional 0 0
lxc.mount.entry = /sys/kernel/security sys/kernel/security none rbind,create=dir,optional 0 0
lxc.mount.entry = /sys/kernel/tracing sys/kernel/tracing none rbind,create=dir,optional 0 0
lxc.mount.entry = /dev/mqueue dev/mqueue none rbind,create=dir,optional 0 0
lxc.include = /usr/share/lxc/config/common.conf.d/
lxc.arch = linux64
lxc.hook.version = 1
lxc.hook.pre-start = /proc/4111/exe callhook /var/lib/lxd "default" "test" start
lxc.hook.stop = /usr/bin/lxd callhook /var/lib/lxd "default" "test" stopns
lxc.hook.post-stop = /usr/bin/lxd callhook /var/lib/lxd "default" "test" stop
lxc.tty.max = 0
lxc.uts.name = test
lxc.mount.entry = /var/lib/lxd/devlxd dev/lxd none bind,create=dir 0 0
lxc.apparmor.profile = unconfined
lxc.seccomp.profile = /var/lib/lxd/security/seccomp/test
lxc.idmap = u 0 100000 65536
lxc.idmap = g 0 100000 65536
lxc.mount.auto = shmounts:/var/lib/lxd/shmounts/test:/dev/.lxd-mounts
lxc.net.0.type = phys
lxc.net.0.name = eth0
lxc.net.0.flags = up
lxc.net.0.link = veth32356ae8
lxc.rootfs.path = dir:/var/lib/lxd/storage-pools/default/containers/test/rootfs
lxc.mount.entry = /var/lib/lxd/devices/test/disk.something.mnt mnt none bind,create=dir 0 0
```

Note that I'm using root on ZFS, and I'm using ZFS to manage `/var/lxc`. Could that be the origin of issue?

**Comment by stgraber** [comment] 2022-07-03 18:54
https://discuss.linuxcontainers.org/t/cannot-start-lxc-containers-with-gui-profile/14497

**Comment by stgraber** [comment] 2022-07-03 18:55
I'm also on ZFS root here and am yet to have any luck reproducing this issue unfortunately.
It's good to know that it's possible to hit this outside of the LXD snap though, that removes one less variable.

**Comment by stgraber** [comment] 2022-07-03 18:59
Looks like this may actually have been fixed already https://github.com/lxc/lxc/issues/4160

**Comment by stgraber** [comment] 2022-07-03 19:01
Tentatively closing this.

**Closed by stgraber** 2022-07-03 19:01 UTC
