### ISSUE TITLE
LXD containers are unable to reach  network 

### ISSUE THREAD

**Issue by netmoleCBA** [lxc/lxc#1238] opened 2016-10-17 10:36 UTC
Hello there ,

i am new at lxd 
i am on ubuntu :16.04 
i am proceed all steps from  tutorial at  https://www.stgraber.org/2016/03/15/lxd-2-0-installing-and-configuring-lxd-212/

but i cant  ping/ssh on lxd  containers from local network or  from container ping/ssh/ connect only to host   can you tell how to make possible to be ports from containers reachable from local net and container will be able to connect to local network or internet. 

LXD host has IPV4 conectivity no ipv6

**Comment by brauner** [comment] 2016-10-17 13:03
This is a duplicate of https://github.com/lxc/lxd/issues/2510 and better suited there. So closing this one here.

**Closed by brauner** 2016-10-17 13:03 UTC
