### ISSUE TITLE
lxc-start errors

### ISSUE THREAD

**Issue by ruffianhy** [lxc/lxc#482] opened 2015-04-03 01:56 UTC
os:redhat7
lxc version: lxc-1.1.1
lxc os:centos
when i start the lxc with command "lxc-start -n mylxc -l debug -o lxc.log", it gives me erros below:
lxc-start 1428013869.627 ERROR    lxc_conf - conf.c:lxc_mount_auto_mounts:808 - Permission denied - error mounting /usr/local/lib/lxc/rootfs/proc/sys/net on /usr/local/lib/lxc/rootfs/proc/net flags 4096
      lxc-start 1428013869.627 ERROR    lxc_conf - conf.c:lxc_setup:3811 - failed to setup the automatic mounts for 'mylxc'
      lxc-start 1428013869.627 ERROR    lxc_start - start.c:do_start:699 - failed to setup the container
      lxc-start 1428013869.627 ERROR    lxc_sync - sync.c:__sync_wait:51 - invalid sequence number 1. expected 2
      lxc-start 1428013869.627 WARN     lxc_conf - conf.c:lxc_delete_network:2968 - failed to remove interface '(null)'
      lxc-start 1428013869.627 ERROR    lxc_start - start.c:__lxc_start:1157 - failed to spawn 'mylxc'

lxc-start 1428013874.634 ERROR    lxc_start_ui - lxc_start.c:main:344 - The container failed to start.
      lxc-start 1428013874.634 ERROR    lxc_start_ui - lxc_start.c:main:346 - To get more details, run the container in foreground mode.
      lxc-start 1428013874.634 ERROR    lxc_start_ui - lxc_start.c:main:348 - Additional information can be obtained by setting the --logfile and --logpriority options.

**Comment by cernekee** [comment] 2015-06-23 00:01
I see a similar problem, but I'm getting ELOOP instead:

```
lxc-start: conf.c: lxc_mount_auto_mounts: 819 Too many levels of symbolic links
- error mounting /var/lib/lxc/rootfs/proc/sys/net on /var/lib/lxc/rootfs/proc/net flags 4096
lxc-start: conf.c: lxc_setup: 3833 failed to setup the automatic mounts for 'busybox'
```

FWIW, /proc/net is a symlink to self/net (but I verified that the target does exist in the new namespace).  So it isn't clear to me why it's failing, but switching `lxc.mount.auto` to `proc:rw` worked around the problem.

**Comment by jirutka** [comment] 2015-08-30 19:56
I have same problem when starting unprivileged container after updating from 1.0.7 to 1.1.2.

```
# lxc-start -n mylxc -F -l DEBUG
lxc-start: conf.c: lxc_mount_auto_mounts: 819 Permission denied - error mounting sysfs on /var/lib/lxc/rootfs/sys/devices/virtual/net flags 0
lxc-start: conf.c: lxc_setup: 3833 failed to setup the automatic mounts for 'mylxc'
lxc-start: start.c: do_start: 699 failed to setup the container
lxc-start: sync.c: __sync_wait: 51 invalid sequence number 1. expected 2
lxc-start: start.c: __lxc_start: 1164 failed to spawn 'mylxc'
lxc-start: lxc_start.c: main: 344 The container failed to start.
lxc-start: lxc_start.c: main: 348 Additional information can be obtained by setting the --logfile and --logpriority options.
```

OS: Gentoo Linux
LXC version: 1.1.2

**Comment by jirutka** [comment] 2015-08-30 20:06
When I start container with `lxc.network.type = none`:

```
# lxc-start -n mylxc -F -l debug
lxc-start: conf.c: lxc_mount_auto_mounts: 819 Operation not permitted - error mounting sysfs on /var/lib/lxc/rootfs/sys flags 14
lxc-start: conf.c: lxc_setup: 3833 failed to setup the automatic mounts for 'mylxc'
lxc-start: start.c: do_start: 699 failed to setup the container
lxc-start: sync.c: __sync_wait: 51 invalid sequence number 1. expected 2
lxc-start: start.c: __lxc_start: 1164 failed to spawn 'mylxc'
lxc-start: lxc_start.c: main: 344 The container failed to start.
lxc-start: lxc_start.c: main: 348 Additional information can be obtained by setting the --logfile and --logpriority options.
```

**Comment by jirutka** [comment] 2015-08-30 20:32
I’ve tried to copy `debian.common.conf` and `debian.userns.conf` from 1.0.7 and include them from mylxc config and nothing changed, the reported error still persists. So the problem must be somewhere else.

**Comment by hallyn** [comment] 2015-08-31 05:17
On Sun, Aug 30, 2015 at 12:56:48PM -0700, Jakub Jirutka wrote:
> I have same problem when starting unprivileged container after updating from 1.0.7 to 1.1.2.

Could you try 1.1.3?

> # lxc-start -n mylxc -F -l DEBUG
> lxc-start: conf.c: lxc_mount_auto_mounts: 819 Permission denied - error mounting sysfs on /var/lib/lxc/rootfs/sys/devices/virtual/net flags 0

This actually sounds like a known kernel bug which happens when an
incomplete set of -stable patches is applied.  Can you try with an
older kernel?

**Comment by jirutka** [comment] 2015-08-31 12:33
> Could you try 1.1.3?

I did, the problem persists.

> This actually sounds like a known kernel bug which happens when an incomplete set of -stable patches is applied.

What “-stable patches?”

> Can you try with an older kernel?

I’ve tried newer kernel 4.1.6 now and problem persists. I’ll try 3.14.49 tonight.

**Comment by jirutka** [comment] 2015-08-31 12:41
Maybe I should note that I’ve compiled lxc _without_ cgmanager — it’s needed only when using cgroups inside a container, right?

**Comment by hallyn** [comment] 2015-08-31 13:25
On Mon, Aug 31, 2015 at 05:41:34AM -0700, Jakub Jirutka wrote:
> Maybe I should note that I’ve compiled lxc _without_ cgmanager — it’s needed only when using cgroups inside a container, right?

It's needed for an unprivileged user to start a container, but
your failures seem to be unrelated, having to do with mounting /sys.

**Comment by jirutka** [comment] 2015-08-31 13:30
I'm starting the container as root.

Is there anything I can do to help you investigate this issue? Maybe I can create a KVM virtual with the same setup and give you access to it.

**Comment by jirutka** [comment] 2015-09-03 00:13
I’ve finally tried to run it on older kernel (3.14.49) and I got the exact same error. I also tried lxc 1.1.0 with the same result, so the last working version is 1.0.7.

@hallyn I have prepared a VM for you, if you’re willing to take a look at this problem…?

**Comment by jirutka** [comment] 2015-09-03 23:08
OMG, I’ve spent several hours hunting a bug with totally wrong configuration! I should use `empty`, not `none` in `lxc.network.type`! But why the hell it fails with error message like that?

So there’s still a problem, but with `Permission denied - error mounting sysfs on /var/lib/lxc/rootfs/sys/devices/virtual/net flags 0`, not `Operation not permitted - error mounting sysfs on /var/lib/lxc/rootfs/sys flags 14`.

**Comment by jirutka** [comment] 2015-09-04 00:47
Heureka! My problem was caused by Grsecurity feature `CONFIG_GRKERNSEC_SYSFS_RESTRICT`. I’ve disabled this option and error `Permission denied - error mounting sysfs on /var/lib/lxc/rootfs/sys/devices/virtual/net flags 0` disappeared.

It looks quite obvious now and I feel like an idiot. If I had not come with [this wrong conclusion](https://github.com/lxc/lxc/issues/482#issuecomment-136178697), then I was solved this _much_ sooner. Grsecurity was on top of my list of suspects of course, but I was testing it only with `lxc.network.type = none`. Instead of reducing the number of possible causes I’ve been haunting totally different problem.

Well, issue is finally solved for me. It was eventually problem on my side, but you should really consider renaming `none` in `lxc.network.type`, because it’s really VERY confusing.

**Comment by brauner** [comment] 2016-07-23 09:50
Closing this since it seems to be unrelated to `lxc`.

**Closed by brauner** 2016-07-23 09:50 UTC
