### ISSUE TITLE
update-binfmts fails

### ISSUE THREAD

**Issue by v6sa** [lxc/lxc#388] opened 2014-12-24 17:27 UTC
Installing jarwrapper in trusty amd64 container fails with following errors leaving package management in inconsistent state:

    Setting up jarwrapper (0.45ubuntu1) ...
    update-binfmts: warning: unable to open /proc/sys/fs/binfmt_misc/status for writing: Permission denied
    update-binfmts: warning: unable to open /proc/sys/fs/binfmt_misc/register for writing: Permission denied
    update-binfmts: warning: unable to enable binary format jarwrapper
    update-binfmts: exiting due to previous errors

As a workaround I commented out the commands in /var/lib/dpkg/info/jarwrapper.postinst:

    if test -x /usr/sbin/update-binfmts ; then 
       update-binfmts --install jarwrapper /usr/bin/jarwrapper --magic 'PK\x03\x04' --detector /usr/bin/jardetector
    fi

**Comment by stgraber** [comment] 2015-01-26 05:35
Right, you may want to try and argue with the package maintainer that update-binfmts shouldn't be fatal. The permission denied is perfectly expected and caused by our apparmor profile as this would otherwise seriously mess up your host.

(Closing this report since LXC's doing the right thing here by blocking the write).

**Closed by stgraber** 2015-01-26 05:35 UTC
