### ISSUE TITLE
The container doesn't stop correctly (it's hangs).

### ISSUE THREAD

**Issue by vistoyn** [lxc/lxc#1362] opened 2016-12-20 16:25 UTC
Hello!

I try to install LXC 2.0.6 on debian jessie.
```
[root@debian ~]# uname -a
Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux
[root@debian ~]# cat /etc/debian_version
8.6
```

I use this script for compile LXC: 
https://github.com/vistoyn/lxc-compile/blob/2.0.6-alfa1/compile-debian-8.sh

After compile I install test centos container:
```
lxc-create -t download -n test-centos -- -d centos -r 7 -a amd64
lxc start --name test-centos
lxc stop --name test-centos
```

And it's hangs.

I try to attach to centos container:

```
lxc-attach --name test-centos
```
and stop it manually:
```
[root@test-centos /]# init 0
Warning! D-Bus connection terminated.
Failed to wait for response: Connection reset by peer
Failed to open /dev/initctl: No such device or address
Failed to talk to init daemon.
```
lol what???

I try to use debian and ubuntu containers and got same error.
Also i try to use LXC 1.1.5 and enable/disable apparmor. But it does not help.

What shall I do?

**Comment by evgeni** [comment] 2016-12-20 16:48
does the same happen when you call `shutdown`?
and why are you not using LXC 2.0.6 from backports? :)

**Comment by vistoyn** [comment] 2016-12-20 17:45
Shutdown in compile version.
```
[root@test-centos /]# shutdown
Shutdown scheduled for Tue 2016-12-20 17:30:00 UTC, use 'shutdown -c' to cancel.
[root@test-centos /]# shutdown -t now
Shutdown scheduled for Tue 2016-12-20 17:30:28 UTC, use 'shutdown -c' to cancel.
[root@test-centos /]# date
Tue Dec 20 17:32:36 UTC 2016
[root@test-centos /]# init 0
Failed to open /dev/initctl: No such device or address
Failed to talk to init daemon.
```

Shutdown in backports version.
```
[root@test-centos /]# shutdown -t now
Failed to talk to shutdownd, proceeding with immediate shutdown: Connection refused
Failed to open /dev/initctl: No such device or address
Failed to talk to init daemon.
```

The backports has got same error. 
And backports haven't lxc-net.

**Comment by vistoyn** [comment] 2016-12-20 17:46
I think the problem is in:
```
Failed to open /dev/initctl: No such device or address
```
But what does it mean?

**Comment by brauner** [comment] 2017-01-02 09:42
This usually means that the container has not booted up correctly and that the containers `/sbin/init` is not responding correctly to signals. This can happen for a variety of reasons, e.g. a version of systemd that does not behave correctly inside of a container. I tried to reproduce your issue but was unsuccessful: `shutdown`, `init 0`, `lxc-stop -n c` all worked. (@evgeni, did you manage to reproduce this?) Please append the containers configuration file, and reproduce this issue with logging enabled, i.e. start the container with `lxc-start -n c -l debug -o c.log`, perform the operations that lead to the problem and append the logs here.

**Comment by evgeni** [comment] 2017-01-02 10:26
@brauner I had no time for this issue yet, sorry.

**Comment by vistoyn** [comment] 2017-01-02 11:20
The log file:
https://gist.github.com/vistoyn/c8510a5206b287b1915aa1c7b59abad9
Deb packages:
https://github.com/vistoyn/lxc-compile/releases/tag/2.0.6-alfa1

**Comment by evgeni** [comment] 2017-01-02 11:47
@vistoyn ooh, this is a non-privileged user container? can you please retry with a privileged one? I think systemd in CentOS7 is too old to work properly in an unprivileged container.

**Comment by brauner** [comment] 2017-01-02 12:14
@evgeni, an unprivileged centos 7 container works fine for me here. This is on a ubuntu host.

**Comment by vistoyn** [comment] 2017-01-02 12:55
@evgeni
I test in Debian Jessie. The non-privileged user container work's fine. But it doesn't stops. I test container centos, debian, ubuntu. It doesn't stops too.
If I install Ubuntu as host system, the container stops fine. 
I fink the problem in the Debian Jessie as host system for LXC.

**Comment by evgeni** [comment] 2017-01-03 09:22
Works fine for me on Jessie + LXC 2.0.6 from backports and CentOS 7.3.1611 in the privileged container.

**Comment by evgeni** [comment] 2017-01-03 09:35
And reproduced on the very same system but with a user non-priv container.

**Comment by brauner** [comment] 2018-02-09 10:34
This is likely caused by faulty cgroup handling for unpriv containers. We've reworked the cgroup handling code substantially and this issue is likely fixed in master. If it still exists, please re-open.

**Closed by brauner** 2018-02-09 10:34 UTC
Labels: Incomplete
